[scripts.".awkPurgeDups"]
alias = '.awkPurgeDups'
command = '''awk '!dups[0]++' # purge duplicates'''
tags = ['annot']

[scripts.al]
alias = 'al'
command = 'clear && aliases list'
tags = ['alias']

[scripts.ald]
alias = 'ald'
command = '''
clear && aliases directories | awk 'BEGIN{FS=", "; print "initialized alias directories";} {for ( i = 1; i <= NF; i++ ) print $i}' | runiq -
'''
tags = ['alias']

[scripts.alr]
alias = 'alr'
command = '''
clear && aliases rehash && echo 'aliases reloaded'
'''
tags = ['alias']

[scripts.exaa]
alias = 'exaa'
command = '''
clear && exa --long --group-directories-first --classify --links --git --header --sort=accessed --group --all --time accessed
'''
tags = ['exa']

[scripts.exac]
alias = 'exac'
command = '''
clear && exa --long --group-directories-first --classify --links --git --header --sort=created --group --all --time created
'''
tags = ['exa']

[scripts.exal]
alias = 'exal'
command = '''
clear && exa --long --group-directories-first --classify --links --git --header --group
'''
tags = ['exa']

[scripts.exala]
alias = 'exala'
command = '''
clear && exa --long --group-directories-first --classify --links --git --header --group --all
'''
tags = ['exa']

[scripts.exalar]
alias = 'exalar'
command = '''
clear && exa --long --group-directories-first --classify --links --git --header --sort=newest --group --all
'''
tags = ['exa']

[scripts.exalr]
alias = 'exalr'
command = '''
clear && exa --long --group-directories-first --classify --links --git --header --sort=newest --group
'''
tags = ['exa']

[scripts.git]
alias = 'git'
command = 'clear && git status --show-stash && source ~/.dotfiles/rust/pier/line_break.sh && git log --oneline --decorate -20'
tags = ['git']

[scripts.git0]
alias = 'git0'
command = 'clear && source /Users/drivas/.dotfiles/git/manual_parser.sh functions'
tags = ['git']

[scripts.git1]
alias = 'git1'
command = 'clear && source /Users/drivas/.dotfiles/git/manual_parser.sh one-letter'
tags = ['git']

[scripts.git2]
alias = 'git2'
command = 'clear && source /Users/drivas/.dotfiles/git/manual_parser.sh two-letter'
tags = ['git']

[scripts.globalgit]
alias = 'globalgit'
command = '''
clear && source /Users/drivas/.dotfiles/rust/pier/git_all_status.sh
'''
tags = ['git']

[scripts.kal]
alias = 'kal'
command = '''
clear && khal calendar -f "{calendar-color}{start-time}-{end-time} {title}{description-separator}{description} {location}" -d SuperRugby -d Astronomy
'''
tags = ['khal']

[scripts.kall]
alias = 'kall'
command = 'clear && khal calendar'
tags = ['khal']

[scripts.kals]
alias = 'kals'
command = '''
clear && khal list -f "{calendar-color}{start-time}-{end-time} {title}{description-separator}{description} {location}" -d SuperRugby -d Astronomy
'''
tags = ['khal']

[scripts.kastro]
alias = 'kastro'
command = 'clear && khal calendar --include-calendar Astronomy'
tags = ['khal']

[scripts.krugby]
alias = 'krugby'
command = 'clear && khal calendar --include-calendar SuperRugby'
tags = ['khal']

[scripts.l]
alias = 'l'
command = 'clear && pier list'
tags = ['alias']

[scripts.ll]
alias = 'll'
command = '''
clear && aliases list && source /Users/drivas/.dotfiles/rust/pier/double_line_break.sh && pier list
'''
tags = ['alias']

[scripts.todo]
alias = 'todo'
command = '''
clear && todor --check
'''
tags = ['todor']

[scripts.tre]
alias = 'tre'
command = "clear && tree -h -C -a -L 3 -l -D --dirsfirst --filelimit=10 -I '.git|.idea'"
tags = ['tree']
