[scripts.al]
alias = 'al'
command = 'clear && aliases list'
tags = ['alias']

[scripts.ald]
alias = 'ald'
command = '''
clear && aliases directories | awk 'BEGIN{FS=", "; print "initialized alias directories";} {for ( i = 1; i <= NF; i++ ) print $i}' | runiq -
'''
tags = ['alias']

[scripts.alr]
alias = 'alr'
command = "aliases rehash && echo 'aliases reloaded'"
tags = ['alias']

[scripts.git]
alias = 'git'
command = 'clear && git status --show-stash && source ~/.dotfiles/rust/pier/line_break.sh && git log --oneline --decorate -20'
tags = ['git']

[scripts.git0]
alias = 'git0'
command = 'clear && source /Users/Daniel/.dotfiles/git/manual_parser.sh functions'
tags = ['git']

[scripts.git1]
alias = 'git1'
command = 'clear && source /Users/Daniel/.dotfiles/git/manual_parser.sh one-letter'
tags = ['git']

[scripts.git2]
alias = 'git2'
command = 'clear && source /Users/Daniel/.dotfiles/git/manual_parser.sh two-letter'
tags = ['git']

[scripts.globalgit]
alias = 'globalgit'
command = 'source /Users/Daniel/.dotfiles/rust/pier/git_all_status.sh'
tags = ['git']

[scripts.kastro]
alias = 'kastro'
command = 'clear && khal calendar --include-calendar Astronomy'
tags = ['khal']

[scripts.kal]
alias = 'khal'
command = 'clear && khal calendar --exclude-calendar SuperRugby --exclude-calendar Astronomy'
tags = ['kal']

[scripts.kall]
alias = 'kall'
command = 'clear && khal calendar'
tags = ['khal']

[scripts.kls]
alias = 'kls'
command = '''
clear && khal list --exclude-calendar SuperRugby --exclude-calendar Astronomy
'''
tags = ['khal']

[scripts.krugby]
alias = 'krugby'
command = 'clear && khal calendar --include-calendar SuperRugby'
tags = ['khal']

[scripts.l]
alias = 'l'
command = 'clear && pier list'
tags = ['pier']

[scripts.todo]
alias = 'todo'
command = 'todor --check'
tags = ['todor']

[scripts.tre]
alias = 'tre'
command = "clear && tree -h -C -a -L 3 -l -D --dirsfirst --filelimit=10 -I '.git|.idea'"
tags = ['tree']
