[scripts.al]
alias = 'al'
command = 'source ${PIER}aliases.sh list                                       #list aliases'
tags = ['alias']

[scripts.ald]
alias = 'ald'
command = 'source ${PIER}aliases.sh dirs                                       #list aliases directories'
tags = ['alias']

[scripts.alr]
alias = 'alr'
command = 'source ${PIER}aliases.sh reload                                     #reload aliases'
tags = ['alias']

[scripts.chd]
alias = 'chd'
command = 'source ${PIER}cheat.sh dirs                                         #list cheat directories'
tags = ['cheat']

[scripts.ch]
alias = 'ch'
command = 'source ${PIER}cheat.sh list                                         #list available cheats'
tags = ['cheat']

[scripts.cha]
alias = 'cha'
command = 'source ${PIER}cheat.sh alfred                                       #list alfred cheats'
tags = ['cheat']

[scripts.chb]
alias = 'chb'
command = 'source ${PIER}cheat.sh bash                                         #list bash cheats'
tags = ['cheat']

[scripts.chc]
alias = 'chc'
command = 'source ${PIER}cheat.sh cli                                          #list cli cheats'
tags = ['cheat']

[scripts.chg]
alias = 'chg'
command = 'source ${PIER}cheat.sh go                                           #list go cheats'
tags = ['cheat']

[scripts.chj]
alias = 'chj'
command = 'source ${PIER}cheat.sh julia                                        #list julia cheats'
tags = ['cheat']

[scripts.chp]
alias = 'chp'
command = 'source ${PIER}cheat.sh python                                       #list python cheats'
tags = ['cheat']

[scripts.chr]
alias = 'chr'
command = 'source ${PIER}cheat.sh R                                            #list R cheats'
tags = ['cheat']

[scripts.chs]
alias = 'chs'
command = 'source ${PIER}cheat.sh rust                                         #list rust cheats'
tags = ['cheat']

[scripts.exaa]
alias = 'exaa'
command = 'source ${PIER}exa.sh accessed                                       #list files by accessed time'
tags = ['exa']

[scripts.exac]
alias = 'exac'
command = 'source ${PIER}exa.sh created                                        #list files by created time'
tags = ['exa']

[scripts.exal]
alias = 'exal'
command = 'source ${PIER}exa.sh list                                           #list files'
tags = ['exa']

[scripts.exala]
alias = 'exala'
command = 'source ${PIER}exa.sh all                                            #list all files'
tags = ['exa']

[scripts.exalar]
alias = 'exalar'
command = 'source ${PIER}exa.sh all_reversed                                   #list all files by modified time'
tags = ['exa']

[scripts.exalr]
alias = 'exalr'
command = 'source ${PIER}exa.sh reversed                                       #list files by modified time'
tags = ['exa']

[scripts.exabs]
alias = 'exabs'
command = 'source ${PIER}exa.sh absolute                                       #list all files witout clusters'
tags = ['exa']

[scripts.git]
alias = 'git'
command = 'source ${PIER}git.sh                                                #all-round git status'
tags = ['git']

[scripts.globalgit]
alias = 'globalgit'
command = 'source ${PIER}git_all_status.sh                                     #all git repositoris status'
tags = ['git']

[scripts.gt0]
alias = 'gt0'
command = 'source /Users/drivas/.dotfiles/git/manual_parser.sh functions       #one-letter git shortcuts'
tags = ['git']

[scripts.gt1]
alias = 'gt1'
command = 'source /Users/drivas/.dotfiles/git/manual_parser.sh one-letter      #two-letter git shortcuts'
tags = ['git']

[scripts.gt2]
alias = 'gt2'
command = 'source /Users/drivas/.dotfiles/git/manual_parser.sh two-letter      #function git shortcuts'
tags = ['git']

[scripts.kal]
alias = 'kal'
command = 'source ${PIER}kal.sh work                                           #work calendar'
tags = ['khal']

[scripts.kall]
alias = 'kall'
command = 'source ${PIER}kal.sh all                                            #all calendars'
tags = ['khal']

[scripts.kals]
alias = 'kals'
command = 'source ${PIER}kal.sh list                                           #list calendars'
tags = ['khal']

[scripts.kastro]
alias = 'kastro'
command = 'source ${PIER}kal.sh astro                                          #astronomy calendar'
tags = ['khal']

[scripts.krugby]
alias = 'krugby'
command = 'source ${PIER}kal.sh SuperRugby                                     #SuperRugby calendar'
tags = ['khal']

[scripts.l]
alias = 'l'
command = 'source ${PIER}pier.sh list                                          #list pier commands'
tags = ['alias']

[scripts.ll]
alias = 'll'
command = 'source ${PIER}pier.sh all                                           #list aliases & pier commands'
tags = ['alias']

[scripts.todo]
alias = 'todo'
command = 'todor --check                                                       #check tags within repository'
tags = ['todor']

[scripts.tre]
alias = 'tre'
command = "source ${PIER}tre.sh                                                #tree structure constrained to 12 items & 3 levels"
tags = ['tree']
