####################################################################################################

matches:

  ####################################################################################################
  # simple text replacement
  ####################################################################################################

  # name
  - trigger: "??nm"
    replace: "Salvador Daniel Rivas Carrillo"

  - trigger: "??fnm"
    replace: "Salvador Daniel"

  - trigger: "??lnm"
    replace: "Rivas Carrillo"

  - trigger: "??dr"
    replace: "Daniel Rivas"

  # address
  - trigger: "??mail"
    replace: "danielrivasmd@gmail.com"

  - trigger: "??gad"
    replace: "Manuel Azpiroz 1790"

  - trigger: "??gzc"
    replace: "44260"

  - trigger: "??gdl"
    replace: "Guadalajara"

  - trigger: "??mxph"
    replace: "3322192477"

  - trigger: "??swph"
    replace: "767799639"

  # links
  - trigger: "??link"
    replace: "https://www.linkedin.com/in/daniel-rivas-b6306917b/"

  - trigger: "??github"
    replace: "https://github.com/DanielRivasMD"

  - trigger: "??schoolar"
    replace: "https://scholar.google.com/citations?user=zhiXeAsAAAAJ&hl=en"

  # salutation
  - trigger: "??ch"
    replace: "Cheers,"

  - trigger: "??rg"
    replace: "Regards,"

  # salutation
  - trigger: "??br"
    replace: "Best regards,"

  # salutation
  - trigger: "??sl"
    replace: "Sincerely,"

  ####################################################################################################

  # accents
  - trigger: "A//"
    replace: "Á"

  - trigger: "E//"
    replace: "É"

  - trigger: "I//"
    replace: "Í"

  - trigger: "O//"
    replace: "Ó"

  - trigger: "U//"
    replace: "Ú"

  - trigger: "A::"
    replace: "Ä"

  - trigger: "O::"
    replace: "Ö"

  - trigger: "U::"
    replace: "Ü"

  - trigger: "N--"
    replace: "Ñ"

  # accents
  - trigger: "a//"
    replace: "á"

  - trigger: "e//"
    replace: "é"

  - trigger: "i//"
    replace: "í"

  - trigger: "o//"
    replace: "ó"

  - trigger: "u//"
    replace: "ú"

  - trigger: "a::"
    replace: "ä"

  - trigger: "o::"
    replace: "ö"

  - trigger: "u::"
    replace: "ü"

  - trigger: "n--"
    replace: "ñ"

  ####################################################################################################

  # symbols
  - trigger: ";;a"
    replace: "α"

  - trigger: ";;b"
    replace: "β"

  # - trigger: ";;c"
  #   replace: ""

  - trigger: ";;d"
    replace: "δ"

  - trigger: ";;e"
    replace: "ε"

  - trigger: ";;f"
    replace: "φ"

  - trigger: ";;g"
    replace: "γ"

  - trigger: ";;h"
    replace: "η"

  - trigger: ";;i"
    replace: "ι"

  - trigger: ";;j"
    replace: "ξ"

  - trigger: ";;k"
    replace: "κ"

  - trigger: ";;l"
    replace: "λ"

  - trigger: ";;m"
    replace: "μ"

  - trigger: ";;n"
    replace: "ν"

  - trigger: ";;o"
    replace: "ο"

  - trigger: ";;p"
    replace: "π"

  # - trigger: ";;q"
  #   replace: ""

  - trigger: ";;r"
    replace: "ρ"

  - trigger: ";;s"
    replace: "σ"

  - trigger: ";;t"
    replace: "τ"

  - trigger: ";;u"
    replace: "θ"

  - trigger: ";;v"
    replace: "ω"

  # - trigger: ";;w"
  #   replace: ""

  - trigger: ";;x"
    replace: "χ"

  - trigger: ";;y"
    replace: "υ"

  - trigger: ";;z"
    replace: "ζ"

  ####################################################################################################

  # symbols  
  - trigger: ",,a"
    replace: "ɒ"

  - trigger: ",,b"
    replace: "ß"

  - trigger: ",,c"
    replace: "ç"

  - trigger: ",,d"
    replace: "Δ"

  - trigger: ",,e"
    replace: "ę"

  - trigger: ",,f"
    replace: "ƒ"

  - trigger: ",,g"
    replace: "ɣ"

  - trigger: ",,h"
    replace: "з"

  - trigger: ",,i"
    replace: "и"

  - trigger: ",,j"
    replace: "ʌ"

  - trigger: ",,k"
    replace: "ϙ"

  - trigger: ",,l"
    replace: "ł"

  - trigger: ",,m"
    replace: "ɱ"

  - trigger: ",,n"
    replace: "ŋ"

  - trigger: ",,o"
    replace: "ø"

  - trigger: ",,p"
    replace: "п"

  # - trigger: ",,q"
  #   replace: "" 

  - trigger: ",,r"
    replace: "я"

  - trigger: ",,s"
    replace: "Σ"

  # - trigger: ",,t"
  #   replace: "" 

  - trigger: ",,u"
    replace: "Θ"

  - trigger: ",,v"
    replace: "Ω"

  - trigger: ",,w"
    replace: "ʍ"

  - trigger: ",,x"
    replace: "∇"

  - trigger: ",,y"
    replace: "Λ"

  - trigger: ",,z"
    replace: "∫"

  ####################################################################################################

  # go
  - trigger: ":gp:"
    replace: "fmt.Println($|$)"

  - trigger: ":ge:"
    replace: |
      if err != nil {
        fmt.Println(err.Error())

  ####################################################################################################

  # rust
  - trigger: ":rp:"
    replace: "println{\"{:?}\"}, $|$);"

  ####################################################################################################

  # print the current date
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  ####################################################################################################

  # print the output of a shell command
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"

####################################################################################################
