####################################################################################################

[keybindings]
"<Alt-q>" = "Quit"
"<Ctrl-n>" = "BackLoopOverTabs"
"<Ctrl-p>" = "LoopOverTabs"
"<Ctrl-t>" = "ProcessReplace"
"<Ctrl-l>" = "ShowHelp"

####################################################################################################
