####################################################################################################
# just
####################################################################################################

# [[language]]
# name = "just"
# scope = "source.just"
# file-types = ["justfile", ".justfile", "JUSTFILE"]
# comment-token = "#"
# indent = { tab-width = 2, unit = "  " }
# formatter = { command = "just", args = ["--fmt", "--justfile"] }

# [[grammar]]
# name = "just"
# source = { git = "https://github.com/poliorcetics/tree-sitter-just", rev = "8d03cfdd7ab89ff76d935827de1b93450fa0ec0a" }

####################################################################################################
