####################################################################################################
# rust
####################################################################################################

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config]
check.command = "clippy"
check.features = "all"
cargo.features = "all"
cargo.autoreload = true
procMacro.enable = true

inlayHints.bindingModeHints.enable = true
inlayHints.closingBraceHints.enable = true
inlayHints.closureReturnTypeHints.enable = "with_block"
inlayHints.lifetimeElisionHints.enable = "skip_trivial"
inlayHints.typeHints.enable = true
inlayHints.chainingHints.enable = true
inlayHints.parameterHints.enable = true

diagnostics.disabled = []
diagnostics.enableExperimental = true

lens.enable = true
lens.run = true

imports.granularity.enforce = true
imports.granularity.group = "module"

completion.autoimport.enable = true
completion.fullFunctionSignatures.enable = true

workspace.symbol.search.scope = "workspace"
files.watcher = "server"

[[language]]
name = "rust"
scope = "source.rust"
injection-regex = "rs|rust"
file-types = ["rs"]
roots = ["Cargo.toml", "Cargo.lock"]
shebangs = ["rust-script", "cargo"]
auto-format = true
comment-tokens = ["//", "///", "//!"]
block-comment-tokens = [
  { start = "/*", end = "*/" },
  { start = "/**", end = "*/" },
  { start = "/*!", end = "*/" },
]
language-servers = ["rust-analyzer"]
indent = { tab-width = 4, unit = "\t" }
persistent-diagnostic-sources = ["rustc", "clippy"]

[language.auto-pairs]
'<' = '>'

[language.debugger]
name = "lldb-dap"
transport = "stdio"
command = "lldb-dap"

[[language.debugger.templates]]
name = "binary"
request = "launch"
completion = [{ name = "binary", completion = "filename" }]
args = { program = "{0}" }

[[language.debugger.templates]]
name = "binary (terminal)"
request = "launch"
completion = [{ name = "binary", completion = "filename" }]
args = { program = "{0}", runInTerminal = true }

[[language.debugger.templates]]
name = "attach"
request = "attach"
completion = ["pid"]
args = { pid = "{0}" }

[[language.debugger.templates]]
name = "gdbserver attach"
request = "attach"
completion = [
  { name = "lldb connect url", default = "connect://localhost:3333" },
  { name = "file", completion = "filename" },
  "pid",
]
args = { attachCommands = [
  "platform select remote-gdb-server",
  "platform connect {0}",
  "file {1}",
  "attach {2}",
] }

[[grammar]]
name = "rust"
source = { git = "https://github.com/tree-sitter/tree-sitter-rust", rev = "1f63b33efee17e833e0ea29266dd3d713e27e321" }

####################################################################################################
