gui:                                    # stuff relating to the UI
    windowSize: 'normal'                # 'normal' | 'half' | 'full' default 'normal'
    scrollHeight: 2                     # how many lines to scroll by
    scrollPastBottom: true              # enable scrolling past the bottom
    scrollOffMargin: 2
    scrollOffBehavior: 'margin'         # 'margin' | 'jump'
    sidePanelWidth: 0.3                 # 0 - 1
    expandFocusedSidePanel: true
    mainPanelSplitMode: 'horizontal'    # 'horizontal' | 'flexible' | 'vertical'
    language: 'en'                      # 'auto' | 'en' | 'zh' | 'pl' | 'nl'
    timeFormat: '02 Jan 06'             # https://pkg.go.dev/time#Time.Format
    shortTimeFormat: '3:04PM'
    commitLength:
        show: true
    mouseEvents: true
    skipDiscardChangeWarning: true
    skipStashWarning: false
    showFileTree: true
    showListFooter: false
    showRandomTip: false
    showBranchCommitHash: false
    showBottomLine: true
    showPanelJumps: true
    showCommandLog: false
    showIcons: false                    # deprecated: use nerdFontsVersion
    nerdFontsVersion: "3"               # 2" | "3"
    commandLogSize: 0
    splitDiff: 'auto'                   # 'auto' | 'always'
    skipRewordInEditorWarning: false
    border: 'rounded'                   # 'single' | 'double' | 'rounded' | 'hidden'
    animateExplosion: true
    ####################################################################################################
    theme:
        lightTheme: false
        activeBorderColor:
            - white
            - bold
        inactiveBorderColor:
            - green
        searchingActiveBorderColor:
            - cyan
            - bold
        optionsTextColor:
            - blue
        selectedLineBgColor:
            - default
        selectedRangeBgColor:
            - blue
        cherryPickedCommitBgColor:
            - blue
        cherryPickedCommitFgColor:
            - cyan
        unstagedChangesColor:
            - red
        defaultFgColor:
            - default
####################################################################################################
git:
  paging:
    colorArg: always
    pager: delta --dark --paging never
    commit:
        signOff: false
    merging:
        manualCommit: false
        args: ''
    log:
        order: 'topo-order'             # 'date-order' | 'author-date-order' | 'topo-order'
        showGraph: 'when-maximised'     # 'always' | 'never' | 'when-maximised'
        showWholeGraph: false
    skipHookPrefix: WIP
    mainBranches: [master, main]
    autoFetch: false
    autoRefresh: true
    fetchAll: true
    branchLogCmd: 'git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --'
    allBranchesLogCmd: 'git log --graph --all --color=always --abbrev-commit --decorate --date=relative  --pretty=medium'
    overrideGpg: false
    disableForcePushing: false
    parseEmoji: false
    diffContextSize: 5
####################################################################################################
os:
    copyToClipboardCmd: ''
    editPreset: ''
    edit: 'micro {{filename}}'
    editAtLine: ''
    editAtLineAndWait: ''
    open: ''
    openLink: ''
####################################################################################################
refresher:
    refreshInterval: 10
    fetchInterval: 60
####################################################################################################
update:
    method: 'never'                     # 'prompt' | 'background' | 'never'
    days: 0
####################################################################################################
reporting: 'undetermined'               # 'on' | 'off' | 'undetermined'
####################################################################################################
confirmOnQuit: false
####################################################################################################
quitOnTopLevelReturn: false
####################################################################################################
disableStartupPopups: false
####################################################################################################
notARepository: 'prompt' # one of: 'prompt' | 'create' | 'skip'
####################################################################################################
promptToReturnFromSubprocess: true # display confirmation when subprocess terminates
####################################################################################################

keybinding:
    universal:
        quit: 'Q'
        quit-alt1: '<c-c>'
        return: '<esc>'
        quitWithoutChangingDirectory: 'q'
        togglePanel: '<tab>'
        prevItem: null
        nextItem: null
        prevItem-alt: '<up>'
        nextItem-alt: '<down>'
        prevPage: '<f1>'
        nextPage: '<f2>'
        gotoTop: '<c-o>'
        gotoBottom: '<c-p>'
        scrollLeft: 'H'
        scrollRight: 'L'
        prevBlock: null
        nextBlock: null
        prevBlock-alt: <c-v>
        nextBlock-alt: <c-x>
        jumpToBlock: [1, 2, 3, 4, 5]
        nextMatch: 'l'
        prevMatch: 'h'
        optionMenu: null
        optionMenu-alt1: '?'
        select: '<space>'
        goInto: '<enter>'
        openRecentRepos: '<f10>'
        confirm: '<enter>'
        remove: 'd'
        new: 'n'
        edit: 'e'
        openFile: null
        scrollUpMain: null
        scrollDownMain: null
        scrollUpMain-alt1: null
        scrollDownMain-alt1: null
        scrollUpMain-alt2: 'k'
        scrollDownMain-alt2: 'j'
        executeCustomCommand: '<c-g>'
        createRebaseOptionsMenu: 'm'
        pushFiles: 'P'
        pullFiles: 'p'
        refresh: 'r'
        createPatchOptionsMenu: 'N'
        prevTab: '<f8>'
        nextTab: '<f9>'
        nextScreenMode: '<f7>'
        prevScreenMode: null
        undo: 'u'
        redo: 'U'
        diffingMenu: 'W'
        copyToClipboard: 'y'
        submitEditorText: '<enter>'
        extrasMenu: null
        toggleWhitespaceInDiffView: null
        increaseContextInDiffView: '='
        decreaseContextInDiffView: '-'
    status:
        checkForUpdate: 'u'
        recentRepos: '<enter>'
    files:
        commitChanges: 'c'
        commitChangesWithoutHook: 'w'
        amendLastCommit: 'A'
        commitChangesWithEditor: 'C'
        confirmDiscard: 'x'
        ignoreFile: 'i'
        refreshFiles: 'r'
        stashAllChanges: 's'
        viewStashOptions: 'S'
        toggleStagedAll: '<c-y>'
        viewResetOptions: 'D'
        fetch: 'f'
        toggleTreeView: '\'
        openMergeTool: 'M'
    branches:
        createPullRequest: 'u'
        viewPullRequestOptions: 'U'
        checkoutBranchByName: 'c'
        forceCheckoutBranch: 'F'
        rebaseBranch: 'r'
        renameBranch: 'R'
        mergeIntoCurrentBranch: 'M'
        viewGitFlowOptions: 'i'
        fastForward: 'f'
        createTag: 'T'
        pushTag: 'P'
        setUpstream: 'u'
        fetchRemote: 'f'
    commits:
        squashDown: 's'
        renameCommit: 'r'
        renameCommitWithEditor: 'R'
        viewResetOptions: 'g'
        markCommitAsFixup: 'f'
        createFixupCommit: 'F'
        squashAboveCommits: 'S'
        moveDownCommit: 'J'
        moveUpCommit: 'K'
        amendToCommit: 'A'
        pickCommit: 'p'
        revertCommit: 't'
        cherryPickCopy: 'c'
        cherryPickCopyRange: 'C'
        pasteCommits: 'v'
        tagCommit: 'T'
        checkoutCommit: '<space>'
        resetCherryPick: 'Y'
        copyCommitMessageToClipboard: 'y'
        openLogMenu: 'L'
        viewBisectOptions: 'b'
    stash:
        popStash: 's'
        renameStash: 'r'
    commitFiles:
        checkoutCommitFile: 'c'
    main:
        toggleDragSelect: null
        toggleDragSelect-alt: 'v'
        toggleSelectHunk: 'a'
        pickBothHunks: 'b'
    submodules:
        init: 'i'
        update: 'u'
        bulkMenu: 'b'
####################################################################################################
