####################################################################################################
# deprecations
####################################################################################################

[[keymaps]]
command = "-palette.command"
key = "F1"

[[keymaps]]
command = "-palette.command"
key = "Meta+Shift+p"

[[keymaps]]
command = "-next_editor_tab"
key = "Ctrl+Tab"

[[keymaps]]
command = "-previous_editor_tab"
key = "Ctrl+Shift+Tab"

[[keymaps]]
command = "-insert_cursor_above"
mode = "i"
key = "Alt+Meta+ArrowUp"

[[keymaps]]
command = "-insert_cursor_below"
mode = "i"
key = "Alt+Meta+ArrowDown"

[[keymaps]]
command = "-select_current_line"
mode = "i"
key = "Meta+l"

[[keymaps]]
command = "-toggle_line_comment"
key = "Meta+/"

[[keymaps]]
command = "-indent_line"
key = "Meta+]"

[[keymaps]]
command = "-outdent_line"
key = "Meta+["

[[keymaps]]
command = "-undo"
key = "Meta+z"

[[keymaps]]
command = "-redo"
key = "Meta+Shift+z"

[[keymaps]]
command = "-redo"
key = "Meta+y"

[[keymaps]]
command = "-move_line_up"
mode = "i"
key = "Alt+ArrowUp"

[[keymaps]]
command = "-move_line_down"
mode = "i"
key = "Alt+ArrowDown"

[[keymaps]]
command = "-delete_line"
mode = "i"
key = "Meta+Shift+k"

[[keymaps]]
command = "-select_next_current"
mode = "i"
key = "Meta+d"

[[keymaps]]
command = "-select_skip_current"
mode = "i"
key = "Meta+k Meta+d"

[[keymaps]]
command = "-select_all_current"
mode = "i"
key = "Meta+Shift+l"

[[keymaps]]
command = "-palette"
key = "Meta+p"

[[keymaps]]
command = "-goto_definition"
key = "F12"

[[keymaps]]
command = "-duplicate_line_down"
mode = "i"
key = "Alt+Shift+ArrowDown"

[[keymaps]]
command = "-duplicate_line_up"
mode = "i"
key = "Alt+Shift+ArrowUp"

[[keymaps]]
command = "-select_undo"
mode = "i"
key = "Meta+u"

[[keymaps]]
command = "-rename_symbol"
key = "F2"

[[keymaps]]
command = "-next_error"
key = "F8"

[[keymaps]]
command = "-previous_error"
key = "Shift+F8"

[[keymaps]]
command = "-open_keyboard_shortcuts"
key = "Meta+K Meta+S"

[[keymaps]]
command = "-delete_to_beginning_of_line"
mode = "i"
key = "Meta+backspace"

[[keymaps]]
command = "-split_vertical"
key = 'Meta+\'

[[keymaps]]
command = "-toggle_file_explorer_focus"
key = "Meta+Shift+E"

####################################################################################################
# remappings
####################################################################################################

[[keymaps]]
command = "palette"
key = "Ctrl+r"

[[keymaps]]
command = "palette.command"
key = "Ctrl+t"

[[keymaps]]
command = "next_editor_tab"
key = "Alt+Meta+ArrowRight"

[[keymaps]]
command = "previous_editor_tab"
key = "Alt+Meta+ArrowLeft"

[[keymaps]]
command = "paragraph_forward"
key = "Alt+ArrowDown"

[[keymaps]]
command = "paragraph_backward"
key = "Alt+ArrowUp"

[[keymaps]]
command = "insert_cursor_above"
mode = "i"
key = "Alt+k"

[[keymaps]]
command = "insert_cursor_below"
mode = "i"
key = "Alt+j"

[[keymaps]]
command = "select_current_line"
mode = "i"
key = "Alt+Shift+l"

[[keymaps]]
command = "toggle_line_comment"
key = "Alt+Shift+c"

[[keymaps]]
command = "indent_line"
key = "Alt+Shift+i"

[[keymaps]]
command = "outdent_line"
key = "Ctrl+F4"

[[keymaps]]
command = "undo"
key = "Alt+F4"

[[keymaps]]
command = "redo"
key = "Alt+Shift+u"

[[keymaps]]
command = "move_line_up"
mode = "i"
key = "Alt+Shift+k"

[[keymaps]]
command = "move_line_down"
mode = "i"
key = "Alt+Shift+j"

[[keymaps]]
command = "delete_line"
mode = "i"
key = "Alt+Shift+x"

[[keymaps]]
command = "next_diff"
key = "Alt+Meta+ArrowDown"

[[keymaps]]
command = "previous_diff"
key = "Alt+Meta+ArrowUp"

[[keymaps]]
command = "select_next_current"
mode = "i"
key = "Alt+d"

[[keymaps]]
command = "select_skip_current"
mode = "i"
key = "Alt+y"

[[keymaps]]
command = "select_all_current"
mode = "i"
key = "Alt+a"

[[keymaps]]
command = "select_undo"
mode = "i"
key = "Alt+z"

[[keymaps]]
command = "duplicate_line_down"
mode = "i"
key = "Alt+Shift+d"

[[keymaps]]
command = "duplicate_line_up"
mode = "i"
key = " "

[[keymaps]]
command = "next_window_tab"
key = "Ctrl+Alt+ArrowRight"

[[keymaps]]
command = "previous_window_tab"
key = "Ctrl+Alt+ArrowLeft"

[[keymaps]]
command = "show_hover"
key = "Ctrl+Space"

[[keymaps]]
command = "rename_symbol"
key = "Alt+Shift+F4"

[[keymaps]]
command = "next_error"
key = "Ctrl+x"

[[keymaps]]
command = "previous_error"
key = "Ctrl+v"

[[keymaps]]
command = "open_keyboard_shortcuts"
key = "Meta+."

[[keymaps]]
command = "delete_to_beginning_of_line"
mode = "i"
key = "Ctrl+u"

[[keymaps]]
command = "split_vertical"
key = "Alt+Shift+g"

[[keymaps]]
command = "split_horizontal"
key = "Alt+Shift+h"

[[keymaps]]
command = "goto_definition"
key = "Ctrl+Alt+Meta+Enter"

[[keymaps]]
command = "goto_type_definition"
key = "Alt+Meta+Enter"

[[keymaps]]
command = "toggle_file_explorer_focus"
key = "Alt+F1"

####################################################################################################
