
[[keymaps]]
command = "palette.command"
key = "Meta+Enter"

[[keymaps]]
command = "-palette.command"
key = "F1"

[[keymaps]]
command = "palette.command"
key = "Meta+Enter"

[[keymaps]]
command = "-palette.command"
key = "Meta+Shift+p"

[[keymaps]]
command = "next_editor_tab"
key = "Alt+Meta+ArrowRight"

[[keymaps]]
command = "-next_editor_tab"
key = "Ctrl+Tab"

[[keymaps]]
command = "previous_editor_tab"
key = "Alt+Meta+ArrowLeft"

[[keymaps]]
command = "-previous_editor_tab"
key = "Ctrl+Shift+Tab"

[[keymaps]]
command = "paragraph_forward"
key = "Alt+ArrowDown"

[[keymaps]]
command = "paragraph_backward"
key = "Alt+ArrowUp"

[[keymaps]]
command = "insert_cursor_above"
mode = "i"
key = "Alt+˚"

[[keymaps]]
command = "-insert_cursor_above"
mode = "i"
key = "Alt+Meta+ArrowUp"

[[keymaps]]
command = "insert_cursor_below"
mode = "i"
key = "Alt+∆"

[[keymaps]]
command = "-insert_cursor_below"
mode = "i"
key = "Alt+Meta+ArrowDown"

[[keymaps]]
command = "select_current_line"
mode = "i"
key = "Alt+Shift+ò"

[[keymaps]]
command = "-select_current_line"
mode = "i"
key = "Meta+l"

[[keymaps]]
command = "toggle_line_comment"
key = "Alt+Shift+ç"

[[keymaps]]
command = "-toggle_line_comment"
key = "Meta+/"

[[keymaps]]
command = "indent_line"
key = "Alt+Shift+ˆ"

[[keymaps]]
command = "-indent_line"
key = "Meta+]"

[[keymaps]]
command = "outdent_line"
key = "Ctrl+F4"

[[keymaps]]
command = "-outdent_line"
key = "Meta+["

[[keymaps]]
command = "undo"
key = "Alt+F4"

[[keymaps]]
command = "-undo"
key = "Meta+z"

[[keymaps]]
command = "redo"
key = "Alt+Shift+¨"

[[keymaps]]
command = "-redo"
key = "Meta+Shift+z"

[[keymaps]]
command = "redo"
key = "Alt+Shift+¨"

[[keymaps]]
command = "-redo"
key = "Meta+y"

[[keymaps]]
command = "move_line_up"
mode = "i"
key = "Alt+Shift+k"

[[keymaps]]
command = "-move_line_up"
mode = "i"
key = "Alt+ArrowUp"

[[keymaps]]
command = "move_line_down"
mode = "i"
key = "Alt+Shift+ô"

[[keymaps]]
command = "-move_line_down"
mode = "i"
key = "Alt+ArrowDown"

[[keymaps]]
command = "delete_line"
mode = "i"
key = "Alt+Shift+˛"

[[keymaps]]
command = "-delete_line"
mode = "i"
key = "Meta+Shift+k"

[[keymaps]]
command = "next_diff"
key = "PageDown"

[[keymaps]]
command = "select_next_current"
mode = "i"
key = "Alt+∂"

[[keymaps]]
command = "-select_next_current"
mode = "i"
key = "Meta+d"

[[keymaps]]
command = "select_skip_current"
mode = "i"
key = "Alt+¥"

[[keymaps]]
command = "-select_skip_current"
mode = "i"
key = "Meta+k Meta+d"

[[keymaps]]
command = "select_all_current"
mode = "i"
key = "Alt+å"

[[keymaps]]
command = "-select_all_current"
mode = "i"
key = "Meta+Shift+l"

[[keymaps]]
command = "palette"
key = "Ctrl+Enter"

[[keymaps]]
command = "-palette"
key = "Meta+p"

[[keymaps]]
command = "previous_diff"
key = "PageUp"

[[keymaps]]
command = "goto_definition"
key = "Ctrl+Alt+Meta+Enter"

[[keymaps]]
command = "-goto_definition"
key = "F12"

[[keymaps]]
command = "duplicate_line_down"
mode = "i"
key = "Alt+Shift+î"

[[keymaps]]
command = "-duplicate_line_down"
mode = "i"
key = "Alt+Shift+ArrowDown"

[[keymaps]]
command = "duplicate_line_up"
mode = "i"
key = " "

[[keymaps]]
command = "-duplicate_line_up"
mode = "i"
key = "Alt+Shift+ArrowUp"

[[keymaps]]
command = "select_undo"
mode = "i"
key = "Meta+z"

[[keymaps]]
command = "-select_undo"
mode = "i"
key = "Meta+u"
