####################################################################################################
# deprecations
####################################################################################################

[[keymaps]]
command = "-toggle_terminal_focus"
key = "Ctrl+`"

[[keymaps]]
command = "-move_line_up"
mode = "i"
key = "Alt+ArrowUp"

[[keymaps]]
command = "-move_line_down"
mode = "i"
key = "Alt+ArrowDown"

[[keymaps]]
command = "-duplicate_line_up"
mode = "i"
key = "Alt+Shift+ArrowUp"

[[keymaps]]
command = "-duplicate_line_down"
mode = "i"
key = "Alt+Shift+ArrowDown"

[[keymaps]]
command = "-select_skip_current"
key = "Meta+k Meta+d"

####################################################################################################
# remappings
####################################################################################################

[[keymaps]]
command = "toggle_terminal_focus"
key = "Meta+j"

[[keymaps]]
command = "paragraph_backward"
key = "Alt+ArrowUp"

[[keymaps]]
command = "paragraph_forward"
key = "Alt+ArrowDown"

[[keymaps]]
command = "select_skip_current"
key = "Alt+y"

[[keymaps]]
command = "duplicate_line_down"
key = "Alt+Shift+d"

[[keymaps]]
command = "move_line_up"
key = "Alt+Shift+k"

[[keymaps]]
command = "move_line_down"
key = "Alt+Shift+j"

[[keymaps]]
command = "next_window_tab"
key = "Alt+Ctrl+ArrowRight"

[[keymaps]]
command = "previous_window_tab"
key = "Alt+Ctrl+ArrowLeft"

####################################################################################################
