default_mode:  normal
keybinds:
    unbind:    true
    locked:
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 'q',]
    normal:
        - action: [SwitchToMode: Locked,]
          key: [Ctrl: 'q',]
        - action: [SwitchToMode: Pane,]
          key: [Ctrl: 'f',]
        - action: [SwitchToMode: Resize,]
          key: [Ctrl: 'h',]
        - action: [SwitchToMode: Tab,]
          key: [Ctrl: 'g',]
        - action: [SwitchToMode: Scroll,]
          key: [Ctrl: 's',]
        - action: [NewTab: ,]
          key: [ Alt: 'C',]
        - action: [NewPane: ,]
          key: [ Alt: 'c',]
        - action: [MoveFocus: Left,]
          key: [ Alt: 'h',]
        - action: [MoveFocus: Right,]
          key: [ Alt: 'l',]
        - action: [MoveFocus: Down,]
          key: [ Alt: 'j',]
        - action: [MoveFocus: Up,]
          key: [ Alt: 'k',]
        - action: [GoToNextTab,]
          key: [ Alt: 'H',]
    pane:
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 'q',]
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 'f',]
        - action: [SwitchToMode: Resize,]
          key: [Ctrl: 'h',]
        - action: [SwitchToMode: Tab,]
          key: [Ctrl: 'g',]
        - action: [SwitchToMode: Scroll,]
          key: [Ctrl: 's',]
        - action: [MoveFocus: Left,]
          key: [ Alt: 'h', Left,]
        - action: [MoveFocus: Right,]
          key: [ Alt: 'l', Right,]
        - action: [MoveFocus: Down,]
          key: [ Alt: 'j', Down,]
        - action: [MoveFocus: Up,]
          key: [ Alt: 'k', Up,]
        - action: [NewTab: ,]
          key: [ Alt: 'C',]
        - action: [NewPane: ,]
          key: [ Alt: 'c',]
        - action: [MoveFocus: Left,]
          key: [ Alt: 'h',]
        - action: [MoveFocus: Right,]
          key: [ Alt: 'l',]
        - action: [MoveFocus: Down,]
          key: [ Alt: 'j',]
        - action: [MoveFocus: Up,]
          key: [ Alt: 'k',]
        - action: [GoToNextTab,]
          key: [ Alt: 'H',]
    tab:
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 'q']
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 'g',]
        - action: [SwitchToMode: Pane,]
          key: [Ctrl: 'f',]
        - action: [SwitchToMode: Resize,]
          key: [Ctrl: 'h',]
        - action: [SwitchToMode: Scroll,]
          key: [Ctrl: 's',]
        - action: [GoToPreviousTab,]
          key: [ Left,]
        - action: [GoToNextTab,]
          key: [ Right,]
        - action: [NewTab: ,]
          key: [ Alt: 'C',]
        - action: [NewPane: ,]
          key: [ Alt: 'c',]
        - action: [MoveFocus: Left,]
          key: [ Alt: 'h',]
        - action: [MoveFocus: Right,]
          key: [ Alt: 'l',]
        - action: [MoveFocus: Down,]
          key: [ Alt: 'j',]
        - action: [MoveFocus: Up,]
          key: [ Alt: 'k',]
        - action: [GoToNextTab,]
          key: [ Alt: 'H',]
        - action: [CloseTab,]
          key: [ Char: 'X',]
        - action: [GoToTab: 1,]
          key: [ Char: '1',]
        - action: [GoToTab: 2,]
          key: [ Char: '2',]
        - action: [GoToTab: 3,]
          key: [ Char: '3',]
        - action: [GoToTab: 4,]
          key: [ Char: '4',]
        - action: [GoToTab: 5,]
          key: [ Char: '5',]
        - action: [GoToTab: 6,]
          key: [ Char: '6',]
        - action: [GoToTab: 7,]
          key: [ Char: '7',]
        - action: [GoToTab: 8,]
          key: [ Char: '8',]
        - action: [GoToTab: 9,]
          key: [ Char: '9',]
    resize:
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 'q']
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 'h',]
        - action: [SwitchToMode: Pane,]
          key: [Ctrl: 'f',]
        - action: [SwitchToMode: Tab,]
          key: [Ctrl: 'g',]
        - action: [SwitchToMode: Scroll,]
          key: [Ctrl: 's',]
        - action: [Resize: Left,]
          key: [Left,]
        - action: [Resize: Down,]
          key: [Down,]
        - action: [Resize: Up,]
          key: [Up, ]
        - action: [Resize: Right,]
          key: [Right,]
        - action: [NewTab: ,]
          key: [ Alt: 'C',]
        - action: [NewPane: ,]
          key: [ Alt: 'c',]
        - action: [MoveFocus: Left,]
          key: [ Alt: 'h',]
        - action: [MoveFocus: Right,]
          key: [ Alt: 'l',]
        - action: [MoveFocus: Down,]
          key: [ Alt: 'j',]
        - action: [MoveFocus: Up,]
          key: [ Alt: 'k',]
        - action: [GoToNextTab,]
          key: [ Alt: 'H',]
    scroll:
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 'q']
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 's',]
        - action: [SwitchToMode: Pane,]
          key: [Ctrl: 'f',]
        - action: [SwitchToMode: Resize,]
          key: [Ctrl: 'h',]
        - action: [SwitchToMode: Tab,]
          key: [Ctrl: 'g',]
        - action: [ScrollDown,]
          key: [Char: 'j', Down,]
        - action: [ScrollUp,]
          key: [Char: 'k', Up,]
        - action: [PageScrollDown,]
          key: [Char: 'd', PageDown,]
        - action: [PageScrollUp,]
          key: [Char: 'u', PageUp,]
        - action: [NewTab: ,]
          key: [ Alt: 'C',]
        - action: [NewPane: ,]
          key: [ Alt: 'c',]
        - action: [MoveFocus: Left,]
          key: [ Alt: 'h',]
        - action: [MoveFocus: Right,]
          key: [ Alt: 'l',]
        - action: [MoveFocus: Down,]
          key: [ Alt: 'j',]
        - action: [MoveFocus: Up,]
          key: [ Alt: 'k',]
        - action: [GoToNextTab,]
          key: [ Alt: 'H',]
