####################################################################################################

# hover
C-space = ["hover"]

####################################################################################################

# delete
del = ["delete_selection_noyank"]
backspace = ["delete_char_backward"]
A-d = ["delete_word_forward"]                              # shift-alt         # delete next word
# A-c = [""]                                               # del-shift         # none

# movement
A-b = ["move_prev_word_start", "collapse_selection"]       # alt-left          # word left
A-f = ["move_next_word_end", "collapse_selection"]         # alt-right         # word right
S-F1 = ["goto_prev_paragraph", "collapse_selection"]       # alt-up            # prev block
S-F2 = ["goto_next_paragraph", "collapse_selection"]       # alt-down          # next block

# movement
S-left = ["extend_char_left"]                              # shift-left        # select left
S-right = ["extend_char_right"]                            # shift-right       # select right
S-up = ["extend_line_above"]                               # shift-up          # select up
S-down = ["extend_line_below"]                             # shift-down        # select down

# movement
A-S-left = ["extend_prev_word_start"]                      # alt-shift-left    # select word left
A-S-right = [ "extend_next_word_end"]                      # alt-shift-right   # select word right
A-S-up = ["select_mode", "goto_prev_paragraph",
  "XXX_MODE"]                                              # alt-shift-up      # select prev block
A-S-down = ["select_mode", "goto_next_paragraph",
  "XXX_MODE"]                                              # alt-shift-down    # select next block

# movement
A-left = ["select_mode", "goto_line_start", "XXX_MODE"]    # cmd-shift-left    # select start line
A-right = ["select_mode", "goto_line_end", "XXX_MODE"]     # cmd-shift-right   # select end line
S-F4 = ["select_mode", "goto_file_start", "XXX_MODE"]      # cmd-shift-up      # select start
S-F5 = ["select_mode", "goto_last_line", "goto_line_end",
  "XXX_MODE"]                                              # cmd-shift-down    # select end

# helix pane
C-left = ["jump_view_left"]                                # ctrl-left         # prev split
C-right = ["jump_view_right"]                              # ctrl-right        # next split
C-up = ["jump_view_up"]                                    # ctrl-up           # upper split
C-down = ["jump_view_down"]                                # ctrl-down         # lower split

# helix tab
A-C-F7 = ["goto_last_accessed_file"]                       # ctrl-cmd-space    # last tab
A-C-F8 = ["goto_previous_buffer"]                          # ctrl-cmd-left     # prev tab
A-C-F9 = ["goto_next_buffer"]                              # ctrl-cmd-right    # next tab

# helix split
A-C-F10 = ["vsplit"]                                       # ctrl-cmd-alt      # vertical split
A-C-F11 = ["hsplit"]                                       # ctrl-cmd-shift    # horizontal split
A-C-F12 = ["wonly"]                                        # ctrl-cmd-cmd      # unsplit

# comments
S-F8 = ["normal_mode", "till_prev_char"]                   # ctrl-cmd-[        # prev comment
S-F9 = ["normal_mode", "find_till_char"]                   # ctrl-cmd-]        # next comment

# version control
S-F11 = ["goto_prev_change"]                               # alt-cmd-up        # prev change
S-F12 = ["goto_next_change"]                               # alt-cmd-down      # next change

# jump
A-F13 = ["jump_backward"]                                  # ctrl-cmd-;        # prev jump
A-F14 = ["jump_forward"]                                   # ctrl-cmd-'        # next jump
A-F15 = ["jumplist_picker"]                                # ctrl-cmd-\        # jump list
S-F6 = ["save_selection"]                                  # ctrl-cmd-enter    # record jump point

# diagnostics
A-F16 = ["goto_prev_diag"]                                 # ctrl-cmd-,        # prev diag
A-F17 = ["goto_next_diag"]                                 # ctrl-cmd-.        # next diag
A-F18 = ["workspace_diagnostics_picker"]                   # ctrl-cmd-/        # diag list

# symbols
A-C-F13 = ["goto_prev_class"]                              # ctrl-cmd-7        # prev class
A-C-F14 = ["goto_next_class"]                              # ctrl-cmd-8        # next class
A-C-F15 = ["goto_prev_function"]                           # ctrl-cmd-4        # prev func
A-C-F16 = ["goto_next_function"]                           # ctrl-cmd-5        # next func
A-C-F17 = ["goto_prev_parameter"]                          # ctrl-cmd-1        # prev param
A-C-F18 = ["goto_next_parameter"]                          # ctrl-cmd-2        # next param
S-F7 = ["workspace_symbol_picker"]                         # ctrl-cmd-0        # symbol list


####################################################################################################

# alphabet
# A-F1 = [""]                                              # alt-a             #
A-F2 = ["command_mode"]                                    # alt-b             # command mode
A-F4 = ["yank_joined_to_clipboard"]                        # alt-c             # copy
A-F5 = ["search_selection", "extend_search_next"]          # alt-d             # spawn multi
# A-F6 = [""]                                              # alt-e             #
A-F7 = ["search"]                                          # alt-f             # search
# A-F8 = [""]                                              # alt-g             #
A-F9 = ["search_prev"]                                     # alt-h             # find prev
# A-F10 = [""]                                             # alt-i             #
A-F11 = ["normal_mode", "copy_selection_on_next_line",
  "XXX_MODE"]                                              # alt-j             # spawn multi down
A-F12 = ["normal_mode", "copy_selection_on_prev_line",
  "XXX_MODE"]                                              # alt-k             # spawn multi up
C-F1 = ["search_next"]                                     # alt-l             # find next
# C-F2 = [""]                                              # alt-m             #
C-F4 = ["rename_symbol"]                                   # alt-n             # rename
# C-F5 = [""]                                              # alt-o             #
C-F6 = ["match_brackets"]                                  # alt-p             # jump matching
C-F7 = [":buffer-close"]                                   # alt-q             # close buffer
C-F8 = ["record_macro"]                                    # alt-r             # toggle macro
C-F9 = [":write-buffer-close"]                             # alt-s             # save & close buf
# C-F10 = [""]                                             # alt-t             #
C-F11 = ["undo"]                                           # alt-u             # undo
C-F12 = ["paste_after"]                                    # alt-v             # paste
A-C-F1 = ["normal_mode", ":write", "XXX_MODE"]             # alt-w             # save
A-C-F2 = ["delete_selection"]                              # alt-x             # cut
A-C-F4 = ["search_selection", "search_next"]               # alt-y             # skip multi
A-C-F5 = ["search_selection", "search_prev"]               # alt-z             # remove multi


####################################################################################################

# alphabet
S-A-F1 = ["select_all"]                                    # alt-shift-a       # select all
S-A-F2 = ["shell_pipe"]                                    # alt-shift-b       # shell mode
S-A-F4 = ["toggle_comments"]                               # alt-shift-c       # toggle comment
S-A-F5 = ["extend_to_line_bounds", "yank", "paste_after"]  # alt-shift-d       # duplicate line
# S-A-F6 = [""]                                            # alt-shift-e       #
S-A-F7 = ["global_search"]                                 # alt-shift-f       # global search
# S-A-F8 = [""]                                            # alt-shift-g       #
# S-A-F9 = [""]                                            # alt-shift-h       #
S-A-F10 = ["indent"]                                       # alt-shift-i       # indent
S-A-F11 = ["normal_mode", "extend_to_line_bounds", "delete_selection", "paste_after",
  "XXX_MODE"]                                              # alt-shift-j       # move down
S-A-F12 = ["normal_mode", "extend_to_line_bounds", "delete_selection", "move_line_up",
  "paste_before", "XXX_MODE"]                              # alt-shift-k       # move up
S-C-F1 = ["extend_line_below"]                             # alt-shift-l       # select line
# S-C-F2 = [""]                                            # alt-shift-m       #
# S-C-F4 = [""]                                            # alt-shift-n       #
S-C-F5 = ["unindent"]                                      # alt-shift-o       # unindent
# S-C-F6 = [""]                                            # alt-shift-p       #
S-C-F7 = [":quit"]                                         # alt-shift-q       # quit all
S-C-F8 = ["replay_macro"]                                  # alt-shift-r       # play macro
S-C-F9 = [":write-quit"]                                   # alt-shift-s       # save & quit all
# S-C-F10 = [""]                                           # alt-shift-t       #
S-C-F11 = ["redo"]                                         # alt-shift-u       # redo
# S-C-F12 = [""]                                           # alt-shift-v       #
S-A-C-F1 = ["normal_mode", ":reload-all", "XXX_MODE"]      # alt-shift-w       # reload
S-A-C-F2 = ["extend_to_line_bounds", "delete_selection"]   # alt-shift-x       # cut line
S-A-C-F4 = ["extend_to_line_bounds", "yank"]               # alt-shift-y       # copy line
# S-A-C-F5 = [""]                                          # alt-shift-z       #


####################################################################################################

# control
C-a = ["goto_line_start"]                                  # cmd-left          # start line
# C-b = [""]                                               # shift-space       # none
# C-c = [""]                                               #                   # none
# C-d = [""]                                               #                   # none
C-e = ["goto_line_end", "move_char_right"]                 # cmd-right         # end line
# C-f = [""]                                               # shift-enter       # none
# C-g = [""]                                               # del-caps          # none
# C-h = [""]                                               # del-tab           # none
# C-i = [""]                                               #                   # none
C-j = ["goto_definition"]                                  # del-cmd           # none
C-k = ["kill_to_line_end"]                                 # shift-cmd         # delete end line
# C-l = [""]                                               # shift-alt         # none
# C-m = [""]                                               #                   # none
C-n = ["goto_reference"]                                   # del-alt           # none
C-o = ["goto_file_start"]                                  # cmd-up            # cursor start
C-p = ["goto_last_line"]                                   # cmd-down          # cursor end
# C-q = [""]                                               #                   # none
C-r = ["file_picker"]                                      # del-ctrl          # file picker
C-s = ["buffer_picker"]                                    # del-alt           # buffer picker
C-t = ["command_palette"]                                  # del-cmd           # command palette
C-u = ["kill_to_line_start"]                               # shift-cmd         # delete start line
C-v = ["increment"]                                        # ctrl-cmd-up       # increment digits
C-w = ["delete_word_backward"]                             # shift-ctrl        # delete word left
C-x = ["decrement"]                                        # ctrl-cmd-down     # decrement digits
# C-y = [""]                                               # del-space         # none
# C-z = [""]                                               #                   # none


####################################################################################################

# control - command
# A-F19 = [""]                                             # ctrl-cmd-a        #
# A-F20 = [""]                                             # ctrl-cmd-b        #
# S-F13 = [""]                                             # ctrl-cmd-c        #
S-F14 = ["goto_definition"]                                # ctrl-cmd-d        #
# S-F15 = [""]                                             # ctrl-cmd-e        #
S-F16 = ["goto_implementation"]                            # ctrl-cmd-f        #
# S-F17 = [""]                                             # ctrl-cmd-g        #
# S-F18 = [""]                                             # ctrl-cmd-h        #
# S-F19 = [""]                                             # ctrl-cmd-i        #
S-F20 = ["goto_next_comment"]                              # ctrl-cmd-j        #
A-C-F19 = ["goto_prev_comment"]                            # ctrl-cmd-k        #
# A-C-F20 = [""]                                           # ctrl-cmd-l        #
A-C-S-F6 = ["normal_mode", "repeat_last_motion"]           # ctrl-cmd-m        #
A-C-S-F7 = ["goto_last_modification"]                      # ctrl-cmd-n        #
# A-C-S-F8 = [""]                                          # ctrl-cmd-o        #
# A-C-S-F9 = [""]                                          # ctrl-cmd-p        #
# A-C-S-F10 = [""]                                         # ctrl-cmd-q        #
A-C-S-F11 = ["goto_reference"]                             # ctrl-cmd-r        #
# A-C-S-F12 = [""]                                         # ctrl-cmd-s        #
A-C-S-F13 = ["goto_type_definition"]                       # ctrl-cmd-t        #
# A-C-S-F14 = [""]                                         # ctrl-cmd-u        #
# A-C-S-F15 = [""]                                         # ctrl-cmd-v        #
# A-C-S-F16 = [""]                                         # ctrl-cmd-w        #
# A-C-S-F17 = [""]                                         # ctrl-cmd-x        #
# A-C-S-F18 = [""]                                         # ctrl-cmd-y        #
# A-C-S-F19 = [""]                                         # ctrl-cmd-z        #


####################################################################################################
