####################################################################################################

[editor]
mouse = true
rulers = [100]
shell = ["zsh", "-c"]
bufferline = "always"
lsp.display-inlay-hints = false
auto-info = false

####################################################################################################

# cursor shape
[editor.cursor-shape]
normal = "bar"
insert = "underline"
select = "block"

####################################################################################################

# file picker
[editor.file-picker]
hidden = false

####################################################################################################
