####################################################################################################

[editor]
mouse = true
rulers = [100]
bufferline = "always"
shell = ["sh", "-c"]
lsp.display-inlay-hints = false

completion-replace = true
cursorline = true
cursorcolumn = true

auto-completion = false
auto-info = false
auto-format = false

####################################################################################################

[editor.gutters]
layout = ["diff", "diagnostics", "line-numbers", "spacer"]

####################################################################################################

# cursor shape
[editor.cursor-shape]
normal = "bar"
insert = "underline"
select = "block"

####################################################################################################

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = [
  "diagnostics",
  "selections",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type",
]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

####################################################################################################

# file picker
[editor.file-picker]
hidden = false

####################################################################################################

[editor.indent-guides]
render = true
character = "╎"
skip-levels = 1

####################################################################################################

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
tabpad = "·"
# newline = ""

####################################################################################################
