[colors.bright]
black = "#696969"
blue = "#007FFF"
cyan = "#00CCCC"
green = "#03C03C"
magenta = "#FF1493"
red = "#FF2400"
white = "#FFFAFA"
yellow = "#FDFF00"

[colors.normal]
black = "#10100E"
blue = "#0087BD"
cyan = "#20B2AA"
green = "#009F6B"
magenta = "#9A4EAE"
red = "#C40233"
white = "#C6C6C4"
yellow = "#FFD700"

[colors.primary]
background = "#10100E"
foreground = "#C6C6C4"

[cursor.style]
shape = "Underline"

[font]
size = 18.0

[font.bold]
family = "Hack Nerd Font"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Hack Nerd Font"

[font.normal]
family = "Hack Nerd Font"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
chars = "\u001B[3~"
key = "Delete"

[[keyboard.bindings]]
chars = "\u001B[Z"
key = "Tab"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u007F"
key = "Back"

[[keyboard.bindings]]
chars = "\u001B\u007F"
key = "Back"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[D"
key = "Left"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOD"
key = "Left"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[C"
key = "Right"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOC"
key = "Right"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[A"
key = "Up"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOA"
key = "Up"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[B"
key = "Down"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOB"
key = "Down"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001Ba"
key = "A"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[1;3A"
key = "B"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bc"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bd"
key = "D"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[1;3B"
key = "F"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bg"
key = "G"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bh"
key = "H"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bj"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bk"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bl"
key = "L"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bm"
key = "M"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bo"
key = "O"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bp"
key = "P"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bq"
key = "Q"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Br"
key = "R"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bs"
key = "S"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bt"
key = "T"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bv"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bw"
key = "W"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bx"
key = "X"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001By"
key = "Y"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bz"
key = "Z"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BA"
key = "A"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BB"
key = "B"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BC"
key = "C"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BD"
key = "D"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BE"
key = "E"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BF"
key = "F"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BG"
key = "G"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BH"
key = "H"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BI"
key = "I"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BJ"
key = "J"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BK"
key = "K"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BL"
key = "L"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BM"
key = "M"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BN"
key = "N"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BP"
key = "P"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BQ"
key = "Q"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BR"
key = "R"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BS"
key = "S"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BT"
key = "T"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BU"
key = "U"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BV"
key = "V"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BW"
key = "W"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BX"
key = "X"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BY"
key = "Y"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BZ"
key = "Z"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u0011"
key = "Q"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0011a"
key = "A"
mods = "Command"

[[keyboard.bindings]]
chars = ""
key = "B"
mods = "Command"

[[keyboard.bindings]]
chars = ""
key = "C"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0011d"
key = "D"
mods = "Command"

[[keyboard.bindings]]
chars = ""
key = "E"
mods = "Command"

[[keyboard.bindings]]
chars = ""
key = "F"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0011g"
key = "G"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0011h"
key = "H"
mods = "Command"

[[keyboard.bindings]]
chars = ""
key = "I"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0011j"
key = "J"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0011k"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = ""
key = "L"
mods = "Command"

[[keyboard.bindings]]
chars = ""
key = "M"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0011n"
key = "N"
mods = "Command"

[[keyboard.bindings]]
chars = ""
key = "O"
mods = "Command"

[[keyboard.bindings]]
chars = ""
key = "P"
mods = "Command"

[[keyboard.bindings]]
chars = ""
key = "Q"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0011r"
key = "R"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0011s"
key = "S"
mods = "Command"

[[keyboard.bindings]]
chars = ""
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = ""
key = "U"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0011w"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0011x"
key = "X"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0011y"
key = "Y"
mods = "Command"

[[keyboard.bindings]]
chars = ""
key = "Z"
mods = "Command"

[[keyboard.bindings]]
chars = ""
key = "A"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = ""
key = "B"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = ""
key = "C"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = ""
key = "D"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = ""
key = "E"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = ""
key = "F"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0011G"
key = "G"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0011H"
key = "H"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = ""
key = "I"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0011J"
key = "J"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0011K"
key = "K"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = ""
key = "L"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = ""
key = "M"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0011N"
key = "N"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = ""
key = "O"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = ""
key = "P"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = ""
key = "Q"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0011R"
key = "R"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = ""
key = "S"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = ""
key = "T"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = ""
key = "U"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = ""
key = "V"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0011W"
key = "W"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0011X"
key = "X"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = ""
key = "Y"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = ""
key = "Z"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = ""
key = "A"
mods = "Alt|Command"

[[keyboard.bindings]]
chars = ""
key = "B"
mods = "Alt|Command"

[[keyboard.bindings]]
chars = ""
key = "C"
mods = "Alt|Command"

[[keyboard.bindings]]
chars = ""
key = "D"
mods = "Alt|Command"

[[keyboard.bindings]]
chars = ""
key = "E"
mods = "Alt|Command"

[[keyboard.bindings]]
chars = ""
key = "F"
mods = "Alt|Command"

[[keyboard.bindings]]
chars = ""
key = "G"
mods = "Alt|Command"

[[keyboard.bindings]]
chars = ""
key = "H"
mods = "Alt|Command"

[[keyboard.bindings]]
chars = ""
key = "J"
mods = "Alt|Command"

[[keyboard.bindings]]
chars = ""
key = "K"
mods = "Alt|Command"

[[keyboard.bindings]]
chars = ""
key = "L"
mods = "Alt|Command"

[[keyboard.bindings]]
chars = ""
key = "M"
mods = "Alt|Command"

[[keyboard.bindings]]
chars = ""
key = "O"
mods = "Alt|Command"

[[keyboard.bindings]]
chars = ""
key = "P"
mods = "Alt|Command"

[[keyboard.bindings]]
chars = ""
key = "Q"
mods = "Alt|Command"

[[keyboard.bindings]]
chars = ""
key = "R"
mods = "Alt|Command"

[[keyboard.bindings]]
chars = ""
key = "S"
mods = "Alt|Command"

[[keyboard.bindings]]
chars = ""
key = "T"
mods = "Alt|Command"

[[keyboard.bindings]]
chars = ""
key = "U"
mods = "Alt|Command"

[[keyboard.bindings]]
chars = ""
key = "V"
mods = "Alt|Command"

[[keyboard.bindings]]
chars = ""
key = "W"
mods = "Alt|Command"

[[keyboard.bindings]]
chars = ""
key = "X"
mods = "Alt|Command"

[[keyboard.bindings]]
chars = ""
key = "Y"
mods = "Alt|Command"

[[keyboard.bindings]]
chars = ""
key = "Z"
mods = "Alt|Command"

[[keyboard.bindings]]
chars = "\u001B[20;2~"
key = "Return"
mods = "Alt|Control"

[[keyboard.bindings]]
chars = "\u001B[21;2~"
key = "Return"
mods = "Alt|Command"

[[keyboard.bindings]]
chars = "\u001B[23;2~"
key = "Return"
mods = "Control|Command"

[[keyboard.bindings]]
chars = "\u001B[24;2~"
key = "Return"
mods = "Alt|Control|Command"

[[keyboard.bindings]]
chars = "\u0011;"
key = "Space"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0011O"
key = "Space"
mods = "Alt|Control"

[[keyboard.bindings]]
chars = "\u0011L"
key = "Space"
mods = "Alt|Command"

[[keyboard.bindings]]
chars = "\u001B[19;5~"
key = "Space"
mods = "Control|Command"

[[keyboard.bindings]]
chars = "\u001B[18;5~"
key = "Space"
mods = "Control|Command|Shift"

[[keyboard.bindings]]
chars = "\u0011o"
key = "Space"
mods = "Alt|Control|Command"

[[keyboard.bindings]]
chars = "\u0011z"
key = "Space"
mods = "Alt|Control|Command|Shift"

[[keyboard.bindings]]
chars = "\u001B[1;2D"
key = "Left"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[1;5D"
key = "Left"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0001"
key = "Left"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[1;3D"
key = "Left"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001B[18;6~"
key = "Left"
mods = "Alt|Control|Shift"

[[keyboard.bindings]]
chars = "\u0011{"
key = "Left"
mods = "Alt|Command"

[[keyboard.bindings]]
chars = "\u001B[23;6~"
key = "Left"
mods = "Alt|Command|Shift"

[[keyboard.bindings]]
chars = """

"""
key = "Left"
mods = "Control|Command"

[[keyboard.bindings]]
chars = "\u0011<"
key = "Left"
mods = "Alt|Control|Command"

[[keyboard.bindings]]
chars = "\u001B[1;2C"
key = "Right"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[1;5C"
key = "Right"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0005"
key = "Right"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[1;3C"
key = "Right"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001B[19;6~"
key = "Right"
mods = "Alt|Control|Shift"

[[keyboard.bindings]]
chars = "\u0011}"
key = "Right"
mods = "Alt|Command"

[[keyboard.bindings]]
chars = "\u001B[24;6~"
key = "Right"
mods = "Alt|Command|Shift"

[[keyboard.bindings]]
chars = "\u000E"
key = "Right"
mods = "Control|Command"

[[keyboard.bindings]]
chars = "\u0011>"
key = "Right"
mods = "Alt|Control|Command"

[[keyboard.bindings]]
chars = "\u001B[1;2A"
key = "Up"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u0002"
key = "Up"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[1;5A"
key = "Up"
mods = "Control"

[[keyboard.bindings]]
chars = "\u000F"
key = "Up"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[18;3~"
key = "Up"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001B[18;4~"
key = "Up"
mods = "Alt|Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[20;3~"
key = "Up"
mods = "Alt|Command"

[[keyboard.bindings]]
chars = "\u001B[23;4~"
key = "Up"
mods = "Alt|Command|Shift"

[[keyboard.bindings]]
chars = "\u0016"
key = "Up"
mods = "Control|Command"

[[keyboard.bindings]]
chars = "\u0011+"
key = "Up"
mods = "Alt|Control|Command"

[[keyboard.bindings]]
chars = "\u001B[23;3~"
key = "Up"
mods = "Alt|Control|Command|Shift"

[[keyboard.bindings]]
chars = "\u001B[1;2B"
key = "Down"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u0006"
key = "Down"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[1;5B"
key = "Down"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0010"
key = "Down"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[19;3~"
key = "Down"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001B[19;4~"
key = "Down"
mods = "Alt|Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[21;3~"
key = "Down"
mods = "Alt|Command"

[[keyboard.bindings]]
chars = "\u001B[24;4~"
key = "Down"
mods = "Alt|Command|Shift"

[[keyboard.bindings]]
chars = "\u0018"
key = "Down"
mods = "Control|Command"

[[keyboard.bindings]]
chars = "\u0011-"
key = "Down"
mods = "Alt|Control|Command"

[[keyboard.bindings]]
chars = "\u001B[24;3~"
key = "Down"
mods = "Alt|Control|Command|Shift"

[[keyboard.bindings]]
chars = "\u001B[20;5~"
key = "PageUp"

[[keyboard.bindings]]
chars = "\u001B[21;5~"
key = "PageDown"

[[keyboard.bindings]]
chars = "\u001B[1;4P"
key = "PageUp"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;4Q"
key = "PageDown"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[15;4~"
key = "PageUp"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[17;4~"
key = "PageDown"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[20;4~"
key = "PageUp"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[21;4~"
key = "PageDown"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[23;5~"
key = "Home"

[[keyboard.bindings]]
chars = "\u001B[24;5~"
key = "End"

[[keyboard.bindings]]
chars = "\u001B[1;6P"
key = "Home"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;6Q"
key = "End"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[15;6~"
key = "Home"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[17;6~"
key = "End"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[20;6~"
key = "Home"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[21;6~"
key = "End"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00110"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00111"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00112"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00113"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00114"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00115"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00116"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00117"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00118"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00119"
key = "Key9"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0011,"
key = "Comma"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0011."
key = "Period"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0011("
key = "LBracket"
mods = "Alt|Command"

[[keyboard.bindings]]
chars = "\u0011)"
key = "RBracket"
mods = "Alt|Command"

[[keyboard.bindings]]
chars = "\u001B[15;2~"
key = "Comma"
mods = "Alt|Command"

[[keyboard.bindings]]
chars = "\u001B[17;2~"
key = "Period"
mods = "Alt|Command"

[[keyboard.bindings]]
chars = "\u001B[1;2S"
key = "Slash"
mods = "Alt|Command"

[[keyboard.bindings]]
chars = "\u001BOP"
key = "F1"

[[keyboard.bindings]]
chars = "\u001BOQ"
key = "F2"

[[keyboard.bindings]]
chars = "\u001BOR"
key = "F3"

[[keyboard.bindings]]
chars = "\u001BOS"
key = "F4"

[[keyboard.bindings]]
chars = "\u001B[15~"
key = "F5"

[[keyboard.bindings]]
chars = "\u001B[17~"
key = "F6"

[[keyboard.bindings]]
chars = "\u001B[18~"
key = "F7"

[[keyboard.bindings]]
chars = "\u001B[19~"
key = "F8"

[[keyboard.bindings]]
chars = "\u001B[20~"
key = "F9"

[[keyboard.bindings]]
chars = "\u001B[21~"
key = "F10"

[[keyboard.bindings]]
chars = "\u001B[23~"
key = "F11"

[[keyboard.bindings]]
chars = "\u001B[24~"
key = "F12"

[scrolling]
history = 0
multiplier = 3

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.6
startup_mode = "Maximized"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 5
y = 0
