####################################################################################################
# awk
####################################################################################################

[language-server.awk_lsp]
command = "awk-language-server"

[language-server.awk_lsp.config]
diagnostics = true
completion = true
hover = true

[[language]]
name = "awk"
scope = "source.awk"
injection-regex = "awk"
file-types = ["awk", "*.awk"]
shebangs = ["awk"]
comment-token = "#"
language-servers = ["awk_lsp"]
indent = { tab-width = 2, unit = "  " }

[[grammar]]
name = "awk"
source = { git = "https://github.com/Beaglefoot/tree-sitter-awk", rev = "master" }

####################################################################################################
