####################################################################################################
# clojure
####################################################################################################

[language-server]
command = "clojure-lsp"
# args = ["--stdio"]

[[language]]
name = "clojure"
scope = "source.clojure"
file-types = ["clj", "cljs", "cljc", "edn"]
roots = ["deps.edn", "project.clj", "build.boot", "shadow-cljs.edn"]
auto-format = true
indent = { tab-width = 2, unit = "\t" }

formatter = { command = "zprint", args = ["-"] }

[[grammar]]
source = { git = "https://github.com/oracle/tree-sitter-clojure", rev = "master" }
name = "clojure"
