####################################################################################################
# csv
####################################################################################################

[[language]]
name = "csv"
scope = "source.csv"
injection-regex = "csv"
file-types = ["csv", "tsv"]
indent = { tab-width = 2, unit = "  " }

[[grammar]]
name = "csv"
source = { git = "https://github.com/Kalmaegi/rainbow-csv-tree-sitter", rev = "fbf125bcedb15080980e8afaf69c4374412e5844" }

####################################################################################################
