####################################################################################################
# git
####################################################################################################

[[language]]
name = "git-commit"
scope = "git.commitmsg"
roots = [".git"]
file-types = ["COMMIT_EDITMSG"]
comment-token = "#"
indent = { tab-width = 2, unit = "  " }

[[grammar]]
name = "git-commit"
source = { git = "https://github.com/the-mikedavis/tree-sitter-git-commit", rev = "main" }

[[language]]
name = "git-diff"
scope = "source.diff"
roots = [".git"]
file-types = ["diff", "*.diff", "*.patch"]
injection-regex = "diff"
comment-token = "#"
indent = { tab-width = 2, unit = "  " }

[[grammar]]
name = "git-diff"
source = { git = "https://github.com/the-mikedavis/tree-sitter-git-diff", rev = "main" }

[[language]]
name = "git-rebase"
scope = "source.gitrebase"
roots = [".git"]
file-types = ["git-rebase-todo", "rebase-merge/git-rebase-todo"]
injection-regex = "git-rebase"
comment-token = "#"
indent = { tab-width = 2, unit = " " }

[[grammar]]
name = "git-rebase"
source = { git = "https://github.com/the-mikedavis/tree-sitter-git-rebase", rev = "main" }

[[language]]
name = "git-config"
scope = "source.gitconfig"
roots = [".git"]
file-types = [".gitmodules", ".gitconfig", ".git/config"]
injection-regex = "git-config"
comment-token = "[#;]"
indent = { tab-width = 2, unit = "\t" }

[[grammar]]
name = "git-config"
source = { git = "https://github.com/the-mikedavis/tree-sitter-git-config", rev = "main" }

[[language]]
name = "git-attributes"
scope = "source.gitattributes"
roots = [".git"]
file-types = [".gitattributes"]
injection-regex = "git-attributes"
comment-token = "#"
grammar = "gitattributes"

[[grammar]]
name = "gitattributes"
source = { git = "https://github.com/mtoohey31/tree-sitter-gitattributes", rev = "main" }

[[language]]
name = "git-ignore"
scope = "source.gitignore"
roots = [".git"]
file-types = [".gitignore", ".gitignore_global", ".git-blame-ignore-revs"]
injection-regex = "git-ignore"
comment-token = "#"
grammar = "gitignore"

[[grammar]]
name = "gitignore"
source = { git = "https://github.com/shunsambongi/tree-sitter-gitignore", rev = "main" }

[language-server.typos-lsp]
command = "typos-lsp"
args = ["--stdio"]

[[language]]
name = "git-commit"
language-servers = ["typos-lsp"]

####################################################################################################
