####################################################################################################
# html
####################################################################################################

# [[language]]
# name = "html"
# auto-format = true
# formatter = { command = "prettier", args = ["--parser", "html"] }
# indent = { tab-width = 2, unit = "  " }

####################################################################################################
