####################################################################################################
# julia
####################################################################################################

[language-server.julia_lsp]
command = "julia-sys"
args = ["--startup-file=no", "--history-file=no", "--quiet", "-e", """
  using LanguageServer, SymbolServer
  depot = get(ENV, "JULIA_DEPOT_PATH", "")
  project = Base.current_project()
  server = LanguageServer.LanguageServerInstance(stdin, stdout, project, depot)
  run(server)
  """]

[[language]]
name = "julia"
scope = "source.julia"
injection-regex = "julia"
file-types = ["jl"]
roots = ["Project.toml", "Manifest.toml"]
comment-token = "#"
language-servers = ["julia_lsp"]
indent = { tab-width = 2, unit = "  " }
auto-format = true
formatter = { command = "julia-sys", timeout = 60, args = [
  "--startup-file=no",
  "--history-file=no",
  "--quiet",
  "--project",
  "-e",
  "using JuliaFormatter; print(format_text(read(stdin, String); indent=2))",
] }

[[grammar]]
name = "julia"
source = { git = "https://github.com/tree-sitter/tree-sitter-julia", rev = "fc60b7cce87da7a1b7f8cb0f9371c3dc8b684500" }
