####################################################################################################
# julia
####################################################################################################

[language-server.julia_lsp]
command = "jlang"
args = ["lsp"]

[[language]]
name = "julia"
scope = "source.julia"
file-types = ["jl"]
roots = ["Project.toml", "Manifest.toml"]
auto-format = true
comment-token = "#"
language-servers = ["julia_lsp"]
indent = { tab-width = 2, unit = " " }
formatter = { command = "jlang", timeout = 30, args = ["format"] }

[[grammar]]
name = "julia"
source = { git = "https://github.com/tree-sitter/tree-sitter-julia", rev = "fc60b7cce87da7a1b7f8cb0f9371c3dc8b684500" }
