####################################################################################################
# julia
####################################################################################################

[language-server.julia_lsp]
command = "julia-sys"
args = ["lsp"]

[[language]]
name = "julia"
scope = "source.julia"
file-types = ["jl"]
roots = ["Project.toml", "Manifest.toml"]
language-servers = ["julia_lsp"]
auto-format = true
formatter = { command = "julia-sys", timeout = 30, args = ["formatter"] }

[[grammar]]
name = "julia"
source = { git = "https://github.com/tree-sitter/tree-sitter-julia", rev = "fc60b7cce87da7a1b7f8cb0f9371c3dc8b684500" }
