####################################################################################################
# kbd
####################################################################################################

[[language]]
name = "kbd"
scope = "source.kbd"
injection-regex = "kbd"
file-types = ["kbd", "xkb"]
comment-tokens = [";;"]
indent = { tab-width = 2, unit = "  " }

####################################################################################################
