####################################################################################################
# lua
####################################################################################################

[language-server.lua-language-server.config]
runtime.version = "Lua 5.4"
runtime.path = ["?.lua", "?/init.lua"]
diagnostics.globals = ["vim", "describe", "it", "before_each", "after_each"]
workspace.checkThirdParty = false
telemetry.enable = false

[[language]]
name = "lua"
scope = "source.lua"
injection-regex = "lua"
file-types = ["lua"]
shebangs = ["lua"]
roots = [".git", ".luarc.json", ".luarc.jsonc"]
comment-token = "--"
block-comment-tokens = { start = "--[[", end = "--]]" }
indent = { tab-width = 2, unit = "  " }
auto-format = true

[[grammar]]
name = "lua"
source = { git = "https://github.com/tree-sitter-grammars/tree-sitter-lua", rev = "main" }

####################################################################################################
