####################################################################################################
# python
####################################################################################################

[language-server.python_lsp]
command = "pylsp"

[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
file-types = ["py"]
shebangs = ["python"]
roots = []
comment-token = "#"
language-servers = ["python_lsp"]
indent = { tab-width = 2, unit = "  " }
formatter = { command = "black", args = ["-q", "-"] }
auto-format = true

[[grammar]]
name = "python"
source = { git = "https://github.com/tree-sitter/tree-sitter-python", rev = "de221eccf9a221f5b85474a553474a69b4b5784d" }

[[language]]
name = "python"
language-servers = [{ name = "pylsp", except-features = ["diagnostics"] }]

####################################################################################################
