####################################################################################################
# sql
####################################################################################################

[language-server.sqls]
command = "sqls"
args = ["-config", "sqls.yml"]

[[language]]
name = "sql"
scope = "source.sql"
injection-regex = "sql"
file-types = ["sql"]
roots = ["schema.sql", "migrations/"]
auto-format = true
comment-token = "--"
language-servers = ["sqls"]
indent = { tab-width = 2, unit = "\t" }

formatter = { command = "pg_format", args = ["--tabs", "--spaces", "2", "-"] }

[[grammar]]
source = { git = "https://github.com/DerekStride/tree-sitter-sql", rev = "0caa7fa2ee00e0b770493a79d4efacc1fc376cc5" }
name = "sql"

####################################################################################################
