####################################################################################################
# yaml
####################################################################################################

[language-server.yaml_lsp]
command = "yaml-language-server"
args = ["--stdio"]

[[language]]
name = "yaml"
scope = "source.yaml"
file-types = ["yml", "yaml"]
roots = []
comment-token = "#"
language-servers = ["yaml_lsp"]
indent = { tab-width = 2, unit = "  " }
injection-regex = "yml|yaml"

[[grammar]]
name = "yaml"
source = { git = "https://github.com/ikatyang/tree-sitter-yaml", rev = "0e36bed171768908f331ff7dff9d956bae016efb" }

####################################################################################################
