
[ui]
font-size = 18

[editor]
font-size = 18
tab-width = 2
format-on-save = true
multicursor-whole-words = false
font-family = "Hack Nerd Font"
enable-completion-lens = true
show-tab = true
modal-mode-relative-line-numbers = false
highlight-scope-lines = true
render-whitespace = "all"
atomic-soft-tabs = true
double-click = "all"
wrap-style = "none"

[core]
modal = false
color-theme = "Kanagawa Wave"
icon-theme = "Material Icons"
custom-titlebar = true

[terminal]
font-size = 18

[lapce-julia-ls]
"lsp.serverPath" = "/usr/local/bin/julia"

[lapce-rust]
serverPath = "/usr/local/bin/rust-analyzer"

[lapce-toml]
"volt.serverPath" = "/usr/local/bin/taplo"

[color-theme]

[color-theme.base]
cyan = "#00ffff"
black = "#000000"
blue = "#0000ff"
green = "#008000"
magenta = "ff00ff"
orange = "ffa500"
purple = "800080"
red = "ff0000"
white = "ffffff"
yellow = "ffff00"

[color-theme.ui]
"editor.selection" = "#800000"
"editor.caret" = "#5fb2b8"
"palette.current.background" = "#2C313C"
