[scripts.update]
command = 'source ${PIER}/.update.sh'
description = 'update homebrew, rustc compiler, & cargo & go binaries'
tags = ['update']

[scripts.forge]
command = 'source ${PIER}/.forge.sh'
description = 'observe & build alacritty, helix & karabiner'
tags = ['build']

[scripts.dir-count]
command = 'fd . --type=d --max-depth=1 | /usr/bin/wc -l'
description = 'count directories in present address'
tags = ['shell']

[scripts.file-count]
command = 'fd . --type=f --max-depth=1 | /usr/bin/wc -l'
description = 'count files in present address'
tags = ['shell']

[scripts.finder-hidden-off]
command = 'defaults write com.apple.Finder AppleShowAllFiles false && killall Finder'
description = 'turn finder hidden files on'
tags = ['shell']

[scripts.finder-hidden-on]
command = 'defaults write com.apple.Finder AppleShowAllFiles true && killall Finder'
description = 'turn finder hidden files off'
tags = ['shell']

[scripts.fpath]
command = '''
source ${PIER}/break_single_line.sh  $COLUMNS
echo $FPATH | xsv flatten -d ":" -n
'''
description = 'display fpath'
tags = ['shell']

[scripts.git]
command = '''
#!/bin/sh
source ${PIER}/break_single_line.sh $COLUMNS

git status --short
source ${PIER}/break_single_line.sh $COLUMNS

git stash list
source ${PIER}/break_double_line.sh $COLUMNS

git lk -10
source ${PIER}/break_single_line.sh $COLUMNS
'''
description = 'all-round git status'
tags = ['git']

[scripts.godoc]
command = 'godoc -http=localhost:6060; open http://localhost:6060 -a Opera'
description = 'open port for godoc'
tags = ['go']

[scripts.gopath]
command = '''
source ${PIER}/break_single_line.sh  $COLUMNS
echo $GOPATH | xsv flatten -d ":" -n | awk '{print $2}'
source ${PIER}/break_single_line.sh  $COLUMNS
'''
description = 'display GOPATH'
tags = ['go']

[scripts.gt]
command = '''
#!/bin/sh
directory="/Users/drivas/.archive/pier/"
case "$1" in
1)  bat -l "Git Config" ${HOME}/.gitconfig.d/alias_one_letter
    ;;
2)  bat -l "Git Config" ${HOME}/.gitconfig.d/alias_two_letter
    ;;
*)  bat -l "Git Config" ${HOME}/.gitconfig.d/functions
    ;;
esac
'''
description = 'list git shortcuts'
tags = ['git']

[scripts.julia]
command = 'micro /Users/drivas/Factorem/Awesome-lists/awesome-julia/README.md'
description = 'edit julia awesome list'
tags = ['julia']

[scripts.path]
command = '''
source ${PIER}/break_single_line.sh  $COLUMNS
echo $PATH | xsv flatten -d ":" -n | awk '{print $2}'
source ${PIER}/break_single_line.sh  $COLUMNS
'''
description = 'display PATH'
tags = ['shell']

[default]
