[scripts.brew-up]
command = 'zellij run --cwd $HOME --name "brew" --floating -- brew upgrade'
description = 'update packages'
tags = ['update']

[scripts.rustup-up]
command = 'zellij run --cwd $HOME --name "rustup" --floating -- rustup update'
description = 'update rust compiler'
tags = ['update']

[scripts.cargo-up]
command = 'zellij run --cwd $HOME --name "cargo" --floating -- cargo-install-update install-update --all'
description = 'update cargo binaries'
tags = ['update']

[scripts.go-up]
command = 'zellij run --cwd $HOME --name "go" --floating -- go-global-update'
description = 'update cargo binaries'
tags = ['update']

[scripts.alacritty-edit]
command = 'micro ${CERBERUS}/alacritty/alacritty.yml'
description = 'open alacritty config with micro'
tags = ['config']

[scripts.alacritty-refresh]
command = 'rm ~/.config/alacritty/alacritty.toml && alacritty migrate'
description = 'refresh alacritty config'
tags = ['config']

[scripts.bianca-sftp-ai]
command = 'sftp -qr drivas-sens2022521@bianca-sftp.uppmax.uu.se'
description = 'sftp to Bianca sens2022521'
tags = ['remote']

[scripts.bianca-sftp-ca]
command = 'sftp -qr drivas-sens2022593@bianca-sftp.uppmax.uu.se'
description = 'sftp to Bianca sens2022593'
tags = ['remote']

[scripts.bianca-sftp-im]
command = 'sftp -qr drivas-sens2019016@bianca-sftp.uppmax.uu.se'
description = 'sftp to Bianca sens2019016'
tags = ['remote']

[scripts.bianca-ssh-ai]
command = 'ssh drivas-sens2022521@bianca.uppmax.uu.se'
description = 'ssh to Bianca sens2022521'
tags = ['remote']

[scripts.bianca-ssh-ca]
command = 'ssh drivas-sens2022593@bianca.uppmax.uu.se'
description = 'ssh to Bianca sens2022593'
tags = ['remote']

[scripts.bianca-ssh-im]
command = 'ssh drivas-sens2019016@bianca.uppmax.uu.se'
description = 'ssh to Bianca sens2019016'
tags = ['remote']

[scripts.cheat-julia]
command = 'open ~/Documents/Bahlam/Biblo/Cheat_sheet/Julia/julia-cheat.html'
description = 'visualize julia cheatsheet'
tags = ['julia']

[scripts.clean-fire]
command = '''for i in $(procs Firefox | awk 'NR > 2 {print $1}' ); do kill $i; done'''
description = 'stop all Firefox jobs'
tags = ['shell']

[scripts.cpu]
command = 'procs --sortd CPU --watch'
description = 'watch resources usage CPU-sorted'
tags = ['shell']

[scripts.daemon]
command = '''sudo kill $(ps aux | awk '{if ($11 == "wdavdaemon") print $2}')'''
description = 'kill microsoft defender'
tags = ['shell']

[scripts.dir-count]
command = 'fd . --type=d --max-depth=1 | /usr/bin/wc -l'
description = 'count directories in present address'
tags = ['shell']

[scripts.file-count]
command = 'fd . --type=f --max-depth=1 | /usr/bin/wc -l'
description = 'count files in present address'
tags = ['shell']

[scripts.finder-hidden-off]
command = 'defaults write com.apple.Finder AppleShowAllFiles false && killall Finder'
description = 'turn finder hidden files on'
tags = ['shell']

[scripts.finder-hidden-on]
command = 'defaults write com.apple.Finder AppleShowAllFiles true && killall Finder'
description = 'turn finder hidden files off'
tags = ['shell']

[scripts.fpath]
command = '''
source ${PIER}/break_single_line.sh  $COLUMNS
echo $FPATH | xsv flatten -d ":" -n
'''
description = 'display fpath'
tags = ['shell']

[scripts.git]
command = '''
#!/bin/sh
source ${PIER}/break_single_line.sh $COLUMNS

git status --short
source ${PIER}/break_single_line.sh $COLUMNS

git stash list
source ${PIER}/break_double_line.sh $COLUMNS

git lk -10
source ${PIER}/break_single_line.sh  $COLUMNS
'''
description = 'all-round git status'
tags = ['git']

[scripts.godoc]
command = 'godoc -http=localhost:6060; open http://localhost:6060 -a Opera'
description = 'open port for godoc'
tags = ['go']

[scripts.gopath]
command = '''
source ${PIER}/break_single_line.sh  $COLUMNS
echo $GOPATH | xsv flatten -d ":" -n
source ${PIER}/break_single_line.sh  $COLUMNS
'''
description = 'display GOPATH'
tags = ['go']

[scripts.gt]
command = '''
#!/bin/sh
directory="/Users/drivas/.archive/pier/"
case "$1" in
1)  bat -l "Git Config" ${HOME}/.gitconfig.d/alias_one_letter
    ;;
2)  bat -l "Git Config" ${HOME}/.gitconfig.d/alias_two_letter
    ;;
*)  bat -l "Git Config" ${HOME}/.gitconfig.d/functions
    ;;
esac
'''
description = 'list git shortcuts'
tags = ['git']

[scripts.julia]
command = 'micro /Users/drivas/Factorem/Awesome-lists/awesome-julia/README.md'
description = 'edit julia awesome list'
tags = ['julia']

[scripts.kal]
command = '''
#!/bin/sh
source ${PIER}/break_single_line.sh  $COLUMNS
khal calendar \
  --format "{calendar-color}[{start-time}-{end-time}]  {title}{description-separator}{description}  ‹{location}›  «{categories}»"
source ${PIER}/break_single_line.sh  $COLUMNS
'''
description = 'all calendars'
tags = ['khal']

[scripts.kals]
command = '''
#!/bin/sh
source ${PIER}/break_single_line.sh  $COLUMNS
khal list \
  --format "{calendar-color}[{start-time}-{end-time}]  {title}{description-separator}{description}  ‹{location}›  «{categories}»" \
  --exclude-calendar SuperRugby \
  --exclude-calendar Astronomy
source ${PIER}/break_single_line.sh  $COLUMNS
'''
description = 'list calendars'
tags = ['khal']

[scripts.kastro]
command = '''
#!/bin/sh
source ${PIER}/break_single_line.sh  $COLUMNS
khal calendar \
  --include-calendar Astronomy
source ${PIER}/break_single_line.sh  $COLUMNS
'''
description = 'astronomy calendar'
tags = ['khal']

[scripts.kedit]
command = 'micro ${ARCHIVE}/cerberus/khal/khalNew.sh'
description = 'edit khal-endar event'
tags = ['khal']

[scripts.knew]
command = 'source ${ARCHIVE}/cerberus/khal/khalNew.sh & git --git-dir=${ARCHIVE}/.git --work-tree=${ARCHIVE} checkout ${ARCHIVE}/cerberus/khal/khalNew.sh'
description = 'add khal-endar event'
tags = ['khal']

[scripts.krugby]
command = '''
#!/bin/sh
source ${PIER}/break_single_line.sh  $COLUMNS
khal calendar \
  --include-calendar SuperRugby
source ${PIER}/break_single_line.sh  $COLUMNS
'''
description = 'SuperRugby calendar'
tags = ['khal']

[scripts.magnus-sftp]
command = 'sftp drivas@magnus.pawsey.org.au'
description = 'sftp to Pawsey Magnus'
tags = ['remote']

[scripts.micro]
command = 'micro ${IANUS}/micro/bindings.json'
description = 'open micro config with micro'
tags = ['shell']

[scripts.path]
command = '''
source ${PIER}/break_single_line.sh  $COLUMNS
echo $PATH | xsv flatten -d ":" -n
source ${PIER}/break_single_line.sh  $COLUMNS
'''
description = 'display PATH'
tags = ['shell']

[scripts.pier]
command = 'bat ~/.pier.toml'
description = 'print pier.toml'
tags = ['rust']

[scripts.pwd]
command = 'pwd | tr -d "\n" | cb'
description = 'copy pwd without new line'
tags = ['shell']

[scripts.sample]
command = 'sampler --config /Users/drivas/.archive/cerberus/sampler/monitor.yml'
description = 'use sample'
tags = ['go']

[scripts.tmux-catedra]
command = 'sh ~/.archive/ianus/tmux/session/catedra.sh'
description = 'launch tmux session'
tags = ['tmux']

[scripts.tmux-cohesion]
command = 'sh ~/.archive/ianus/tmux/session/cohesion.sh'
description = 'launch tmux session'
tags = ['tmux']

[scripts.tmux-control]
command = 'sh ~/.archive/ianus/tmux/session/control.sh'
description = 'launch tmux session'
tags = ['tmux']

[scripts.tmux-mind]
command = 'sh ~/.archive/ianus/tmux/session/mind.sh'
description = 'launch tmux session'
tags = ['tmux']

[scripts.topaz-sftp]
command = 'sftp drivas@topaz.pawsey.org.au'
description = 'sftp to Pawsey Topaz'
tags = ['remote']

[scripts.uppmax-sftp]
command = 'sftp drivas@rackham.uppmax.uu.se'
description = 'sftp to Uppmax Rackham'
tags = ['remote']

[default]
