####################################################################################################
# theme
####################################################################################################

# theme = "adwaita-dark"
theme = "base16_custom"
# theme = "base16_transparent"
# theme = "catppuccin_frappe"
# theme = "catppuccin_macchiato"
# theme = "catppuccin_mocha"
# theme = "dark_plus"
# theme = "fleet_dark"
# theme = "github_dark"
# theme = "molokai"
# theme = "osaka"
# theme = "snazzy"
# theme = "solarized-osaka"

####################################################################################################

####################################################################################################

[editor]
scrolloff = 3
mouse = true
rulers = [100]
bufferline = "always"
shell = ["sh", "-c"]

path-completion = true
continue-comments = false
completion-replace = false
cursorline = true
cursorcolumn = true

auto-completion = false
auto-info = true
auto-format = false

color-modes = true

end-of-line-diagnostics = "error"

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.lsp]
display-inlay-hints = true

[editor.smart-tab]
enable = false

####################################################################################################

[editor.gutters]
layout = ["diff", "diagnostics", "line-numbers", "spacer"]

####################################################################################################

# cursor shape
[editor.cursor-shape]
normal = "bar"
insert = "underline"
select = "block"

####################################################################################################

[editor.statusline]
left = ["mode", "spinner", "diagnostics"]
center = [
	"file-modification-indicator",
	"file-name",
	"read-only-indicator",
	"version-control",
]
right = [
	"selections",
	"position",
	"primary-selection-length",
	"file-encoding",
	"file-type",
]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"


####################################################################################################

[editor.file-picker]
hidden = false

####################################################################################################

[editor.indent-guides]
render = true
character = "╎"
skip-levels = 1

####################################################################################################

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "␣"
tab = "→"
tabpad = "·"
newline = "↵"

####################################################################################################

####################################################################################################

# [keys.insert.j]
# j = "normal_mode"


[keys.normal."space"]
r = ":config-reload"
ret = "command_palette"

a = "no_op"
b = "no_op"
c = "no_op"
d = "no_op"
e = "no_op"
f = "no_op"
g = "no_op"
h = "no_op"
j = "no_op"
k = "no_op"
p = "no_op"
# r = "no_op"
s = "no_op"
w = "no_op"
y = "no_op"

C = "no_op"
D = "no_op"
E = "no_op"
F = "no_op"
G = "no_op"
P = "no_op"
R = "no_op"
S = "no_op"
Y = "no_op"

A-c = "no_op"

"'" = "no_op"
"/" = "no_op"
"?" = "no_op"


[keys.normal.g]
a = "no_op"
b = "no_op"
c = "no_op"
d = "no_op"
e = "no_op"
f = "no_op"
g = "no_op"
h = "no_op"
i = "no_op"
j = "no_op"
k = "no_op"
l = "no_op"
m = "no_op"
n = "no_op"
p = "no_op"
r = "no_op"
s = "no_op"
t = "no_op"
w = "no_op"
y = "no_op"
D = "no_op"

"." = "no_op"
"|" = "no_op"


####################################################################################################

# diagnostics mini mode
[keys.normal."\\"]
up =  "goto_prev_diag"
down =  "goto_next_diag"
ret =  "workspace_diagnostics_picker"
"\\" =  "diagnostics_picker"

####################################################################################################

# language server protocol mini mode
[keys.normal.z]
z = "symbol_picker"
n = "rename_symbol"
r = "goto_reference"
d = "goto_definition"
i = "goto_implementation"
t = "goto_type_definition"
ret = "code_action"

b = "no_op"
c = "no_op"
j = "no_op"
k = "no_op"
m = "no_op"
# n = "no_op"
N = "no_op"
p = "no_op"
# t = "no_op"
# z = "no_op"
space = "no_op"

up = "no_op"
down = "no_op"
backspace = "no_op"
pageup = "no_op"
pagedown = "no_op"

C-b = "no_op"
C-d = "no_op"
C-f = "no_op"
C-u = "no_op"

"/" = "no_op"
"?" = "no_op"


[keys.normal.Z]
ret = "workspace_symbol_picker"
d = ["vsplit", "goto_definition"]
t = ["vsplit", "goto_type_definition"]

b = "no_op"
c = "no_op"
j = "no_op"
k = "no_op"
m = "no_op"
n = "no_op"
N = "no_op"
p = "no_op"
# t = "no_op"
z = "no_op"

space = "no_op"
up = "no_op"
down = "no_op"
backspace = "no_op"
pageup = "no_op"
pagedown = "no_op"

C-b = "no_op"
C-d = "no_op"
C-f = "no_op"
C-u = "no_op"

"/" = "no_op"
"?" = "no_op"

####################################################################################################

[keys.normal]
A-ret = ["hover"]
S-F13 = ["insert_mode"]
A-S-up = ["select_mode","goto_prev_paragraph","normal_mode"]
A-S-down = ["select_mode","goto_next_paragraph","normal_mode"]


C-a = ["goto_line_start"]
C-e = ["goto_line_end","move_char_right"]
A-S-F5 = ["global_search"]
A-S-x = ["extend_to_line_bounds","delete_selection_noyank"]
C-right = ["jump_view_right"]
A-S-r = [":sh zellij run --name serpl    --pinned true  --close-on-exit --floating  --width 180 --height  60 --x   0 --y   0 -- serpl"]
pageup = ["goto_prev_paragraph","collapse_selection"]
C-x = ["scroll_up"]
C-r = ["changed_file_picker"]
C-o = ["goto_last_accessed_file"]
pagedown = ["goto_next_paragraph","collapse_selection"]
A-l = ["search_next"]
A-S-v = ["replace_selections_with_clipboard"]
C-up = ["jump_view_up"]
A-S-F1 = [":sh zellij run --name watch    --pinned true  --close-on-exit --floating  --width  90 --height  30 --x  90 --y   0 -- btm"]
C-y = ["scroll_down"]
A-S-i = ["indent"]
C-p = ["goto_next_comment"]
A-S-F4 = ["extend_to_line_bounds","yank","paste_after","goto_line_start"]
S-up = ["extend_line_up"]
C-end = ["increment"]
S-right = ["extend_char_right"]
A-pagedown = ["redo"]
A-S-t = [":sh zellij run --name todor    --pinned true  --close-on-exit --floating  --width  90 --height  30 --x  90 --y   0 -- todor --delete"]
C-t = ["buffer_picker"]
A-F15 = ["switch_case"]
S-left = ["extend_char_left"]
A-S-right = ["extend_next_word_end"]
A-y = ["search_selection","search_next"]
A-k = ["normal_mode","copy_selection_on_prev_line","normal_mode"]
A-e = ["toggle_comments"]
C-pagedown = ["normal_mode","find_till_char","normal_mode"]
A-end = ["goto_next_change"]
A-F14 = ["switch_to_uppercase"]
A-F16 = ["repeat_last_motion"]
C-g = [":buffer-close"]
C-b = ["goto_previous_buffer"]
A-home = ["goto_prev_change"]
A-S-j = ["normal_mode","extend_to_line_bounds","delete_selection","paste_after","normal_mode"]
C-home = ["decrement"]
C-k = ["kill_to_line_end"]
C-u = ["kill_to_line_start"]
A-up = ["extend_to_file_start"]
esc = ["collapse_selection","keep_primary_selection"]
A-d = ["delete_word_forward"]
A-q = ["normal_mode",":quit-all"]
C-down = ["jump_view_down"]
home = ["goto_file_start"]
A-t = [":sh just todor"]
A-pageup = ["undo"]
A-a = [":format"]
C-f = ["goto_next_buffer"]
backspace = ["delete_char_backward"]
A-h = ["search_prev"]
A-S-F2 = ["extend_to_line_bounds","yank_to_clipboard"]
del = ["delete_selection_noyank"]
S-F17 = ["jump_backward"]
A-right = ["select_mode","goto_line_end","normal_mode"]
A-f = ["move_next_word_end","collapse_selection"]
A-z = ["search_selection","search_prev"]
A-left = ["select_mode","goto_line_start","normal_mode"]
A-S-z = [":yank-diagnostic"]
end = ["goto_last_line"]
C-h = ["hsplit"]
A-r = ["normal_mode",":reload-all","normal_mode"]
C-l = ["file_picker"]
A-S-F6 = ["unindent"]
C-w = ["delete_word_backward"]
A-S-m = ["replay_macro"]
A-S-F10 = [":sh zellij run --name canvas   --pinned false --close-on-exit --floating  --width 180 --height  90 --x   0 --y   0 -- zsh"]
A-b = ["move_prev_word_start","collapse_selection"]
A-m = ["record_macro"]
A-v = ["paste_clipboard_before"]
A-F17 = ["goto_last_modification"]
A-x = ["yank_to_clipboard","delete_selection_noyank"]
A-F13 = ["switch_to_lowercase"]
A-S-k = ["normal_mode","extend_to_line_bounds","delete_selection","move_line_up","paste_before","normal_mode"]
A-S-e = [":sh zellij run --name explorer --pinned true  --close-on-exit --floating  --width 180 --height  60 --x   0 --y   0 -- yazi $(pwd)"]
C-s = ["file_explorer"]
A-F4 = ["search_selection","extend_search_next"]
S-F14 = ["save_selection"]
S-F16 = ["jumplist_picker"]
A-F2 = ["yank_to_clipboard"]
A-S-l = ["goto_line_end","select_mode","goto_line_start","normal_mode"]
A-S-left = ["extend_prev_word_start"]
C-v = ["vsplit"]
A-n = [":new"]
A-F10 = ["command_mode"]
A-j = ["normal_mode","copy_selection_on_next_line","normal_mode"]
S-down = ["extend_line_down"]
A-w = ["normal_mode",":write"]
A-down = ["extend_to_file_end"]
C-space = ["goto_word"]
C-pageup = ["normal_mode","till_prev_char","normal_mode"]
C-n = ["goto_prev_comment"]
A-S-q = [":sh zellij run --name lazygit  --pinned true  --close-on-exit --floating  --width 180 --height  60 --x   0 --y   0 -- lazygit"]
A-s = ["normal_mode",":write-quit-all"]
C-j = ["wonly"]
C-left = ["jump_view_left"]
S-F15 = ["jump_forward"]
A-S-w = [":sh zellij run --name watch    --pinned true  --close-on-exit --floating  --width  45 --height  20 --x 135 --y   0 -- just watch"]
A-F5 = ["search"]
A-S-a = ["select_all"]



[keys.insert]
A-ret = ["completion"]
S-F13 = ["normal_mode"]
A-S-up = ["select_mode","goto_prev_paragraph","insert_mode"]
A-S-down = ["select_mode","goto_next_paragraph","append_mode"]


C-a = ["goto_line_start"]
C-e = ["goto_line_end","move_char_right"]
A-S-F5 = ["global_search"]
A-S-x = ["extend_to_line_bounds","delete_selection_noyank"]
C-right = ["jump_view_right"]
A-S-r = [":sh zellij run --name serpl    --pinned true  --close-on-exit --floating  --width 180 --height  60 --x   0 --y   0 -- serpl"]
pageup = ["goto_prev_paragraph","collapse_selection"]
C-x = ["scroll_up"]
C-r = ["changed_file_picker"]
C-o = ["goto_last_accessed_file"]
pagedown = ["goto_next_paragraph","collapse_selection"]
A-l = ["search_next"]
A-S-v = ["replace_selections_with_clipboard"]
C-up = ["jump_view_up"]
A-S-F1 = [":sh zellij run --name watch    --pinned true  --close-on-exit --floating  --width  90 --height  30 --x  90 --y   0 -- btm"]
C-y = ["scroll_down"]
A-S-i = ["indent"]
C-p = ["goto_next_comment"]
A-S-F4 = ["extend_to_line_bounds","yank","paste_after","goto_line_start"]
S-up = ["extend_line_up"]
C-end = ["increment"]
S-right = ["extend_char_right"]
A-pagedown = ["redo"]
A-S-t = [":sh zellij run --name todor    --pinned true  --close-on-exit --floating  --width  90 --height  30 --x  90 --y   0 -- todor --delete"]
C-t = ["buffer_picker"]
A-F15 = ["switch_case"]
S-left = ["extend_char_left"]
A-S-right = ["extend_next_word_end"]
A-y = ["search_selection","search_next"]
A-k = ["normal_mode","copy_selection_on_prev_line","insert_mode"]
A-e = ["toggle_comments"]
C-pagedown = ["normal_mode","find_till_char","insert_mode"]
A-end = ["goto_next_change"]
A-F14 = ["switch_to_uppercase"]
A-F16 = ["repeat_last_motion"]
C-g = [":buffer-close"]
C-b = ["goto_previous_buffer"]
A-home = ["goto_prev_change"]
A-S-j = ["normal_mode","extend_to_line_bounds","delete_selection","paste_after","insert_mode"]
C-home = ["decrement"]
C-k = ["kill_to_line_end"]
C-u = ["kill_to_line_start"]
A-up = ["extend_to_file_start"]
esc = ["collapse_selection","keep_primary_selection"]
A-d = ["delete_word_forward"]
A-q = ["normal_mode",":quit-all"]
C-down = ["jump_view_down"]
home = ["goto_file_start"]
A-t = [":sh just todor"]
A-pageup = ["undo"]
A-a = [":format"]
C-f = ["goto_next_buffer"]
backspace = ["delete_char_backward"]
A-h = ["search_prev"]
A-S-F2 = ["extend_to_line_bounds","yank_to_clipboard"]
del = ["delete_selection_noyank"]
S-F17 = ["jump_backward"]
A-right = ["select_mode","goto_line_end","insert_mode"]
A-f = ["move_next_word_end","collapse_selection"]
A-z = ["search_selection","search_prev"]
A-left = ["select_mode","goto_line_start","insert_mode"]
A-S-z = [":yank-diagnostic"]
end = ["goto_last_line"]
C-h = ["hsplit"]
A-r = ["normal_mode",":reload-all","insert_mode"]
C-l = ["file_picker"]
A-S-F6 = ["unindent"]
C-w = ["delete_word_backward"]
A-S-m = ["replay_macro"]
A-S-F10 = [":sh zellij run --name canvas   --pinned false --close-on-exit --floating  --width 180 --height  90 --x   0 --y   0 -- zsh"]
A-b = ["move_prev_word_start","collapse_selection"]
A-m = ["record_macro"]
A-v = ["paste_clipboard_before"]
A-F17 = ["goto_last_modification"]
A-x = ["yank_to_clipboard","delete_selection_noyank"]
A-F13 = ["switch_to_lowercase"]
A-S-k = ["normal_mode","extend_to_line_bounds","delete_selection","move_line_up","paste_before","insert_mode"]
A-S-e = [":sh zellij run --name explorer --pinned true  --close-on-exit --floating  --width 180 --height  60 --x   0 --y   0 -- yazi $(pwd)"]
C-s = ["file_explorer"]
A-F4 = ["search_selection","extend_search_next"]
S-F14 = ["save_selection"]
S-F16 = ["jumplist_picker"]
A-F2 = ["yank_to_clipboard"]
A-S-l = ["goto_line_end","select_mode","goto_line_start","insert_mode"]
A-S-left = ["extend_prev_word_start"]
C-v = ["vsplit"]
A-n = [":new"]
A-F10 = ["command_mode"]
A-j = ["normal_mode","copy_selection_on_next_line","insert_mode"]
S-down = ["extend_line_down"]
A-w = ["normal_mode",":write"]
A-down = ["extend_to_file_end"]
C-space = ["goto_word"]
C-pageup = ["normal_mode","till_prev_char","insert_mode"]
C-n = ["goto_prev_comment"]
A-S-q = [":sh zellij run --name lazygit  --pinned true  --close-on-exit --floating  --width 180 --height  60 --x   0 --y   0 -- lazygit"]
A-s = ["normal_mode",":write-quit-all"]
C-j = ["wonly"]
C-left = ["jump_view_left"]
S-F15 = ["jump_forward"]
A-S-w = [":sh zellij run --name watch    --pinned true  --close-on-exit --floating  --width  45 --height  20 --x 135 --y   0 -- just watch"]
A-F5 = ["search"]
A-S-a = ["select_all"]



[keys.select]
A-ret = ["hover"]
A-S-up = ["select_mode","goto_prev_paragraph","select_mode"]
A-S-down = ["select_mode","goto_next_paragraph","select_mode"]
S-F13 = ["normal_mode"]


C-a = ["goto_line_start"]
C-e = ["goto_line_end","move_char_right"]
A-S-F5 = ["global_search"]
A-S-x = ["extend_to_line_bounds","delete_selection_noyank"]
C-right = ["jump_view_right"]
A-S-r = [":sh zellij run --name serpl    --pinned true  --close-on-exit --floating  --width 180 --height  60 --x   0 --y   0 -- serpl"]
pageup = ["goto_prev_paragraph","collapse_selection"]
C-x = ["scroll_up"]
C-r = ["changed_file_picker"]
C-o = ["goto_last_accessed_file"]
pagedown = ["goto_next_paragraph","collapse_selection"]
A-l = ["search_next"]
A-S-v = ["replace_selections_with_clipboard"]
C-up = ["jump_view_up"]
A-S-F1 = [":sh zellij run --name watch    --pinned true  --close-on-exit --floating  --width  90 --height  30 --x  90 --y   0 -- btm"]
C-y = ["scroll_down"]
A-S-i = ["indent"]
C-p = ["goto_next_comment"]
A-S-F4 = ["extend_to_line_bounds","yank","paste_after","goto_line_start"]
S-up = ["extend_line_up"]
C-end = ["increment"]
S-right = ["extend_char_right"]
A-pagedown = ["redo"]
A-S-t = [":sh zellij run --name todor    --pinned true  --close-on-exit --floating  --width  90 --height  30 --x  90 --y   0 -- todor --delete"]
C-t = ["buffer_picker"]
A-F15 = ["switch_case"]
S-left = ["extend_char_left"]
A-S-right = ["extend_next_word_end"]
A-y = ["search_selection","search_next"]
A-k = ["normal_mode","copy_selection_on_prev_line","select_mode"]
A-e = ["toggle_comments"]
C-pagedown = ["normal_mode","find_till_char","select_mode"]
A-end = ["goto_next_change"]
A-F14 = ["switch_to_uppercase"]
A-F16 = ["repeat_last_motion"]
C-g = [":buffer-close"]
C-b = ["goto_previous_buffer"]
A-home = ["goto_prev_change"]
A-S-j = ["normal_mode","extend_to_line_bounds","delete_selection","paste_after","select_mode"]
C-home = ["decrement"]
C-k = ["kill_to_line_end"]
C-u = ["kill_to_line_start"]
A-up = ["extend_to_file_start"]
esc = ["collapse_selection","keep_primary_selection"]
A-d = ["delete_word_forward"]
A-q = ["normal_mode",":quit-all"]
C-down = ["jump_view_down"]
home = ["goto_file_start"]
A-t = [":sh just todor"]
A-pageup = ["undo"]
A-a = [":format"]
C-f = ["goto_next_buffer"]
backspace = ["delete_char_backward"]
A-h = ["search_prev"]
A-S-F2 = ["extend_to_line_bounds","yank_to_clipboard"]
del = ["delete_selection_noyank"]
S-F17 = ["jump_backward"]
A-right = ["select_mode","goto_line_end","select_mode"]
A-f = ["move_next_word_end","collapse_selection"]
A-z = ["search_selection","search_prev"]
A-left = ["select_mode","goto_line_start","select_mode"]
A-S-z = [":yank-diagnostic"]
end = ["goto_last_line"]
C-h = ["hsplit"]
A-r = ["normal_mode",":reload-all","select_mode"]
C-l = ["file_picker"]
A-S-F6 = ["unindent"]
C-w = ["delete_word_backward"]
A-S-m = ["replay_macro"]
A-S-F10 = [":sh zellij run --name canvas   --pinned false --close-on-exit --floating  --width 180 --height  90 --x   0 --y   0 -- zsh"]
A-b = ["move_prev_word_start","collapse_selection"]
A-m = ["record_macro"]
A-v = ["paste_clipboard_before"]
A-F17 = ["goto_last_modification"]
A-x = ["yank_to_clipboard","delete_selection_noyank"]
A-F13 = ["switch_to_lowercase"]
A-S-k = ["normal_mode","extend_to_line_bounds","delete_selection","move_line_up","paste_before","select_mode"]
A-S-e = [":sh zellij run --name explorer --pinned true  --close-on-exit --floating  --width 180 --height  60 --x   0 --y   0 -- yazi $(pwd)"]
C-s = ["file_explorer"]
A-F4 = ["search_selection","extend_search_next"]
S-F14 = ["save_selection"]
S-F16 = ["jumplist_picker"]
A-F2 = ["yank_to_clipboard"]
A-S-l = ["goto_line_end","select_mode","goto_line_start","select_mode"]
A-S-left = ["extend_prev_word_start"]
C-v = ["vsplit"]
A-n = [":new"]
A-F10 = ["command_mode"]
A-j = ["normal_mode","copy_selection_on_next_line","select_mode"]
S-down = ["extend_line_down"]
A-w = ["normal_mode",":write"]
A-down = ["extend_to_file_end"]
C-space = ["goto_word"]
C-pageup = ["normal_mode","till_prev_char","select_mode"]
C-n = ["goto_prev_comment"]
A-S-q = [":sh zellij run --name lazygit  --pinned true  --close-on-exit --floating  --width 180 --height  60 --x   0 --y   0 -- lazygit"]
A-s = ["normal_mode",":write-quit-all"]
C-j = ["wonly"]
C-left = ["jump_view_left"]
S-F15 = ["jump_forward"]
A-S-w = [":sh zellij run --name watch    --pinned true  --close-on-exit --floating  --width  45 --height  20 --x 135 --y   0 -- just watch"]
A-F5 = ["search"]
A-S-a = ["select_all"]



