####################################################################################################
# theme
####################################################################################################

# theme = "adwaita-dark"
theme = "base16_custom"
# theme = "base16_transparent"
# theme = "catppuccin_frappe"
# theme = "catppuccin_macchiato"
# theme = "catppuccin_mocha"
# theme = "dark_plus"
# theme = "fleet_dark"
# theme = "github_dark"
# theme = "molokai"
# theme = "osaka"
# theme = "snazzy"
# theme = "solarized-osaka"

####################################################################################################

####################################################################################################

[editor]
scrolloff = 3
mouse = true
rulers = [100]
bufferline = "always"
shell = ["sh", "-c"]

completion-replace = false
cursorline = true
cursorcolumn = true

auto-completion = false
auto-info = true
auto-format = false

color-modes = true

end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.lsp]
display-inlay-hints = true

[editor.smart-tab]
enable = false

####################################################################################################

[editor.gutters]
layout = ["diff", "diagnostics", "line-numbers", "spacer"]

####################################################################################################

# cursor shape
[editor.cursor-shape]
normal = "bar"
insert = "underline"
select = "block"

####################################################################################################

[editor.statusline]
left = ["mode", "spinner", "diagnostics"]
center = [
	"file-modification-indicator",
	"file-name",
	"read-only-indicator",
	"version-control",
]
right = [
	"selections",
	"position",
	"primary-selection-length",
	"file-encoding",
	"file-type",
]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"


####################################################################################################

# file picker
[editor.file-picker]
hidden = false

####################################################################################################

[editor.indent-guides]
render = true
character = "╎"
skip-levels = 1

####################################################################################################

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "␣"
tab = "→"
tabpad = "·"
newline = "↵"

####################################################################################################

####################################################################################################

[keys.insert.j]
j = { j = "normal_mode" }

# create a new minor mode bound to `+`
[keys.normal.","]
"-" = "swap_view_left"
"=" = "swap_view_right"
";" = "goto_file"
"'" = "wclose"
"\\" = "wonly"
"/" = "rotate_view"

[keys.normal."space"]
# TODO: possible to overwrite mini-modes now
f = "no_op"
r = ":config-reload"
q = "switch_case"
left = "goto_previous_buffer"
right = "goto_next_buffer"
space = "goto_last_accessed_file"

[keys.normal."/"]
"[" = "rsearch"
"]" = "search"
";" = "search_prev"
"'" = "search_next"
"\\" = "search_selection"
"|" = "search_selection_detect_word_boundaries"

[keys.normal."\\"]
"[" = "shell_pipe"
"]" = "shell_pipe_to"
";" = "shell_insert_output"
"'" = "shell_append_output"
"\\" = "shell_keep_pipe"

[keys.normal."+"]
m = ":run-shell-command make"
c = ":run-shell-command cargo build"
t = ":run-shell-command cargo test"

####################################################################################################

[keys.normal]
A-ret = ["hover"]
F13 = ["insert_mode"]
A-S-up = ["select_mode","goto_prev_paragraph","normal_mode"]
A-S-down = ["select_mode","goto_next_paragraph","normal_mode"]


A-left = ["select_mode","goto_line_start","normal_mode"]
A-right = ["select_mode","goto_line_end","normal_mode"]
A-S-F2 = ["extend_to_line_bounds","yank_to_clipboard"]
A-h = ["search_prev"]
A-S-q = [":sh zellij run --name lazygit --pinned true  --close-on-exit --floating  --width 180 --height  60 --x   0 --y   0 -- lazygit"]
pageup = ["goto_prev_paragraph","collapse_selection"]
A-end = ["goto_next_change"]
C-h = ["hsplit"]
A-S-a = ["select_all"]
A-S-left = ["extend_prev_word_start"]
A-pageup = ["undo"]
A-S-m = ["replay_macro"]
C-F15 = ["goto_last_modification"]
S-left = ["extend_char_left"]
C-a = ["goto_line_start"]
C-F14 = ["workspace_diagnostics_picker"]
home = ["goto_file_start"]
A-y = ["search_selection","search_next"]
C-down = ["jump_view_down"]
A-w = ["normal_mode",":write"]
A-F16 = ["repeat_last_motion"]
A-S-F15 = ["rename_symbol"]
end = ["goto_last_line"]
C-left = ["jump_view_left"]
S-F16 = ["jump_backward"]
A-S-F5 = ["global_search"]
C-w = ["delete_word_backward"]
C-o = ["goto_last_accessed_file"]
C-home = ["goto_prev_comment"]
C-pageup = ["normal_mode","till_prev_char","normal_mode"]
A-F15 = ["vsplit","goto_type_definition"]
C-F12 = ["goto_next_diag"]
C-u = ["kill_to_line_start"]
pagedown = ["goto_next_paragraph","collapse_selection"]
A-v = ["paste_clipboard_before"]
C-r = ["changed_file_picker"]
A-S-F10 = [":sh zellij run --name canvas  --pinned false --close-on-exit --floating  --width 180 --height  90 --x   0 --y   0 -- zsh"]
A-F14 = ["vsplit","goto_definition"]
S-F15 = ["jumplist_picker"]
S-F14 = ["jump_forward"]
A-up = ["extend_to_file_start"]
C-F13 = ["diagnostics_picker"]
A-S-r = [":sh zellij run --name serpl   --pinned true  --close-on-exit --floating  --width 180 --height  60 --x   0 --y   0 -- serpl"]
A-j = ["normal_mode","copy_selection_on_next_line","normal_mode"]
A-q = ["normal_mode",":quit-all"]
A-S-l = ["goto_line_end","select_mode","goto_line_start","normal_mode"]
A-b = ["move_prev_word_start","collapse_selection"]
backspace = ["delete_char_backward"]
C-t = ["buffer_picker"]
C-j = ["wclose"]
A-e = ["toggle_comments"]
C-up = ["jump_view_up"]
A-a = [":format"]
A-l = ["search_next"]
S-down = ["extend_line_down"]
A-S-k = ["normal_mode","extend_to_line_bounds","delete_selection","move_line_up","paste_before","normal_mode"]
C-F11 = ["goto_prev_diag"]
C-f = ["goto_next_buffer"]
A-S-x = ["extend_to_line_bounds","delete_selection_noyank"]
A-f = ["move_next_word_end","collapse_selection"]
A-S-i = ["indent"]
C-v = ["vsplit"]
del = ["delete_selection_noyank"]
A-home = ["goto_prev_change"]
S-F13 = ["save_selection"]
A-S-w = [":sh zellij run --name canvas  --pinned true  --close-on-exit --floating  --width  45 --height  20 --x 135 --y   0 -- just watch"]
C-b = ["goto_previous_buffer"]
A-F10 = ["command_mode"]
A-t = [":sh just todor"]
A-F13 = ["symbol_picker"]
A-S-F14 = ["goto_implementation"]
A-n = [":new"]
A-S-F17 = ["goto_type_definition"]
A-S-F6 = ["unindent"]
A-s = ["normal_mode",":write-quit-all"]
S-up = ["extend_line_up"]
C-g = ["wonly"]
A-S-right = ["extend_next_word_end"]
C-end = ["goto_next_comment"]
A-r = ["normal_mode",":reload-all","normal_mode"]
C-x = ["scroll_up"]
A-F2 = ["yank_to_clipboard"]
C-pagedown = ["normal_mode","find_till_char","normal_mode"]
A-S-F16 = ["goto_reference"]
A-S-j = ["normal_mode","extend_to_line_bounds","delete_selection","paste_after","normal_mode"]
C-y = ["scroll_down"]
C-n = ["increment"]
C-right = ["jump_view_right"]
A-F5 = ["search"]
C-k = ["kill_to_line_end"]
A-k = ["normal_mode","copy_selection_on_prev_line","normal_mode"]
S-right = ["extend_char_right"]
esc = ["collapse_selection","keep_primary_selection"]
C-e = ["goto_line_end","move_char_right"]
A-S-z = [":yank-diagnostic"]
A-F4 = ["search_selection","extend_search_next"]
C-space = ["goto_word"]
A-S-t = [":sh zellij run --name todor   --pinned true  --close-on-exit --floating  --width  90 --height  30 --x  90 --y   0 -- todor --delete"]
A-pagedown = ["redo"]
A-S-F4 = ["extend_to_line_bounds","yank","paste_after","goto_line_start"]
C-l = [":buffer-close"]
A-z = ["search_selection","search_prev"]
C-s = ["file_picker"]
A-d = ["delete_word_forward"]
A-x = ["yank_to_clipboard","delete_selection_noyank"]
A-S-F13 = ["goto_definition"]
C-p = ["decrement"]
A-down = ["extend_to_file_end"]
A-m = ["record_macro"]



[keys.insert]
A-ret = ["completion"]
F13 = ["normal_mode"]
A-S-up = ["select_mode","goto_prev_paragraph","insert_mode"]
A-S-down = ["select_mode","goto_next_paragraph","append_mode"]


A-left = ["select_mode","goto_line_start","insert_mode"]
A-right = ["select_mode","goto_line_end","insert_mode"]
A-S-F2 = ["extend_to_line_bounds","yank_to_clipboard"]
A-h = ["search_prev"]
A-S-q = [":sh zellij run --name lazygit --pinned true  --close-on-exit --floating  --width 180 --height  60 --x   0 --y   0 -- lazygit"]
pageup = ["goto_prev_paragraph","collapse_selection"]
A-end = ["goto_next_change"]
C-h = ["hsplit"]
A-S-a = ["select_all"]
A-S-left = ["extend_prev_word_start"]
A-pageup = ["undo"]
A-S-m = ["replay_macro"]
C-F15 = ["goto_last_modification"]
S-left = ["extend_char_left"]
C-a = ["goto_line_start"]
C-F14 = ["workspace_diagnostics_picker"]
home = ["goto_file_start"]
A-y = ["search_selection","search_next"]
C-down = ["jump_view_down"]
A-w = ["normal_mode",":write"]
A-F16 = ["repeat_last_motion"]
A-S-F15 = ["rename_symbol"]
end = ["goto_last_line"]
C-left = ["jump_view_left"]
S-F16 = ["jump_backward"]
A-S-F5 = ["global_search"]
C-w = ["delete_word_backward"]
C-o = ["goto_last_accessed_file"]
C-home = ["goto_prev_comment"]
C-pageup = ["normal_mode","till_prev_char","insert_mode"]
A-F15 = ["vsplit","goto_type_definition"]
C-F12 = ["goto_next_diag"]
C-u = ["kill_to_line_start"]
pagedown = ["goto_next_paragraph","collapse_selection"]
A-v = ["paste_clipboard_before"]
C-r = ["changed_file_picker"]
A-S-F10 = [":sh zellij run --name canvas  --pinned false --close-on-exit --floating  --width 180 --height  90 --x   0 --y   0 -- zsh"]
A-F14 = ["vsplit","goto_definition"]
S-F15 = ["jumplist_picker"]
S-F14 = ["jump_forward"]
A-up = ["extend_to_file_start"]
C-F13 = ["diagnostics_picker"]
A-S-r = [":sh zellij run --name serpl   --pinned true  --close-on-exit --floating  --width 180 --height  60 --x   0 --y   0 -- serpl"]
A-j = ["normal_mode","copy_selection_on_next_line","insert_mode"]
A-q = ["normal_mode",":quit-all"]
A-S-l = ["goto_line_end","select_mode","goto_line_start","insert_mode"]
A-b = ["move_prev_word_start","collapse_selection"]
backspace = ["delete_char_backward"]
C-t = ["buffer_picker"]
C-j = ["wclose"]
A-e = ["toggle_comments"]
C-up = ["jump_view_up"]
A-a = [":format"]
A-l = ["search_next"]
S-down = ["extend_line_down"]
A-S-k = ["normal_mode","extend_to_line_bounds","delete_selection","move_line_up","paste_before","insert_mode"]
C-F11 = ["goto_prev_diag"]
C-f = ["goto_next_buffer"]
A-S-x = ["extend_to_line_bounds","delete_selection_noyank"]
A-f = ["move_next_word_end","collapse_selection"]
A-S-i = ["indent"]
C-v = ["vsplit"]
del = ["delete_selection_noyank"]
A-home = ["goto_prev_change"]
S-F13 = ["save_selection"]
A-S-w = [":sh zellij run --name canvas  --pinned true  --close-on-exit --floating  --width  45 --height  20 --x 135 --y   0 -- just watch"]
C-b = ["goto_previous_buffer"]
A-F10 = ["command_mode"]
A-t = [":sh just todor"]
A-F13 = ["symbol_picker"]
A-S-F14 = ["goto_implementation"]
A-n = [":new"]
A-S-F17 = ["goto_type_definition"]
A-S-F6 = ["unindent"]
A-s = ["normal_mode",":write-quit-all"]
S-up = ["extend_line_up"]
C-g = ["wonly"]
A-S-right = ["extend_next_word_end"]
C-end = ["goto_next_comment"]
A-r = ["normal_mode",":reload-all","insert_mode"]
C-x = ["scroll_up"]
A-F2 = ["yank_to_clipboard"]
C-pagedown = ["normal_mode","find_till_char","insert_mode"]
A-S-F16 = ["goto_reference"]
A-S-j = ["normal_mode","extend_to_line_bounds","delete_selection","paste_after","insert_mode"]
C-y = ["scroll_down"]
C-n = ["increment"]
C-right = ["jump_view_right"]
A-F5 = ["search"]
C-k = ["kill_to_line_end"]
A-k = ["normal_mode","copy_selection_on_prev_line","insert_mode"]
S-right = ["extend_char_right"]
esc = ["collapse_selection","keep_primary_selection"]
C-e = ["goto_line_end","move_char_right"]
A-S-z = [":yank-diagnostic"]
A-F4 = ["search_selection","extend_search_next"]
C-space = ["goto_word"]
A-S-t = [":sh zellij run --name todor   --pinned true  --close-on-exit --floating  --width  90 --height  30 --x  90 --y   0 -- todor --delete"]
A-pagedown = ["redo"]
A-S-F4 = ["extend_to_line_bounds","yank","paste_after","goto_line_start"]
C-l = [":buffer-close"]
A-z = ["search_selection","search_prev"]
C-s = ["file_picker"]
A-d = ["delete_word_forward"]
A-x = ["yank_to_clipboard","delete_selection_noyank"]
A-S-F13 = ["goto_definition"]
C-p = ["decrement"]
A-down = ["extend_to_file_end"]
A-m = ["record_macro"]



[keys.select]
A-ret = ["hover"]
A-S-up = ["select_mode","goto_prev_paragraph","select_mode"]
A-S-down = ["select_mode","goto_next_paragraph","select_mode"]
F13 = ["normal_mode"]


A-left = ["select_mode","goto_line_start","select_mode"]
A-right = ["select_mode","goto_line_end","select_mode"]
A-S-F2 = ["extend_to_line_bounds","yank_to_clipboard"]
A-h = ["search_prev"]
A-S-q = [":sh zellij run --name lazygit --pinned true  --close-on-exit --floating  --width 180 --height  60 --x   0 --y   0 -- lazygit"]
pageup = ["goto_prev_paragraph","collapse_selection"]
A-end = ["goto_next_change"]
C-h = ["hsplit"]
A-S-a = ["select_all"]
A-S-left = ["extend_prev_word_start"]
A-pageup = ["undo"]
A-S-m = ["replay_macro"]
C-F15 = ["goto_last_modification"]
S-left = ["extend_char_left"]
C-a = ["goto_line_start"]
C-F14 = ["workspace_diagnostics_picker"]
home = ["goto_file_start"]
A-y = ["search_selection","search_next"]
C-down = ["jump_view_down"]
A-w = ["normal_mode",":write"]
A-F16 = ["repeat_last_motion"]
A-S-F15 = ["rename_symbol"]
end = ["goto_last_line"]
C-left = ["jump_view_left"]
S-F16 = ["jump_backward"]
A-S-F5 = ["global_search"]
C-w = ["delete_word_backward"]
C-o = ["goto_last_accessed_file"]
C-home = ["goto_prev_comment"]
C-pageup = ["normal_mode","till_prev_char","select_mode"]
A-F15 = ["vsplit","goto_type_definition"]
C-F12 = ["goto_next_diag"]
C-u = ["kill_to_line_start"]
pagedown = ["goto_next_paragraph","collapse_selection"]
A-v = ["paste_clipboard_before"]
C-r = ["changed_file_picker"]
A-S-F10 = [":sh zellij run --name canvas  --pinned false --close-on-exit --floating  --width 180 --height  90 --x   0 --y   0 -- zsh"]
A-F14 = ["vsplit","goto_definition"]
S-F15 = ["jumplist_picker"]
S-F14 = ["jump_forward"]
A-up = ["extend_to_file_start"]
C-F13 = ["diagnostics_picker"]
A-S-r = [":sh zellij run --name serpl   --pinned true  --close-on-exit --floating  --width 180 --height  60 --x   0 --y   0 -- serpl"]
A-j = ["normal_mode","copy_selection_on_next_line","select_mode"]
A-q = ["normal_mode",":quit-all"]
A-S-l = ["goto_line_end","select_mode","goto_line_start","select_mode"]
A-b = ["move_prev_word_start","collapse_selection"]
backspace = ["delete_char_backward"]
C-t = ["buffer_picker"]
C-j = ["wclose"]
A-e = ["toggle_comments"]
C-up = ["jump_view_up"]
A-a = [":format"]
A-l = ["search_next"]
S-down = ["extend_line_down"]
A-S-k = ["normal_mode","extend_to_line_bounds","delete_selection","move_line_up","paste_before","select_mode"]
C-F11 = ["goto_prev_diag"]
C-f = ["goto_next_buffer"]
A-S-x = ["extend_to_line_bounds","delete_selection_noyank"]
A-f = ["move_next_word_end","collapse_selection"]
A-S-i = ["indent"]
C-v = ["vsplit"]
del = ["delete_selection_noyank"]
A-home = ["goto_prev_change"]
S-F13 = ["save_selection"]
A-S-w = [":sh zellij run --name canvas  --pinned true  --close-on-exit --floating  --width  45 --height  20 --x 135 --y   0 -- just watch"]
C-b = ["goto_previous_buffer"]
A-F10 = ["command_mode"]
A-t = [":sh just todor"]
A-F13 = ["symbol_picker"]
A-S-F14 = ["goto_implementation"]
A-n = [":new"]
A-S-F17 = ["goto_type_definition"]
A-S-F6 = ["unindent"]
A-s = ["normal_mode",":write-quit-all"]
S-up = ["extend_line_up"]
C-g = ["wonly"]
A-S-right = ["extend_next_word_end"]
C-end = ["goto_next_comment"]
A-r = ["normal_mode",":reload-all","select_mode"]
C-x = ["scroll_up"]
A-F2 = ["yank_to_clipboard"]
C-pagedown = ["normal_mode","find_till_char","select_mode"]
A-S-F16 = ["goto_reference"]
A-S-j = ["normal_mode","extend_to_line_bounds","delete_selection","paste_after","select_mode"]
C-y = ["scroll_down"]
C-n = ["increment"]
C-right = ["jump_view_right"]
A-F5 = ["search"]
C-k = ["kill_to_line_end"]
A-k = ["normal_mode","copy_selection_on_prev_line","select_mode"]
S-right = ["extend_char_right"]
esc = ["collapse_selection","keep_primary_selection"]
C-e = ["goto_line_end","move_char_right"]
A-S-z = [":yank-diagnostic"]
A-F4 = ["search_selection","extend_search_next"]
C-space = ["goto_word"]
A-S-t = [":sh zellij run --name todor   --pinned true  --close-on-exit --floating  --width  90 --height  30 --x  90 --y   0 -- todor --delete"]
A-pagedown = ["redo"]
A-S-F4 = ["extend_to_line_bounds","yank","paste_after","goto_line_start"]
C-l = [":buffer-close"]
A-z = ["search_selection","search_prev"]
C-s = ["file_picker"]
A-d = ["delete_word_forward"]
A-x = ["yank_to_clipboard","delete_selection_noyank"]
A-S-F13 = ["goto_definition"]
C-p = ["decrement"]
A-down = ["extend_to_file_end"]
A-m = ["record_macro"]



