####################################################################################################

[[language]]
name = "python"
language-servers = [{ name = "pylsp", except-features = ["diagnostics"] }]

####################################################################################################

[[language]]
name = "rust"
auto-format = false

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

####################################################################################################
