####################################################################################################

check_version = true
check_help = true
check = [["-v", "-V", "--version", "version"], ["-h", "-H", "--help", "help"]]
man_command = "batman"
pager_command = "bat --paging=always --color=always"
cheat_sh_url = "https://cheat.sh"
eg_url = "https://raw.githubusercontent.com/srsudar/eg/master/eg/examples"
cheatsheets_url = "https://raw.githubusercontent.com/cheat/cheatsheets/master"
timeout = 5

####################################################################################################
