
[scripts.cChrome]
alias = 'cChrome'
command = '''for i in $(procs 'Google Chrome' --or chromedriver | awk 'NR > 2 {print $1}' ); do kill $i; done'''
description = 'stop all Chrome jobs'
tags = ['shell']

[scripts.cFire]
alias = 'cFire'
command = '''for i in $(procs Firefox | awk 'NR > 2 {print $1}' ); do kill $i; done'''
description = 'stop all Firefox jobs'
tags = ['shell']

[scripts.dc]
alias = 'dc'
command = 'fd . --type=d --max-depth=1 | /usr/bin/wc -l'
description = 'count directories in present address'
tags = ['shell']

[scripts.fc]
alias = 'fc'
command = 'fd . --type=f --max-depth=1 | /usr/bin/wc -l'
description = 'count files in present address'
tags = ['shell']

[scripts.t-uppmax]
alias = 't-uppmax'
command = 'source ~/.tmux/sessions/Uppmax.sh'
description = 'three-tab remote anchor [ monitor channel remote ]'
tags = ['tmux']

[scripts.t-bianca]
alias = 't-bianca'
command = 'source ~/.tmux/sessions/Bianca.sh'
description = 'three-tab remote anchor [ monitor channel remote ]'
tags = ['tmux']

[scripts.t-dev]
alias = 't-dev'
command = 'source ~/.tmux/sessions/Dev.sh'
description = 'three-tab development [ monitor zsh zsh ]'
tags = ['tmux']

[scripts.t-repl]
alias = 'tmux-repl'
command = 'source ~/.tmux/sessions/REPL.sh'
description = 'Julia two-tab session [ monitor julia ]'
tags = ['tmux']

[scripts.cd]
alias = 'cd'
command = '''
#!/bin/zsh
  cheat -d | \
  awk '
  BEGIN{
    gray = "\033[1;30m"
    cyan = "\033[0;36m"
  }
  {
    printf "%s ", gray "|";
    printf "%-30s", cyan $1;
    printf "%s ", gray "|";
    printf "%-51s ", $2;
    printf "%1s\n", "|";
  }
  '
'''
description = 'list cheat directories'
tags = ['alias']

[scripts.ch]
alias = 'ch'
command = '''
#!/bin/zsh
cheat -l "$1" | \
awk '
BEGIN{

  # colors
  red = "\033[1;31m"
  gray = "\033[1;30m"
  blue = "\033[1;34m"
  yellow = "\033[1;33m"
  cyan = "\033[0;36m"
  green = "\033[0;32m"
}

{
  if ( NR == 1 )
  {

    # decompose printf
    printf "%s ", gray "|";
    printf "%-40s", blue $1;
    printf "%s", gray "|";
    printf "%49s ", blue $3;
    printf "%s\n", gray "|";

    for ( m = 1; m <= 80; m++ )
    {
      printf "%s", gray "‡";
    }
    print ""
  }
else
  {

    # replicate as header
    printf "%s ", gray "|";
    printf "%-40s", yellow $1;
    printf "%s", gray "|";
    printf "%49s ", cyan $3;
    printf "%s\n", gray "|";
  }
}
'
'''
description = 'list available cheats'
tags = ['cheat']

[scripts.cpu]
alias = 'cpu'
command = 'procs --sortd CPU --watch'
description = 'watch resources usage CPU-sorted'
tags = ['shell']

[scripts.git]
alias = 'git'
command = '''
#!/bin/zsh
source ${PIER}break_single_line.sh ${MANWIDTH}

git status --show-stash
source ${PIER}break_single_line.sh ${MANWIDTH}

git stash list
source ${PIER}break_double_line.sh ${MANWIDTH}

git lk -20
source ${PIER}break_single_line.sh ${MANWIDTH}
'''
description = 'all-round git status'
tags = ['git']

[scripts.gt0]
alias = 'gt0'
command = '''
#!/bin/zsh
directory="/Users/drivas/.dotfiles/git/"
source ${PIER}break_single_line.sh ${MANWIDTH}
awk -f ${directory}manual_parser.awk ${directory}gitconfig.d/functions
source ${PIER}break_single_line.sh ${MANWIDTH}
'''
description = 'function git shortcuts'
tags = ['git']

[scripts.gt1]
alias = 'gt1'
command = '''
#!/bin/zsh
directory="/Users/drivas/.dotfiles/git/"
source ${PIER}break_single_line.sh ${MANWIDTH}
awk -f ${directory}manual_parser.awk ${directory}gitconfig.d/alias_one_letter
source ${PIER}break_single_line.sh ${MANWIDTH}
'''
description = 'one-letter git shortcuts'
tags = ['git']

[scripts.gt2]
alias = 'gt2'
command = '''
#!/bin/zsh
directory="/Users/drivas/.dotfiles/git/"
source ${PIER}break_single_line.sh ${MANWIDTH}
awk -f ${directory}manual_parser.awk ${directory}gitconfig.d/alias_two_letter
source ${PIER}break_single_line.sh ${MANWIDTH}
'''
description = 'two-letter git shortcuts'
tags = ['git']

[scripts.kal]
alias = 'kal'
command = '''
#!/bin/zsh
source ${PIER}break_single_line.sh ${MANWIDTH}
khal calendar
source ${PIER}break_single_line.sh ${MANWIDTH}
'''
description = 'all calendars'
tags = ['khal']

[scripts.kals]
alias = 'kals'
command = '''
#!/bin/zsh
source ${PIER}break_single_line.sh ${MANWIDTH}
khal list \
  -f "{calendar-color}[{start-time}-{end-time}]  {title}{description-separator}{description}  ‹{location}›  «{categories}»" \
  -d SuperRugby \
  -d Astronomy
source ${PIER}break_single_line.sh ${MANWIDTH}
'''
description = 'list calendars'
tags = ['khal']

[scripts.kastro]
alias = 'kastro'
command = '''
#!/bin/zsh
source ${PIER}break_single_line.sh ${MANWIDTH}
khal calendar \
  --include-calendar Astronomy
source ${PIER}break_single_line.sh ${MANWIDTH}
'''
description = 'astronomy calendar'
tags = ['khal']

[scripts.kaw]
alias = 'kaw'
command = '''
#!/bin/zsh
source ${PIER}break_single_line.sh ${MANWIDTH}
khal calendar \
  -f "{calendar-color}[{start-time}-{end-time}]  {title}{description-separator}{description}  ‹{location}›  «{categories}»" \
  -d SuperRugby \
  -d Astronomy
source ${PIER}break_single_line.sh ${MANWIDTH}
'''
description = 'work calendar'
tags = ['khal']

[scripts.krugby]
alias = 'krugby'
command = '''
#!/bin/zsh
source ${PIER}break_single_line.sh ${MANWIDTH}
khal calendar \
  --include-calendar SuperRugby
source ${PIER}break_single_line.sh ${MANWIDTH}
'''
description = 'SuperRugby calendar'
tags = ['khal']

[scripts.path]
alias = 'path'
command = '''
echo $PATH | xsv flatten -d ":" -n
'''
description = 'display PATH'
tags = ['shell']

[scripts.sftp-bianca]
alias = 'sftp-bianca'
command = '''
sftp -q drivas-sens2019016@bianca-sftp.uppmax.uu.se
'''
description = 'sftp to bianca sens2019016'
tags = ['remote']

[scripts.sftp-uppmax]
alias = 'sftp-uppmax'
command = 'sftp drivas@rackham.uppmax.uu.se'
description = 'sftp to Uppmax Rackham'
tags = ['remote']

[scripts.ssh-bianca]
alias = 'ssh-bianca'
command = 'ssh drivas-sens2019016@bianca.uppmax.uu.se'
description = 'ssh to bianca sens2019016'
tags = ['remote']

[scripts.ssh-uppmax]
alias = 'ssh-uppmax'
command = 'ssh drivas@rackham.uppmax.uu.se'
description = 'ssh to Uppmax Rackham'
tags = ['remote']

[scripts.xa]
alias = 'xa'
command = '''
#!/bin/zsh
source ${PIER}break_single_line.sh ${MANWIDTH}
  $(which exa) \
    --long \
    --group-directories-first \
    --classify \
    --links \
    --git \
    --header \
    --sort=accessed \
    --group \
    --all \
    --time accessed
'''
description = 'list files by accessed time'
tags = ['exa']

[scripts.xbs]
alias = 'xbs'
command = '''
#!/bin/zsh
source ${PIER}break_single_line.sh ${MANWIDTH}
  $(which exa) \
    --long  \
    --classify  \
    --links  \
    --git  \
    --header  \
    --sort=newest  \
    --group \
    --all
'''
description = 'list all files without clusters'
tags = ['exa']

[scripts.xc]
alias = 'xc'
command = '''
#!/bin/zsh
source ${PIER}break_single_line.sh ${MANWIDTH}
  $(which exa) \
    --long \
    --group-directories-first \
    --classify \
    --links \
    --git \
    --header \
    --sort=created \
    --group \
    --all \
    --time created
'''
description = 'list files by created time'
tags = ['exa']

[scripts.xd]
alias = 'xd'
command = '''
#!/bin/zsh
source ${PIER}break_single_line.sh ${MANWIDTH}
  $(which exa) \
    --long  \
    --only-dirs  \
    --classify  \
    --links  \
    --git  \
    --header  \
    --group  \
    --all \
    --tree  \
    --level 3  \
    --ignore-glob ".git|.idea"
'''
description = 'list directory tree'
tags = ['exa']

[scripts.xt]
alias = 'xt'
command = '''
#!/bin/zsh
source ${PIER}break_single_line.sh ${MANWIDTH}
  $(which exa) \
    --long  \
    --group-directories-first  \
    --classify  \
    --links  \
    --git  \
    --header  \
    --group  \
    --all \
    --tree  \
    --level 3  \
    --ignore-glob ".git|.idea"
'''
description = 'list file tree'
tags = ['exa']

[default]
