####################################################################################################

# del
del = ["delete_selection_noyank"]                          # shift-shift       # delete foward
backspace = ["delete_char_backward"]                       # shift-shift       # delete backward
A-d = ["delete_word_forward"]                              # shift-alt         # delete next word

# fast reload
F3 = ["normal_mode", ":write", "MODE"]                     # grave             #
A-C-F13 = ["goto_word"]
C-v = ["change_selection_noyank"]

####################################################################################################

# movement
A-b = ["move_prev_word_start", "collapse_selection"]       # alt-left          # word left
A-f = ["move_next_word_end", "collapse_selection"]         # alt-right         # word right

####################################################################################################

# shift
S-left = ["extend_char_left"]                              # shift-left        # select left
S-right = ["extend_char_right"]                            # shift-right       # select right
S-up = ["extend_line_up"]                                  # shift-up          # select up
S-down = ["extend_line_down"]                              # shift-down        # select down

# alt
pageup = ["goto_prev_paragraph", "collapse_selection"]     # alt-up            # prev block
pagedown = ["goto_next_paragraph", "collapse_selection"]   # alt-down          # next block

# alt-shift
A-S-left = ["extend_prev_word_start"]                      # alt-shift-left    # select word left
A-S-right = [ "extend_next_word_end"]                      # alt-shift-right   # select word right
A-S-up = ["select_mode", "goto_prev_paragraph", "MODE"]    # alt-shift-up      # select prev block
A-S-down = ["select_mode", "goto_next_paragraph", "MODE"]  # alt-shift-down    # select next block
# TODO: patch insert -> select

# ctl
C-left = ["jump_view_left"]                                # ctl-left          # prev split
C-right = ["jump_view_right"]                              # ctl-right         # next split
C-up = ["jump_view_up"]                                    # ctl-up            # upper split
C-down = ["jump_view_down"]                                # ctl-down          # lower split

# cmd
C-a = ["goto_line_start"]                                  # cmd-left          # start line
C-e = ["goto_line_end", "move_char_right"]                 # cmd-right         # end line
home = ["goto_file_start"]                                 # cmd-up            # cursor start
end = ["goto_last_line"]                                   # cmd-down          # cursor end

# cmd-shift
A-left = ["select_mode", "goto_line_start", "MODE"]        # cmd-shift-left    # select start line
A-right = ["select_mode", "goto_line_end", "MODE"]         # cmd-shift-right   # select end line
A-up = ["select_mode", "goto_file_start", "MODE"]          # cmd-shift-up      # select start
A-down = ["select_mode", "goto_last_line", "goto_line_end", "MODE"]
                                                           # cmd-shift-down    # select end


####################################################################################################

# alphabet
A-F1 = ["select_regex"]                                    # alt-z             # select
# A-F2 = [""]                                              # alt-b             #
A-F4 = ["yank_joined_to_clipboard"]                        # alt-c             # copy
A-F5 = ["search_selection", "extend_search_next"]          # alt-d             # spawn multi
A-F6 = ["format_selections"]                               # alt-e             # format
A-F7 = ["search"]                                          # alt-f             # search
# A-F8 = [""]                                              # alt-g             #
A-F9 = ["search_prev"]                                     # alt-h             # find prev
# A-F10 = [""]                                             # alt-i             #
C-F1 = ["normal_mode", "copy_selection_on_next_line", "MODE"]
                                                           # alt-j             # spawn multi down
C-F2 = ["normal_mode", "copy_selection_on_prev_line", "MODE"]
                                                           # alt-k             # spawn multi up
C-F4 = ["search_next"]                                     # alt-l             # find next
C-F5 = ["record_macro"]                                    # alt-m             # toggle macro
# C-F6 = [""]                                              # alt-n             #
# C-F7 = [""]                                              # alt-o             #
C-F8 = ["match_brackets"]                                  # alt-p             # jump matching
C-F9 = ["normal_mode", ":quit-all"]                        # alt-q             # close buffer
C-F10 = ["normal_mode", ":reload-all", "MODE"]             # alt-r             # reload
A-C-F1 = ["normal_mode", ":write-quit-all"]                # alt-s             # save & quit
# A-C-F2 = [""]                                            # alt-t             #
A-C-F4 = ["undo"]                                          # alt-u             # undo
A-C-F5 = ["replace_with_yanked"]                           # alt-v             # paste
A-C-F6 = ["normal_mode", ":write"]                         # alt-w             # save
A-C-F7 = ["delete_selection"]                              # alt-x             # cut
A-C-F8 = ["search_selection", "search_next"]               # alt-y             # skip multi
A-C-F9 = ["search_selection", "search_prev"]               # alt-z             # remove multi
A-C-F10 = ["command_mode"]                                 # alt-grave         # command mode


####################################################################################################

# alphabet-shift
S-A-F1 = ["select_all"]                                    # alt-shift-a       # select all
# S-A-F2 = [""]                                            # alt-shift-b       #
S-A-F4 = ["toggle_comments"]                               # alt-shift-c       # toggle comment
S-A-F5 = ["extend_to_line_bounds", "yank", "paste_after", "goto_line_start"]
                                                           # alt-shift-d       # duplicate line
S-A-F6 = ["align_selections"]                              # alt-shift-e       # align
S-A-F7 = ["global_search"]                                 # alt-shift-f       # global search
# S-A-F8 = [""]                                            # alt-shift-g       # change sel
# S-A-F9 = [""]                                            # alt-shift-h       #
S-A-F10 = ["indent"]                                       # alt-shift-i       # indent
S-C-F1 = ["normal_mode", "extend_to_line_bounds", "delete_selection", "paste_after", "MODE"]
                                                           # alt-shift-j       # move down
S-C-F2 = ["normal_mode", "extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before", "MODE"]
                                                           # alt-shift-k       # move up
S-C-F4 = ["goto_line_end", "select_mode", "goto_line_start", "MODE"]
                                                           # alt-shift-l       # select line
S-C-F5 = ["replay_macro"]                                  # alt-shift-m       # play macro
# S-C-F6 = [""]                                            # alt-shift-n       #
S-C-F7 = ["unindent"]                                      # alt-shift-o       # unindent
S-C-F8 = ["select_mode", "match_brackets", "MODE"]         # alt-shift-p       #
# S-C-F9 = [""]                                            # alt-shift-q       #
# S-C-F10 = [""]                                           # alt-shift-r       #
# S-A-C-F1 = [""]                                          # alt-shift-s       #
# S-A-C-F2 = [""]                                          # alt-shift-t       #
S-A-C-F4 = ["redo"]                                        # alt-shift-u       # redo
# S-A-C-F5 = [""]                                          # alt-shift-v       #
# S-A-C-F6 = [""]                                          # alt-shift-w       #
S-A-C-F7 = ["extend_to_line_bounds", "delete_selection"]   # alt-shift-x       # cut line
S-A-C-F8 = ["extend_to_line_bounds", "yank"]               # alt-shift-y       # copy line
# S-A-C-F9 = [""]                                          # alt-shift-z       #
S-A-C-F10 = ["shell_pipe"]                                 # alt-shift-grave   # shell command


####################################################################################################

# ctl
# C-a = ["goto_line_start"]                                  # cmd-left          # start line
# C-b = ["goto_previous_buffer"]                             # ctl-cmd-left      #
# C-c = [""]                                               # DEFAULT           #
# C-d = [""]                                               # DEFAULT           #
# C-e = ["goto_line_end", "move_char_right"]                 # cmd-right         # end line
# C-f = ["goto_next_buffer"]                                 # ctl-cmd-right     #
# C-g = [""]                                               #
# C-h = [""]                                               #
# C-i = [""]                                               # DEFAULT           #
# C-j = [""]                                               #
C-k = ["kill_to_line_end"]                                 # shift-cmd         # delete end line
# C-l = [""]                                               # shift-alt         #
# C-m = [""]                                               # DEFAULT           #
C-n = ["command_palette"]                                  #
# C-o = ["goto_prev_comment"]                                # grave-up          # prev comment
# C-p = ["goto_next_comment"]                                # grave-down        # next comment
# C-q = [""]                                               # DEFAULT           #
C-r = ["changed_file_picker"]                              #             # file picker
C-s = ["buffer_picker"]                                    #             # command palette
C-t = ["file_picker"]                                      #             # buffer picker
C-u = ["kill_to_line_start"]                               # shift-cmd         # delete start line
# C-v = ["normal_mode", ":new"]                              # shift-space       # delete & insert
C-w = ["delete_word_backward"]                             # shift-ctl         # delete word left
C-x = ["scroll_up"]                                        #
C-y = ["scroll_down"]                                      #
# C-z = [""]                                               # DEFAULT           #
# A-c = [""]                                               #


####################################################################################################

# grave
# A-C-F11 = [""]                                           # grave-enter       #
# A-C-F12 = [""]                                           # grave-space       #

# C-pageup = [""]                                          # grave-left        #
# C-pagedown = [""]                                        # grave-right       #
# C-home = [""]                                            # grave-up          #
# C-end = [""]                                             # grave-down        #


####################################################################################################

# grave-shift
A-C-F14 = ["save_selection"]                                 # grave-shift-\     # jump list

A-C-S-F11 = ["jumplist_picker"]                              # grave-shift-enter # record jump
A-C-S-F12 = ["goto_last_modification"]                       # grave-shift-space # last edit

C-S-pageup = ["jump_backward"]                               # grave-shift-left  # prev jump
C-S-pagedown = ["jump_forward"]                              # grave-shift-right # next jump
C-S-home = ["goto_prev_change"]                              # grave-shift-up    # prev change
C-S-end = ["goto_next_change"]                               # grave-shift-down  # next change


####################################################################################################

# joker
F13 = ["goto_prev_class"]                                  # tab--             # next class
F14 = ["goto_next_class"]                                  # tab-=             # prev class

F8 = ["goto_prev_function"]                                # tab-[             # next func
F9 = ["goto_next_function"]                                # tab-]             # prev func
F10 = ["goto_prev_parameter"]                              # tab-;             # next param
F11 = ["goto_next_parameter"]                              # tab-'             # prev param
F12 = ["rename_symbol"]                                    # tab-\             # rename
F15 = ["goto_prev_test"]                                   # tab-,             # prev test
F16 = ["goto_next_test"]                                   # tab-.             # next test
F17 = ["goto_type_definition"]                             # tab-/             # type definition

# F1 = [""]                                                #                   #
F2 = ["symbol_picker"]                                     # tab-enter         # symbol list
F4 = ["goto_implementation"]                               # tab-shift         # implementation
F5 = ["goto_reference"]                                    # tab-alt           # reference
F6 = ["goto_definition"]                                   # tab-cmd           # definition
#                                                          #                   #

# A-C-pagedown = [""]                                      #                   #
# A-C-pageup = [""]                                        #                   #
# A-C-home  = [""]                                         #                   #
# A-C-end = [""]                                           #                   #


####################################################################################################

# ctl-cmd
# S-F13 = []                                               #                   #
# S-F14 = []                                               #                   #

# C-h = [""]                                               #                   #
# A-c = [""]                                               #                   #
# C-r = [""]                                               #                   #
# C-s = [""]                                               #                   #
# C-t = [""]                                               #                   #
# S-F1 = [""]                                              #                   #
# C-j = [""]                                               #                   #
# C-n = [""]                                               #                   #

C-l = [":buffer-close"]                                    # ctl-cmd-bspace    # close tab
C-g = ["normal_mode", ":new"]                              #                   #
S-F4 = ["vsplit"]                                          # ctl-cmd-shift     # vertical split
S-F5 = ["hsplit"]                                          # ctl-cmd-alt       # ho rizontal split
S-F6 = ["wonly"]                                           # ctl-cmd-cmd       # unsplit
S-F7 = ["goto_last_accessed_file"]                         # clt-cmd-space     # last file

C-b = ["goto_previous_buffer"]                             # ctl-cmd-left      # prev tab
C-f = ["goto_next_buffer"]                                 # ctl-cmd-right     # next tab
C-o = ["goto_prev_comment"]                                # ctl-cmd-up        # prev comment
C-p = ["goto_next_comment"]                                # ctl-cmd-down      # next comment

####################################################################################################

# tab
#                                                          #                   #
#                                                          #                   #

S-F8 = ["normal_mode", "till_prev_char", "MODE"]           # grave-left        # prev until
S-F9 = ["normal_mode", "find_till_char", "MODE"]           # grave-right       # next until
# S-F10 = [""]                                             #                   #
# S-F11 = [""]                                             #                   #
# S-F12 = [""]                                             #                   #
# S-F15 = [""]                                             #                   #
# S-F16 = [""]                                             #                   #
# S-F17 = [""]                                             #                   #

#                                                          #                   #
S-F2 = ["diagnostics_picker"]                              # tab-enter         # diag picker
#                                                          #                   #
#                                                          #                   #
#                                                          #                   #
#                                                          #                   #
F7 = ["normal_mode", "repeat_last_motion", "MODE"]         # grave-space       # repeat motion

S-A-pageup = ["goto_prev_diag"]                            # tab-left          # prev diag
S-A-pagedown = ["goto_next_diag"]                          # tab-right         # next diag
S-A-home = ["increment"]                                   # tab-up            # increment
S-A-end = ["decrement"]                                    # tab-down          # decrement


####################################################################################################

# Alt-Enter	Open selected in the background without closing the picker

####################################################################################################
