####################################################################################################
# Alt-Enter	Open selected in the background without closing the picker
####################################################################################################

# del
del = ["delete_selection_noyank"]                          # shift-shift       # delete foward
backspace = ["delete_char_backward"]                       # shift-shift       # delete backward
A-d = ["delete_word_forward"]                              # shift-alt         # delete next word
C-k = ["kill_to_line_end"]                                 # shift-cmd         # delete end line
C-u = ["kill_to_line_start"]                               # shift-cmd         # delete start line
C-w = ["delete_word_backward"]                             # shift-ctl         # delete word left

# F3 = ["normal_mode", ":write", "MODE"]                     # grave             # fast save
# C-v = ["change_selection_noyank"]                          # bs            # change

C-space = ["goto_word"]                                    # ctl-space         # jumper
# A-ret = []                                               # cmd-enter         #

# A-g = [":sh zellij action new-pane --name SHELL --floating --height 100 --width 100 --x 100 --y 0"]
#                                                          # esc               # spawn pane

####################################################################################################

S-A-home  = ["increment"]                                  # hyper-up          # increment
S-A-end = ["decrement"]                                    # hyper-down        # decrement

# C-n = ["goto_prev_comment"]                                # joker-[           # prev comment
# C-p = ["goto_next_comment"]                                # joker-]           # next comment

# joker
# A-F19 = []                                             # joker--           #
# A-F20 = []                                             # joker-=           #
A-F11 = ["goto_prev_comment"]                            # joker-[           # prev comment
A-F12 = ["goto_next_comment"]                            # joker-]           # next comment
# A-F13 = []                                             # joker-;           #
# A-F14 = []                                             # joker-'           #
# A-F15 = []                                             # joker-\           #
A-F18 = ["goto_definition"]                              # joker-,           # definition
A-F19 = ["goto_reference"]                               # joker-.           # reference
A-F20 = ["goto_implementation"]                          # joker-/           # implementation

C-F11 = ["rename_symbol"]                                # joker-bs          # rename symbol
C-F12 = ["symbol_picker"]                                # joker-enter       # symbol list
C-F13 = ["goto_type_definition"]                         # joker-shift       # type definition
# C-F14 = []                                             # joker-alt         #
# C-F15 = []                                             # joker-cmd         #
C-F18 = ["normal_mode", "repeat_last_motion", "MODE"]    # joker-space       # repeat motion

C-pageup = ["normal_mode", "till_prev_char", "MODE"]       # joker-left        # prev until
C-pagedown = ["normal_mode", "find_till_char", "MODE"]     # joker-right       # next until
C-home = ["goto_prev_change"]                              # joker-up          # prev change
C-end = ["goto_next_change"]                               # joker-down        # next change


####################################################################################################

# C-S-F11 = []                                             # joker-shift-bs      #
C-S-F12 = ["jumplist_picker"]                            # joker-shift-enter   # record jump
# C-S-F13 = []                                             # joker-shift-shift   #
# C-S-F14 = []                                             # joker-shift-alt     #
# C-S-F15 = []                                             # joker-shift-cmd     #
C-S-F18 = ["save_selection"]                               # joker-shift-space # jump list

C-S-pageup = ["jump_backward"]                             # joker-shift-left  # prev jump
C-S-pagedown = ["jump_forward"]                            # joker-shift-right # next jump

# F13 = ["goto_prev_test"]                                   # joker-shift-up    # prev test
# F14 = ["goto_next_test"]                                   # joker-shift-down  # next test

F8 = ["goto_prev_class"]                                   # joker-ctl-up      # next class
F9 = ["goto_next_class"]                                   # joker-ctl-down    # prev class

F5 = ["goto_prev_function"]                                # joker-alt-up      # prev func
F6 = ["goto_next_function"]                                # joker-alt-down    # next func

F10 = ["goto_prev_parameter"]                              # joker-cmd-up      # next param
F11 = ["goto_next_parameter"]                              # joker-cmd-down    # prev param


####################################################################################################

F15 = ["undo"]                                      # alt-ctl           # undo
F14 = ["goto_last_modification"]                     # alt-alt           # last edit
F13 = ["redo"]                                    # alt-cmd           # redo

F18 = ["goto_prev_diag"]                              # alt-tab           # prev diag
F17 = ["diagnostics_picker"]                              # alt-joker         # diag picker
F16 = ["goto_next_diag"]                               # alt-shift         # next diag


####################################################################################################

# grave
#                                                          # grave--           #
#                                                          # grave-=           #

#                                                          # grave-[           #
#                                                          # grave-]           #
#                                                          # grave-;           #
#                                                          # grave-'           #
#                                                          # grave-\           #
#                                                          # grave-,           #
#                                                          # grave-.           #
#                                                          # grave-/           #

C-r = ["changed_file_picker"]                              # grave-bs          # delta picker
C-s = ["file_picker"]                                      # grave-enter       # file picker
C-t = ["buffer_picker"]                                    # grave-shift       # buffer picker
#                                                          # grave-alt         #
#                                                          # grave-cmd         #
F7 = ["hover"]                                             # grave-space       # hover

#                                                          # grave-left
#                                                          # grave-right
#                                                          # grave-up
#                                                          # grave-down


####################################################################################################

# grave-shift
#                                                          # grave-shift--     #
#                                                          # grave-shift-=     #

#                                                          # grave-shift-[     #
#                                                          # grave-shift-]     #
#                                                          # grave-shift-;     #
#                                                          # grave-shift-'     #
#                                                          # grave-shift-\     #
#                                                          # grave-shift-,     #
#                                                          # grave-shift-.     #
#                                                          # grave-shift-/     #

#                                                          # grave-shift-bs    #
#                                                          # grave-shift-enter #
#                                                          # grave-shift-shift #
#                                                          # grave-shift-alt   #
#                                                          # grave-shift-cmd   #
#                                                          # grave-shift-space #

#                                                          # grave-shift-left  #
#                                                          # grave-shift-right #
#                                                          # grave-shift-up    #
#                                                          # grave-shift-down  #


####################################################################################################

# ctl-cmd
C-l = [":buffer-close"]                                    # ctl-cmd-bs        # close tab
C-g = ["normal_mode", ":new"]                              # ctl-cmd-enter     # new
C-j = ["vsplit"]                                           # ctl-cmd-shift     # vertical split
S-F5 = ["hsplit"]                                          # ctl-cmd-alt       # horizontal split
S-F6 = ["wonly"]                                           # ctl-cmd-cmd       # unsplit
C-o = ["goto_last_accessed_file"]                          # ctl-cmd-space     # last file

C-b = ["goto_previous_buffer"]                             # ctl-cmd-left      # prev tab
C-f = ["goto_next_buffer"]                                 # ctl-cmd-right     # next tab


####################################################################################################

# scroll
C-x = ["scroll_up"]                                        # alt-cmd-up        #
C-y = ["scroll_down"]                                      # alt-cmd-down      #

# shift
S-left = ["extend_char_left"]                              # shift-left        # select left
S-right = ["extend_char_right"]                            # shift-right       # select right
S-up = ["extend_line_up"]                                  # shift-up          # select up
S-down = ["extend_line_down"]                              # shift-down        # select down

# alt
A-b = ["move_prev_word_start", "collapse_selection"]       # alt-left          # word left
A-f = ["move_next_word_end", "collapse_selection"]         # alt-right         # word right
pageup = ["goto_prev_paragraph", "collapse_selection"]     # alt-up            # prev block
pagedown = ["goto_next_paragraph", "collapse_selection"]   # alt-down          # next block

# alt-shift
A-S-left = ["extend_prev_word_start"]                      # alt-shift-left    # select word left
A-S-right = [ "extend_next_word_end"]                      # alt-shift-right   # select word right
# A-S-up = ["select_mode", "goto_prev_paragraph", "MODE"]    # alt-shift-up      # select prev block
# A-S-down = ["select_mode", "goto_next_paragraph", "MODE"]  # alt-shift-down    # select next block

# ctl
C-left = ["jump_view_left"]                                # ctl-left          # prev split
C-right = ["jump_view_right"]                              # ctl-right         # next split
C-up = ["jump_view_up"]                                    # ctl-up            # upper split
C-down = ["jump_view_down"]                                # ctl-down          # lower split

# cmd
C-a = ["goto_line_start"]                                  # cmd-left          # start line
C-e = ["goto_line_end", "move_char_right"]                 # cmd-right         # end line
home = ["goto_file_start"]                                 # cmd-up            # cursor start
end = ["goto_last_line"]                                   # cmd-down          # cursor end

# cmd-shift
A-left = ["select_mode", "goto_line_start", "MODE"]        # cmd-shift-left    # select start line
A-right = ["select_mode", "goto_line_end", "MODE"]         # cmd-shift-right   # select end line
A-up = ["select_mode", "goto_file_start", "MODE"]          # cmd-shift-up      # select start
A-down = ["select_mode", "goto_last_line", "goto_line_end", "MODE"]
                                                           # cmd-shift-down    # select end


####################################################################################################

# alphabet
# A-F1 = [""]                                              # alt-a             #
# A-F2 = [""]                                              # alt-b             #
A-F4 = ["yank_to_clipboard"]                               # alt-c             # copy
A-F5 = ["search_selection", "extend_search_next"]          # alt-d             # spawn multi
A-F6 = ["align_selections"]                                # alt-e             # align
A-F7 = ["search"]                                          # alt-f             # search
# A-F8 = [""]                                              # alt-g             #
A-F9 = ["search_prev"]                                     # alt-h             # find prev
# A-F10 = [""]                                             # alt-i             #
C-F1 = ["normal_mode", "copy_selection_on_next_line", "MODE"]
                                                           # alt-j             # spawn multi down
C-F2 = ["normal_mode", "copy_selection_on_prev_line", "MODE"]
                                                           # alt-k             # spawn multi up
C-F4 = ["search_next"]                                     # alt-l             # find next
C-F5 = ["record_macro"]                                    # alt-m             # toggle macro
# C-F6 = [""]                                              # alt-n             #
# C-F7 = [""]                                              # alt-o             #
C-F8 = ["match_brackets"]                                  # alt-p             # jump matching
C-F9 = ["normal_mode", ":quit-all"]                        # alt-q             # close buffer
C-F10 = ["normal_mode", ":reload-all", "MODE"]             # alt-r             # reload
A-C-F1 = ["normal_mode", ":write-quit-all"]                # alt-s             # save & quit
A-C-F2 = ["search_selection"]                              # alt-t             # selection
# A-C-F4 = ["undo"]                                          # alt-u             # undo
A-C-F5 = ["paste_clipboard_after"]                         # alt-v             # paste
A-C-F6 = ["normal_mode", ":write"]                         # alt-w             # save
A-C-F7 = ["yank_to_clipboard", "delete_selection_noyank"]  # alt-x             # cut
A-C-F8 = ["search_selection", "search_next"]               # alt-y             # skip multi
A-C-F9 = ["search_selection", "search_prev"]               # alt-z             # remove multi
A-C-F10 = ["command_mode"]                                 # alt-grave         # command mode


####################################################################################################

# alphabet-shift
S-A-F1 = ["select_all"]                                    # alt-shift-a       # select all
# S-A-F2 = [""]                                            # alt-shift-b       #
S-A-F4 = ["toggle_comments"]                               # alt-shift-c       # toggle comment
S-A-F5 = ["extend_to_line_bounds", "yank", "paste_after", "goto_line_start"]
                                                           # alt-shift-d       # duplicate line
S-A-F6 = [":format"]                                       # alt-shift-e       # format
S-A-F7 = ["global_search"]                                 # alt-shift-f       # global search
# S-A-F8 = [""]                                            # alt-shift-g       # change sel
# S-A-F9 = [""]                                            # alt-shift-h       #
S-A-F10 = ["indent"]                                       # alt-shift-i       # indent
S-C-F1 = ["normal_mode", "extend_to_line_bounds", "delete_selection", "paste_after", "MODE"]
                                                           # alt-shift-j       # move down
S-C-F2 = ["normal_mode", "extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before", "MODE"]
                                                           # alt-shift-k       # move up
S-C-F4 = ["goto_line_end", "select_mode", "goto_line_start", "MODE"]
                                                           # alt-shift-l       # select line
# S-C-F5 = ["replay_macro"]                                  # alt-shift-m       # play macro
# S-C-F6 = [""]                                            # alt-shift-n       #
S-C-F7 = ["unindent"]                                      # alt-shift-o       # unindent
S-C-F8 = ["select_mode", "match_brackets", "MODE"]         # alt-shift-p       #
# S-C-F9 = [""]                                            # alt-shift-q       #
# S-C-F10 = [""]                                           # alt-shift-r       #
# S-A-C-F1 = [""]                                          # alt-shift-s       #
S-A-C-F2 = ["select_regex"]                                # alt-shift-t       # select
# S-A-C-F4 = ["redo"]                                        # alt-shift-u       # redo
S-A-C-F5 = ["select_register"]                             # alt-shift-v       # register
# S-A-C-F6 = [""]                                          # alt-shift-w       #
S-A-C-F7 = ["extend_to_line_bounds", "delete_selection_noyank"]
                                                           # alt-shift-x       # cut line
S-A-C-F8 = ["extend_to_line_bounds", "yank_to_clipboard"]  # alt-shift-y       # copy line
S-A-C-F9 = ["extend_to_line_bounds", "yank", "paste_after", "goto_line_start", "toggle_comments", "move_visual_line_up"]
                                                           # alt-shift-z       # duplicate & comment
S-A-C-F10 = ["shell_pipe"]                                 # alt-shift-grave   # shell command


####################################################################################################
