####################################################################################################
# Alt-Enter	Open selected in the background without closing the picker
####################################################################################################

# del
del = ["delete_selection_noyank"]                          # shift-shift       # delete foward
backspace = ["delete_char_backward"]                       # shift-shift       # delete backward
A-d = ["delete_word_forward"]                              # shift-alt         # delete next word
C-k = ["kill_to_line_end"]                                 # shift-cmd         # delete end line
C-u = ["kill_to_line_start"]                               # shift-cmd         # delete start line
C-w = ["delete_word_backward"]                             # shift-ctl         # delete word left

C-space = ["goto_word"]                                    # ctl-space         # jumper


####################################################################################################

# hyper
# S-pageup = []                                            # hyper-left        #
# S-pagedown = []                                          # hyper-right       #
S-home  = ["increment"]                                    # hyper-up          # increment
S-end = ["decrement"]                                      # hyper-down        # decrement


####################################################################################################

# joker
#                                                          # joker--           #
#                                                          # joker-=           #

#                                                          # joker-[           #
#                                                          # joker-]           #
#                                                          # joker-;           #
#                                                          # joker-'           #
#                                                          # joker-\           #
#                                                          # joker-,           #
#                                                          # joker-.           #
#                                                          # joker-/           #

C-r = ["changed_file_picker"]                              # joker-bs          # delta picker
C-s = ["file_picker"]                                      # joker-enter       # file picker
C-t = ["buffer_picker"]                                    # joker-shift       # buffer picker
#                                                          # joker-alt         #
#                                                          # joker-cmd         #
#                                                          # joker-space       #

A-pageup = ["undo"]                                        # joker-left        # undo
A-pagedown = ["redo"]                                      # joker-right       # redo
A-home = ["goto_prev_change"]                              # joker-up          # prev change
A-end = ["goto_next_change"]                               # joker-down        # next change


####################################################################################################

# joker-shift
#                                                          # joker-shift--     #
#                                                          # joker-shift-=     #

#                                                          # joker-shift-[     #
#                                                          # joker-shift-]     #
#                                                          # joker-shift-;     #
#                                                          # joker-shift-'     #
#                                                          # joker-shift-\     #
#                                                          # joker-shift-,     #
#                                                          # joker-shift-.     #
#                                                          # joker-shift-/     #

#                                                          # joker-shift-bs    #
#                                                          # joker-shift-enter #
#                                                          # joker-shift-shift #
#                                                          # joker-shift-alt   #
#                                                          # joker-shift-cmd   #
#                                                          # joker-shift-space #

#                                                          # joker-shift-left  #
#                                                          # joker-shift-right #
#                                                          # joker-shift-up    #
#                                                          # joker-shift-down  #


####################################################################################################

# grave
C-pageup = ["jump_backward"]                               # grave-left        # prev jump
C-pagedown = ["jump_forward"]                              # grave-right       # next jump
C-home = ["goto_prev_comment"]                             # grave-up          # prev comment
C-end = ["goto_next_comment"]                              # grave-down        # next comment

# C-F19 = []                                               # grave--           #
# C-F20 = []                                               # grave-=           #
# A-F11 = []                                               # grave-[           #
# A-F12 = []                                               # grave-]           #
# A-F13 = []                                               # grave-;           #
# A-F14 = []                                               # grave-'           #
# A-F15 = []                                               # grave-\           #
# A-F18 = []                                               # grave-,           #
# A-F19 = []                                               # grave-.           #
# A-F20 = []                                               # grave-/           #

C-F11 = ["rename_symbol"]                                  # grave-bs          # rename symbol
C-F12 = ["symbol_picker"]                                  # grave-enter       # symbol list
C-F13 = ["search"]                                         # grave-shift       # search
C-F16 = ["goto_reference"]                                 # grave-alt         # reference
C-F17 = ["goto_definition"]                                # grave-cmd         # definition
C-F18 = ["goto_last_modification"]                         # grave-space       # last edit


####################################################################################################

# grave-shift
# C-S-pageup = []                                          # grave-shift-left  #
# C-S-pagedown = []                                        # grave-shift-right #
# C-S-home = []                                            # grave-shift-up    #
# C-S-end = []                                             # grave-shift-down  #

# C-S-F19 = []                                             # grave-shift--     #
# C-S-F20 = []                                             # grave-shift-=     #
# A-S-F11 = []                                             # grave-shift-[     #
# A-S-F12 = []                                             # grave-shift-]     #
# A-S-F13 = []                                             # grave-shift-;     #
# A-S-F14 = []                                             # grave-shift-'     #
# A-S-F15 = []                                             # grave-shift-\     #
# A-S-F18 = []                                             # grave-shift-,     #
# A-S-F19 = []                                             # grave-shift-.     #
# A-S-F20 = []                                             # grave-shift-/     #

# C-S-F11 = []                                             # grave-shift-bs    #
C-S-F12 = ["jumplist_picker"]                              # grave-shift-enter # jump list
C-S-F13 = ["global_search"]                                # grave-shift-shift # global search
C-S-F16 = ["goto_implementation"]                          # grave-shift-alt   # implementation
C-S-F17 = ["goto_type_definition"]                         # grave-shift-cmd   # definition
C-S-F18 = ["save_selection"]                               # grave-shift-space # jump save


####################################################################################################

# alt
F15 = ["normal_mode", "till_prev_char", "MODE"]            # alt-ctl           # move backward
F14 = ["normal_mode", "repeat_last_motion", "MODE"]        # alt-alt           # repeat motion
F13 = ["normal_mode", "find_till_char", "MODE"]            # alt-cmd           # move forward

F18 = ["goto_prev_diag"]                                   # alt-tab           # prev diag
F17 = ["diagnostics_picker"]                               # alt-joker         # diag picker
F16 = ["goto_next_diag"]                                   # alt-shift         # next diag


####################################################################################################

# ctl-cmd
C-l = [":buffer-close"]                                    # ctl-cmd-bs        # close tab
C-g = ["normal_mode", ":new"]                              # ctl-cmd-enter     # new
C-v = ["vsplit"]                                           # ctl-cmd-shift     # vertical split
C-h = ["hsplit"]                                           # ctl-cmd-alt       # horizontal split
C-j = ["wonly"]                                            # ctl-cmd-cmd       # unsplit
C-o = ["goto_last_accessed_file"]                          # ctl-cmd-space     # last file

C-b = ["goto_previous_buffer"]                             # ctl-cmd-left      # prev tab
C-f = ["goto_next_buffer"]                                 # ctl-cmd-right     # next tab
# C-n = []                                                 # ctl-cmd-up        #
# C-p = []                                                 # ctl-cmd-down      #


####################################################################################################

# scroll
#                                                          # alt-cmd-left      # zellij
#                                                          # alt-cmd-right     # zellij
C-x = ["scroll_up"]                                        # alt-cmd-up        # scroll up
C-y = ["scroll_down"]                                      # alt-cmd-down      # scroll down

# shift
S-left = ["extend_char_left"]                              # shift-left        # select left
S-right = ["extend_char_right"]                            # shift-right       # select right
S-up = ["extend_line_up"]                                  # shift-up          # select up
S-down = ["extend_line_down"]                              # shift-down        # select down

# alt
A-b = ["move_prev_word_start", "collapse_selection"]       # alt-left          # word left
A-f = ["move_next_word_end", "collapse_selection"]         # alt-right         # word right
pageup = ["goto_prev_paragraph", "collapse_selection"]     # alt-up            # prev block
pagedown = ["goto_next_paragraph", "collapse_selection"]   # alt-down          # next block

# alt-shift
A-S-left = ["extend_prev_word_start"]                      # alt-shift-left    # select word left
A-S-right = ["extend_next_word_end"]                       # alt-shift-right   # select word right
# A-S-up = []                                              # alt-shift-up      # select prev block
# A-S-down = []                                            # alt-shift-down    # select next block

# ctl
C-left = ["jump_view_left"]                                # ctl-left          # prev split
C-right = ["jump_view_right"]                              # ctl-right         # next split
C-up = ["jump_view_up"]                                    # ctl-up            # upper split
C-down = ["jump_view_down"]                                # ctl-down          # lower split

# cmd
C-a = ["goto_line_start"]                                  # cmd-left          # start line
C-e = ["goto_line_end", "move_char_right"]                 # cmd-right         # end line
home = ["goto_file_start"]                                 # cmd-up            # cursor start
end = ["goto_last_line"]                                   # cmd-down          # cursor end

# cmd-shift
A-left = ["select_mode", "goto_line_start", "MODE"]        # cmd-shift-left    # select start line
A-right = ["select_mode", "goto_line_end", "MODE"]         # cmd-shift-right   # select end line
A-up = ["extend_to_file_start"]                            # cmd-shift-up      # select start
A-down = ["extend_to_file_end"]                            # cmd-shift-down    # select end


####################################################################################################

# alphabet
# A-F1 = [""]                                              # alt-a             #
# A-F2 = [""]                                              # alt-b             #
A-F4 = ["yank_to_clipboard"]                               # alt-c             # copy
A-F5 = ["search_selection", "extend_search_next"]          # alt-d             # spawn multi
# A-F6 = [""]                                              # alt-e             #
A-F7 = [":format"]                                         # alt-f             # format
# A-F8 = [""]                                              # alt-g             #
A-F9 = ["search_prev"]                                     # alt-h             # find prev
# A-F10 = [""]                                             # alt-i             #
C-F1 = ["normal_mode", "copy_selection_on_next_line", "MODE"] # alt-j             # spawn multi down
C-F2 = ["normal_mode", "copy_selection_on_prev_line", "MODE"] # alt-k             # spawn multi up
C-F4 = ["search_next"]                                     # alt-l             # find next
C-F5 = ["record_macro"]                                    # alt-m             # toggle macro
# C-F6 = [""]                                              # alt-n             #
# C-F7 = [""]                                              # alt-o             #
# C-F8 = [""]                                              # alt-p             # jump matching
C-F9 = ["normal_mode", ":quit-all"]                        # alt-q             # close buffer
C-F10 = ["normal_mode", ":reload-all", "MODE"]             # alt-r             # reload
A-C-F1 = ["normal_mode", ":write-quit-all"]                # alt-s             # save & quit
# A-C-F2 = [""]                                            # alt-t             #
# A-C-F4 = [""]                                            # alt-u             #
A-C-F5 = ["paste_clipboard_after"]                         # alt-v             # paste
A-C-F6 = ["normal_mode", ":write"]                         # alt-w             # save
A-C-F7 = ["yank_to_clipboard", "delete_selection_noyank"]  # alt-x             # cut
A-C-F8 = ["search_selection", "search_next"]               # alt-y             # skip multi
A-C-F9 = ["search_selection", "search_prev"]               # alt-z             # remove multi
A-C-F10 = ["command_mode"]                                 # alt-grave         # command mode


####################################################################################################

# alphabet-shift
S-A-F1 = ["select_all"]                                    # alt-shift-a       # select all
# S-A-F2 = [""]                                            # alt-shift-b       #
S-A-F4 = ["toggle_comments"]                               # alt-shift-c       # toggle comment
S-A-F5 = ["extend_to_line_bounds", "yank", "paste_after", "goto_line_start"] # alt-shift-d       # duplicate line
# S-A-F6 = [""]                                            # alt-shift-e       # 
# S-A-F7 = [""]                                            # alt-shift-f       #
# S-A-F8 = [""]                                            # alt-shift-g       #
# S-A-F9 = [""]                                            # alt-shift-h       #
S-A-F10 = ["indent"]                                       # alt-shift-i       # indent
S-C-F1 = ["normal_mode", "extend_to_line_bounds", "delete_selection", "paste_after", "MODE"] # alt-shift-j       # move down
S-C-F2 = ["normal_mode", "extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before", "MODE"] # alt-shift-k       # move up
S-C-F4 = ["goto_line_end", "select_mode", "goto_line_start", "MODE"] # alt-shift-l       # select line
S-C-F5 = ["replay_macro"]                                  # alt-shift-m       # play macro
# S-C-F6 = [""]                                            # alt-shift-n       #
S-C-F7 = ["unindent"]                                      # alt-shift-o       # unindent
# S-C-F8 = [""]                                            # alt-shift-p       #
S-C-F9 = [":sh zellij run --name lazygit --close-on-exit --floating --pinned true --height 100 --width 140 --x 0 --y 0 -- lazygit"] # alt-shift-q       # launch lazygit
S-C-F10 = [":sh zellij run --name serpl --close-on-exit --floating --pinned true --height 100 --width 140 --x 0 --y 0 -- serpl"] # alt-shift-r       # launch serpl
S-A-C-F1 = ["extend_to_line_bounds", "yank", "paste_after", "goto_line_start", "toggle_comments", "move_visual_line_up"] # alt-shift-s       # duplicate & comment
# S-A-C-F2 = [""]                                          # alt-shift-t       #
# S-A-C-F4 = [""]                                          # alt-shift-u       #
# S-A-C-F5 = [""]                                          # alt-shift-v       #
S-A-C-F6 = [":sh zellij run --name canvas --close-on-exit --floating --height 100 --width 140 --x 0 --y 0 -- zsh"] # alt-shift-w       # launch window
S-A-C-F7 = ["extend_to_line_bounds", "delete_selection_noyank"] # alt-shift-x       # cut line
S-A-C-F8 = ["extend_to_line_bounds", "yank_to_clipboard"]  # alt-shift-y       # copy line
S-A-C-F9 = [":sh zellij run --name broot --close-on-exit --floating --pinned true --height 100 --width 140 --x 0 --y 0 -- broot --dates --sizes --permissions --hidden --git-ignored --show-git-info --sort-by-type-dirs-first"] # alt-shift-z       # launch broot
S-A-C-F10 = ["shell_pipe"]                                 # alt-shift-grave   # shell command


####################################################################################################
