####################################################################################################

# TODO: update micro bindings
# del
del = ["delete_selection_noyank"]                          # shift-shift
backspace = ["delete_char_backward"]                       # shift-shift
A-d = ["delete_word_forward"]                              # shift-alt         # delete next word

# fast reload
F3 = ["normal_mode", ":write", "MODE"]                     # grave             #

####################################################################################################

# movement
A-b = ["move_prev_word_start", "collapse_selection"]       # alt-left          # word left
A-f = ["move_next_word_end", "collapse_selection"]         # alt-right         # word right

####################################################################################################

# helix pane
C-left = ["jump_view_left"]                                # ctl-left          # prev split
C-right = ["jump_view_right"]                              # ctl-right         # next split
C-up = ["jump_view_up"]                                    # ctl-up            # upper split
C-down = ["jump_view_down"]                                # ctl-down          # lower split

####################################################################################################

# arrow
S-left = ["extend_char_left"]                              # shift-left        # select left
S-right = ["extend_char_right"]                            # shift-right       # select right
S-up = ["extend_line_above"]                               # shift-up          # select up
S-down = ["extend_line_below"]                             # shift-down        # select down

pageup = ["goto_prev_paragraph", "collapse_selection"]     # alt-up            # prev block
pagedown = ["goto_next_paragraph", "collapse_selection"]   # alt-down          # next block

A-S-left = ["extend_prev_word_start"]                      # alt-shift-left    # select word left
A-S-right = [ "extend_next_word_end"]                      # alt-shift-right   # select word right
A-S-up = ["select_mode", "goto_prev_paragraph", "MODE"]    # alt-shift-up      # select prev block
A-S-down = ["select_mode", "goto_next_paragraph", "MODE"]  # alt-shift-down    # select next block

home = ["goto_file_start"]                                 # cmd-up            # cursor start
end = ["goto_last_line"]                                   # cmd-down          # cursor end

A-left = ["select_mode", "goto_line_start", "MODE"]        # cmd-shift-left    # select start line
A-right = ["select_mode", "goto_line_end", "MODE"]         # cmd-shift-right   # select end line
S-home = ["select_mode", "goto_file_start", "MODE"]        # cmd-shift-up      # select start
S-end = ["select_mode", "goto_last_line", "goto_line_end", "MODE"]
                                                           # cmd-shift-down    # select end

A-C-pageup = ["jump_backward"]                             # joker-left        # prev jump
A-C-pagedown = ["jump_forward"]                            # joker-right       # next jump
A-C-home = ["goto_prev_comment"]                           # joker-up          # prev comment
A-C-end = ["goto_next_comment"]                            # joker-down        # next comment

A-C-S-home = ["increment"]                                 # q-up              # increment
A-C-S-end = ["decrement"]                                  # q-down            # decrement

A-home = ["goto_prev_change"]                              # alt-cmd-up        # prev change
A-end = ["goto_next_change"]                               # alt-cmd-down      # next change


####################################################################################################

# alphabet
# TODO: remap
A-F1 = ["goto_word"]                                       # alt-a             # jump
# A-F2 = [""]                                              # alt-b             #
A-F4 = ["yank_joined_to_clipboard"]                        # alt-c             # copy
A-F5 = ["search_selection", "extend_search_next"]          # alt-d             # spawn multi
# A-F6 = [""]                                              # alt-e             #
A-F7 = ["search"]                                          # alt-f             # search
# A-F8 = [""]                                              # alt-g             #
A-F9 = ["search_prev"]                                     # alt-h             # find prev
# A-F10 = [""]                                             # alt-i             #
C-F1 = ["normal_mode", "copy_selection_on_next_line", "MODE"]
                                                           # alt-j             # spawn multi down
C-F2 = ["normal_mode", "copy_selection_on_prev_line", "MODE"]
                                                           # alt-k             # spawn multi up
C-F4 = ["search_next"]                                     # alt-l             # find next
# C-F5 = [""]                                              # alt-m             #
# C-F6 = [""]                                              # alt-n             #
# C-F7 = [""]                                              # alt-o             #
C-F8 = ["match_brackets"]                                  # alt-p             # jump matching
C-F9 = ["normal_mode", ":quit-all"]                        # alt-q             # close buffer
C-F10 = ["record_macro"]                                   # alt-r             # toggle macro
A-C-F1 = ["normal_mode", ":write-buffer-close"]            # alt-s             # save & close buf
# A-C-F2 = [""]                                            # alt-t             #
A-C-F4 = ["undo"]                                          # alt-u             # undo
A-C-F5 = ["replace_with_yanked"]                           # alt-v             # paste
A-C-F6 = ["normal_mode", ":write"]                         # alt-w             # save
A-C-F7 = ["delete_selection"]                              # alt-x             # cut
A-C-F8 = ["search_selection", "search_next"]               # alt-y             # skip multi
A-C-F9 = ["search_selection", "search_prev"]               # alt-z             # remove multi
A-C-F10 = ["command_mode"]                                 # alt-tilde         # command mode


####################################################################################################

# alphabet
S-A-F1 = ["select_all"]                                    # alt-shift-a       # select all
# S-A-F2 = [""]                                            # alt-shift-b       #
S-A-F4 = ["toggle_comments"]                               # alt-shift-c       # toggle comment
S-A-F5 = ["extend_to_line_bounds", "yank", "paste_after", "goto_line_start"]
                                                           # alt-shift-d       # duplicate line
# S-A-F6 = [""]                                            # alt-shift-e       #
S-A-F7 = ["global_search"]                                 # alt-shift-f       # global search
# S-A-F8 = [""]                                            # alt-shift-g       # change sel
# S-A-F9 = [""]                                            # alt-shift-h       #
S-A-F10 = ["indent"]                                       # alt-shift-i       # indent
S-C-F1 = ["normal_mode", "extend_to_line_bounds", "delete_selection", "paste_after", "MODE"]
                                                           # alt-shift-j       # move down
S-C-F2 = ["normal_mode", "extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before", "MODE"]
                                                           # alt-shift-k       # move up
S-C-F4 = ["goto_line_end", "select_mode", "goto_line_start", "MODE"]
                                                           # alt-shift-l       # select line
# S-C-F5 = [""]                                            # alt-shift-m       #
# S-C-F6 = [""]                                            # alt-shift-n       #
S-C-F7 = ["unindent"]                                      # alt-shift-o       # unindent
S-C-F8 = ["select_mode", "match_brackets", "MODE"]         # alt-shift-p       #
# S-C-F9 = [""]                                            # alt-shift-q       #
S-C-F10 = ["replay_macro"]                                 # alt-shift-r       # play macro
S-A-C-F1 = [":write-quit-all"]                             # alt-shift-s       # save & quit all
# S-A-C-F2 = [""]                                          # alt-shift-t       #
S-A-C-F4 = ["redo"]                                        # alt-shift-u       # redo
S-A-C-F5 = ["format_selections"]                           # alt-shift-v       # format
S-A-C-F6 = ["normal_mode", ":reload-all", "MODE"]          # alt-shift-w       # reload
S-A-C-F7 = ["extend_to_line_bounds", "delete_selection"]   # alt-shift-x       # cut line
S-A-C-F8 = ["extend_to_line_bounds", "yank"]               # alt-shift-y       # copy line
S-A-C-F9 = ["select_regex"]                                # alt-shift-z       # select
S-A-C-F10 = ["shell_pipe"]                                 # alt-shift-tilde   # shell command


####################################################################################################

# ctl
C-a = ["goto_line_start"]                                  # cmd-left          # start line
C-b = ["goto_previous_buffer"]                             # ctl-cmd-left      #
# C-c = [""]                                               # DEFAULT           #
# C-d = [""]                                               # DEFAULT           #
C-e = ["goto_line_end", "move_char_right"]                 # cmd-right         # end line
C-f = ["goto_next_buffer"]                                 # ctl-cmd-right     #
# C-g = [""]                                               # bs-caps           #
# C-h = [""]                                               # bs-tab            #
# C-i = [""]                                               # DEFAULT           #
# C-j = [""]                                               # bs-ctl            #
C-k = ["kill_to_line_end"]                                 # shift-cmd         # delete end line
# C-l = [""]                                               # shift-alt         #
# C-m = [""]                                               # DEFAULT           #
# C-n = [""]                                               # bs-fn             #
C-o = ["goto_prev_diag"]                                   # ctl-cmd-up        # prev diag
C-p = ["goto_next_diag"]                                   # ctl-cmd-down      # next diag
# C-q = [""]                                               # DEFAULT           #
C-r = ["file_picker"]                                      # bs-ctl            # file picker
C-s = ["buffer_picker"]                                    # bs-alt            # buffer picker
C-t = ["command_palette"]                                  # bs-cmd            # command palette
C-u = ["kill_to_line_start"]                               # shift-cmd         # delete start line
# C-v = [""]                                               #                   #
C-w = ["delete_word_backward"]                             # shift-ctl         # delete word left
# C-x = [""]                                               #                   #
C-y = ["normal_mode", ":new"]                              # alt-shift-q       # quit all
# C-z = [""]                                               # DEFAULT           #
A-c = ["changed_file_picker"]                              # bs-shift          # git picker


####################################################################################################

# cmd
# F1 = []                                                  #                   #
F2 = ["symbol_picker"]                                     # cmd-enter         # symbol list
F4 = ["goto_implementation"]                               # cmd-shift         # implementation
F5 = ["goto_reference"]                                    # cmd-alt           # reference
F6 = ["goto_definition"]                                   # cmd-cmd           # definition
F7 = ["goto_last_modification"]                            # cmd-space         # last edit

F8 = ["goto_prev_class"]                                   # cmd--             # next class
F9 = ["goto_next_class"]                                   # cmd-=             # prev class
F10 = ["goto_prev_function"]                               # cmd-[             # next func
F11 = ["goto_next_function"]                               # cmd-]             # prev func
F13 = ["goto_prev_parameter"]                              # cmd-;             # next param
F14 = ["goto_next_parameter"]                              # cmd-'             # prev param
F15 = ["goto_prev_test"]                                   # cmd-,             # prev test
F16 = ["goto_next_test"]                                   # cmd-.             # next test
F17 = ["rename_symbol"]                                    # cmd-\             # type definition


# ctl-cmd
S-F1 = [":buffer-close"]                                   # ctl-cmd-bspace    # close tab
S-F2 = ["diagnostics_picker"]                              # ctl-cmd-enter     # symbol list
S-F4 = ["vsplit"]                                          # ctl-cmd-shift     # vertical split
S-F5 = ["hsplit"]                                          # ctl-cmd-alt       # ho rizontal split
S-F6 = ["wonly"]                                           # ctl-cmd-cmd       # unsplit
S-F7 = ["goto_last_accessed_file"]                         # clt-cmd-space     # last file

# S-F8 = []                                                #                   #
# S-F9 = []                                                #                   #
# S-F10 = []                                               #                   #
# S-F11 = []                                               #                   #
# S-F13 = []                                               #                   #
# S-F14 = []                                               #                   #
# S-F15 = []                                               #                   #
# S-F16 = []                                               #                   #
# S-F17 = []                                               #                   #


# joker
# C-F11 = []                                               #                   #
C-F12 = ["jumplist_picker"]                                # joker-enter       # record jump
C-F13 = ["save_selection"]                                 # joker-shift       # jump list
# C-F15 = []                                               #                   #
# C-F16 = []                                               #                   #
C-F17 = ["normal_mode", "repeat_last_motion", "MODE"]      # ctl-space         # repeat motion

# A-F11 = []                                               #                   #
# A-F12 = []                                               #                   #
A-F14 = ["normal_mode", "find_till_char", "MODE"]          # ctl-[             # prev until
A-F13 = ["normal_mode", "till_prev_char", "MODE"]          # ctl-]             # next until
# A-F15 = []                                               #                   #
# A-F16 = []                                               #                   #
# A-F17 = []                                               #                   #
# A-C-F15 = []                                             #                   #
# A-C-F16 = []                                             #                   #
# A-C-F17 = []                                             #                   #


####################################################################################################

# Alt-Enter	Open selected in the background without closing the picker

####################################################################################################
