####################################################################################################

# delete
del = ["delete_selection_noyank"]                          # shift-shift
backspace = ["delete_char_backward"]                       # shift-shift
A-d = ["delete_word_forward"]                              # shift-alt         # delete next word


####################################################################################################

# movement
A-left = ["select_mode", "goto_line_start", "MODE"]        # cmd-shift-left    # select start line
A-right = ["select_mode", "goto_line_end", "MODE"]         # cmd-shift-right   # select end line

# movement
A-b = ["move_prev_word_start", "collapse_selection"]       # alt-left          # word left
A-f = ["move_next_word_end", "collapse_selection"]         # alt-right         # word right

# movement
S-left = ["extend_char_left"]                              # shift-left        # select left
S-right = ["extend_char_right"]                            # shift-right       # select right
S-up = ["extend_line_above"]                               # shift-up          # select up
S-down = ["extend_line_below"]                             # shift-down        # select down

# movement
A-S-left = ["extend_prev_word_start"]                      # alt-shift-left    # select word left
A-S-right = [ "extend_next_word_end"]                      # alt-shift-right   # select word right
A-S-up = ["select_mode", "goto_prev_paragraph", "MODE"]    # alt-shift-up      # select prev block
A-S-down = ["select_mode", "goto_next_paragraph", "MODE"]  # alt-shift-down    # select next block

# helix pane
C-left = ["jump_view_left"]                                # ctrl-left         # prev split
C-right = ["jump_view_right"]                              # ctrl-right        # next split
C-up = ["jump_view_up"]                                    # ctrl-up           # upper split
C-down = ["jump_view_down"]                                # ctrl-down         # lower split


####################################################################################################

# alphabet
# A-F1 = [""]                                              # alt-a             #
A-F2 = ["command_mode"]                                    # alt-b             # command mode
A-F4 = ["yank_joined_to_clipboard"]                        # alt-c             # copy
A-F5 = ["search_selection", "extend_search_next"]          # alt-d             # spawn multi
# A-F6 = [""]                                              # alt-e             #
A-F7 = ["search"]                                          # alt-f             # search
# A-F8 = [""]                                              # alt-g             #
A-F9 = ["search_prev"]                                     # alt-h             # find prev
# A-F10 = [""]                                             # alt-i             #
C-F1 = ["normal_mode", "copy_selection_on_next_line", "MODE"]
                                                           # alt-j             # spawn multi down
C-F2 = ["normal_mode", "copy_selection_on_prev_line", "MODE"]
                                                           # alt-k             # spawn multi up
C-F4 = ["search_next"]                                     # alt-l             # find next
# C-F5 = [""]                                              # alt-m             #
# C-F6 = [""]                                              # alt-n             #
# C-F7 = [""]                                              # alt-o             #
C-F8 = ["match_brackets"]                                  # alt-p             # jump matching
C-F9 = [":buffer-close"]                                   # alt-q             # close buffer
C-F10 = ["record_macro"]                                   # alt-r             # toggle macro
A-C-F1 = [":write-buffer-close"]                           # alt-s             # save & close buf
# A-C-F2 = [""]                                            # alt-t             #
A-C-F4 = ["undo"]                                          # alt-u             # undo
A-C-F5 = ["replace_with_yanked"]                           # alt-v             # paste
A-C-F6 = ["normal_mode", ":write", "MODE"]                 # alt-w             #
A-C-F7 = ["delete_selection"]                              # alt-x             # cut
A-C-F8 = ["search_selection", "search_next"]               # alt-y             # skip multi
A-C-F9 = ["search_selection", "search_prev"]               # alt-z             # remove multi
A-C-F10 = ["command_mode"]                                 # alt-tilde         #


####################################################################################################

# WIP: remap shell & pipe command
# alphabet
S-A-F1 = ["select_all"]                                    # alt-shift-a       # select all
S-A-F2 = ["shell_pipe"]                                    # alt-shift-b       # shell mode
S-A-F4 = ["toggle_comments"]                               # alt-shift-c       # toggle comment
S-A-F5 = ["extend_to_line_bounds", "yank", "paste_after", "goto_line_start"]
                                                           # alt-shift-d       # duplicate line
# S-A-F6 = [""]                                            # alt-shift-e       #
S-A-F7 = ["global_search"]                                 # alt-shift-f       # global search
# S-A-F8 = [""]                                            # alt-shift-g       #
# S-A-F9 = [""]                                            # alt-shift-h       #
S-A-F10 = ["indent"]                                       # alt-shift-i       # indent
S-C-F1 = ["normal_mode", "extend_to_line_bounds", "delete_selection", "paste_after", "MODE"]
                                                           # alt-shift-j       # move down
S-C-F2 = ["normal_mode", "extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before", "MODE"]
                                                           # alt-shift-k       # move up
S-C-F4 = ["goto_line_end", "select_mode", "goto_line_start", "MODE"]
                                                           # alt-shift-l       # select line
# S-C-F5 = [""]                                            # alt-shift-m       #
# S-C-F6 = [""]                                            # alt-shift-n       #
S-C-F7 = ["unindent"]                                      # alt-shift-o       # unindent
# S-C-F8 = [""]                                            # alt-shift-p       #
S-C-F9 = [":quit-all"]                                     # alt-shift-q       # quit all
S-C-F10 = ["replay_macro"]                                 # alt-shift-r       # play macro
S-A-C-F1 = [":write-quit-all"]                             # alt-shift-s       # save & quit all
# S-A-C-F2 = [""]                                          # alt-shift-t       #
S-A-C-F4 = ["redo"]                                        # alt-shift-u       # redo
# S-A-C-F5 = [""]                                          # alt-shift-v       #
S-A-C-F6 = ["normal_mode", ":reload-all", "MODE"]          # alt-shift-w       # reload
S-A-C-F7 = ["extend_to_line_bounds", "delete_selection"]   # alt-shift-x       # cut line
S-A-C-F8 = ["extend_to_line_bounds", "yank"]               # alt-shift-y       # copy line
# S-A-C-F9 = [""]                                          # alt-shift-z       #
# S-A-C-F10 = [""]                                         # alt-shift-tilde   #


####################################################################################################

# control
C-a = ["goto_line_start"]                                  # cmd-left          # start line
# C-b = [""]                                               # shift-space       #
# C-c = [""]                                               #                   #
# C-d = [""]                                               #                   #
C-e = ["goto_line_end", "move_char_right"]                 # cmd-right         # end line
# C-f = [""]                                               # shift-enter       #
# C-g = [""]                                               # del-caps          #
# C-h = [""]                                               # del-tab           #
# C-i = [""]                                               #                   #
# C-j = [""]                                               # del-cmd           #
C-k = ["kill_to_line_end"]                                 # shift-cmd         # delete end line
# C-l = [""]                                               # shift-alt         #
# C-m = [""]                                               #                   #
# C-n = [""]                                               # del-alt           #
# C-o = [""]                                               #                   #
# C-p = [""]                                               #                   #
# C-q = [""]                                               #                   #
C-r = ["file_picker"]                                      # del-ctrl          # file picker
C-s = ["buffer_picker"]                                    # del-alt           # buffer picker
C-t = ["command_palette"]                                  # del-cmd           # command palette
C-u = ["kill_to_line_start"]                               # shift-cmd         # delete start line
# C-v = [""]                                               #                   #
C-w = ["delete_word_backward"]                             # shift-ctrl        # delete word left
# C-x = [""]                                               #                   #
# C-y = [""]                                               # del-space         #
# C-z = [""]                                               #                   #


####################################################################################################

# TODO: update docs
# control - command
# A-F11 = [""]                                             # ctrl-cmd-a        #
# A-F12 = [""]                                             # ctrl-cmd-b        #
# A-F13 = [""]                                             # ctrl-cmd-c        #
# A-F14 = [""]                                             # ctrl-cmd-d        #
# A-F18 = [""]                                             # ctrl-cmd-e        #
# A-F19 = [""]                                             # ctrl-cmd-f        #
# A-F20 = [""]                                             # ctrl-cmd-g        #
# C-F11 = [""]                                             # ctrl-cmd-h        #
# C-F12 = [""]                                             # ctrl-cmd-i        #
# C-F17 = [""]                                             # ctrl-cmd-j        #
# C-F18 = [""]                                             # ctrl-cmd-k        #
# C-F19 = [""]                                             # ctrl-cmd-l        #
# C-F20 = [""]                                             # ctrl-cmd-m        #
# A-C-F11 = [""]                                             # ctrl-cmd-n        #
# A-C-F12 = [""]                                             # ctrl-cmd-o        #
# A-C-F13 = [""]                                             # ctrl-cmd-p        #
# A-C-F14 = [""]                                             # ctrl-cmd-q        #
# A-C-F18 = [""]                                             # ctrl-cmd-r        #
# A-C-F19 = [""]                                           # ctrl-cmd-s        #
# A-C-F20 = [""]                                           # ctrl-cmd-t        #
# S-A-F11 = [""]                                           # ctrl-cmd-u        #
# S-A-F12 = [""]                                           # ctrl-cmd-v        #
# S-A-F13 = [""]                                           # ctrl-cmd-w        #
# S-A-F18 = [""]                                           # ctrl-cmd-x        #
# S-A-F19 = [""]                                           # ctrl-cmd-y        #
# S-A-F20 = [""]                                           # ctrl-cmd-z        #
# F12 = [""]                                           # ctrl-cmd-tilde    #


####################################################################################################

F1 = ["goto_last_accessed_file"]                           # ctrl-cmd-space    # last tab
# F2 = [""]                                                # alt               # go back
F4 = ["goto_prev_paragraph", "collapse_selection"]         # alt-up            # prev block
F5 = ["goto_next_paragraph", "collapse_selection"]         # alt-down          # next block
F6 = ["goto_file_start"]                                   # cmd-up            # cursor start
F7 = ["goto_last_line"]                                    # cmd-down          # cursor end
F8 = ["goto_previous_buffer"]                              # ctrl-cmd-left     # prev tab
F9 = ["goto_next_buffer"]                                  # ctrl-cmd-right    # next tab
F10 = ["goto_prev_diag"]                                        # ctrl-cmd-up       # increment
F11 = ["goto_next_diag"]                                        # ctrl-cmd-down     # decrement
# F12 = [""]                                               #         #
# F13 = [""]                                               #         #
# F14 = [""]                                               #         #
S-C-F11 = ["normal_mode", "till_prev_char", "MODE"]            # ctrl-cmd-,        # prev until
S-C-F12 = ["normal_mode", "find_till_char", "MODE"]            # ctrl-cmd-.        # next until
# S-A-C-F12 = ["normal_mode", "repeat_last_motion", "MODE"]        # ctrl-cmd-/        # repeat motion
# F18 = [""]                                               #    #
# F19 = [""]                                               #    #
# F20 = [""]                                               #    #


####################################################################################################

# S-F1 = [""]                                              # ctrl-cmd-bspace   #
S-F2 = ["workspace_diagnostics_picker"]                                              # ctrl-cmd-enter    #
# S-F2 = ["normal_mode", "repeat_last_motion", "MODE"]                                              # ctrl-cmd-enter    #
S-F4 = ["vsplit"]                                          # ctrl-cmd-shift    # vertical split
S-F5 = ["hsplit"]                                          # ctrl-cmd-alt      # horizontal split
S-F6 = ["wonly"]                                           # ctrl-cmd-cmd      # unsplit
S-F7 = ["goto_prev_change"]                                # alt-cmd-up        # prev change
S-F8 = ["goto_next_change"]                                # alt-cmd-down      # next change
S-F9 = ["select_mode", "goto_file_start", "MODE"]          # cmd-shift-up      # select start
S-F10 = ["select_mode", "goto_last_line", "goto_line_end", "MODE"]
                                                           # cmd-shift-down   # select end
S-F11 = ["increment"]                                             # ctrl-cmd--       #
S-F12 = ["decrement"]                                             # ctrl-cmd-=       #
# S-F13 = ["normal_mode", "till_prev_char", "MODE"]                                             # ctrl-cmd-[       #
# S-F14 = ["normal_mode", "find_till_char", "MODE"]                                             # ctrl-cmd-]       #
# S-F15 = [""]                                             # ctrl-cmd-;       #
# S-F16 = [""]                                             # ctrl-cmd-'       #
# S-F17 = [""]                                             # ctrl-cmd-\       #
# S-F18 = [""]                                             #    #
# S-F19 = [""]                                             #    #
# S-F20 = [""]                                             #    #


####################################################################################################

# movement
# A-C-F15 = ["goto_reference"]                               # ctrl-cmd-[       #
# C-F12 = ["goto_implementation"]                          # ctrl-cmd-]       #
# A-F14 = ["goto_definition"]                              # ctrl-cmd-'       #
# S-A-F11 = ["goto_type_definition"]                         # ctrl-cmd-\       #

# diagnostics
# S-C-F11 = ["goto_prev_diag"]                               # ctrl-cmd-7       # prev diag
# S-C-F12 = ["goto_next_diag"]                               # ctrl-cmd-8       # next diag
# S-A-C-F12 = ["workspace_diagnostics_picker"]                 # ctrl-cmd-9       # diag list

# symbols
# A-C-F17 = ["goto_prev_parameter"]                          # ctrl-cmd-4       # next param
# S-A-F16 = ["goto_next_parameter"]                          # ctrl-cmd-1       # prev param
# A-F16 = ["goto_prev_function"]                           # ctrl-cmd-5       # next func
# A-F17 = ["goto_next_function"]                           # ctrl-cmd-2       # prev func
# A-F13 = ["goto_prev_class"]                              # ctrl-cmd-6       # next class
# S-A-F12 = ["goto_next_class"]                              # ctrl-cmd-3       # prev class
# F12 = ["workspace_symbol_picker"]                      # ctrl-cmd-0       # symbol list

# comments
S-C-F13 = ["goto_prev_comment"]                          # ctrl-cmd-=       # prev comment
S-C-F14 = ["goto_next_comment"]                          # ctrl-cmd-+       # next comment

# jump
S-C-F15 = ["jump_backward"]                              # ctrl-cmd-lock    # prev jump
S-C-F16 = ["jump_forward"]                               # ctrl-cmd-/       # next jump
S-C-F17 = ["save_selection"]                            # ctrl-cmd-*       # jump list
S-A-C-F12 = ["jumplist_picker"]                             # ctrl-cmd--       # record jump
S-A-C-F17 = ["goto_last_modification"]                       # ctrl-cmd-;       #
S-A-C-F13 = ["normal_mode", "repeat_last_motion", "MODE"]                       # ctrl-cmd-;       #


####################################################################################################
