####################################################################################################

[editor]
scrolloff = 7
mouse = true
rulers = [100]
bufferline = "always"
shell = ["sh", "-c"]

completion-replace = false
cursorline = true
cursorcolumn = true

auto-completion = false
auto-info = true
auto-format = false

color-modes = true

end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.lsp]
display-inlay-hints = true

[editor.smart-tab]
enable = false

####################################################################################################

[editor.gutters]
layout = ["diff", "diagnostics", "line-numbers", "spacer"]

####################################################################################################

# cursor shape
[editor.cursor-shape]
normal = "bar"
insert = "underline"
select = "block"

####################################################################################################

[editor.statusline]
left = ["mode", "spinner", "diagnostics"]
center = ["file-modification-indicator", "file-name", "read-only-indicator", "version-control"]
right = [
	"selections",
	"position",
	"primary-selection-length",
	"file-encoding",
	"file-type",
]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"


####################################################################################################

# file picker
[editor.file-picker]
hidden = false

####################################################################################################

[editor.indent-guides]
render = true
character = "╎"
skip-levels = 1

####################################################################################################

# TODO: update invisibles
[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
tabpad = "·"
# newline = ""

####################################################################################################
