####################################################################################################

# insert mode
[keys.insert]

# escape selections
esc = ["normal_mode"]

# completion
A-ret = ["completion"]                                        # alt-space       # completion


####################################################################################################

# alt-shift
A-S-up = ["select_mode", "goto_prev_paragraph", "insert_mode"]  # alt-shift-up      # select prev block
A-S-down = ["select_mode", "goto_next_paragraph", "append_mode"]# alt-shift-down    # select next block

####################################################################################################
