####################################################################################################

# insert mode
[keys.insert]

# escape selections
esc = ["normal_mode"]

####################################################################################################
