####################################################################################################

# [keys.insert.j]
# j = "normal_mode"


[keys.normal."space"]
r = ":config-reload"
ret = "command_palette"

a = "no_op"
b = "no_op"
c = "no_op"
d = "no_op"
e = "no_op"
f = "no_op"
g = "no_op"
h = "no_op"
j = "no_op"
k = "no_op"
p = "no_op"
# r = "no_op"
s = "no_op"
w = "no_op"
y = "no_op"

C = "no_op"
D = "no_op"
E = "no_op"
F = "no_op"
G = "no_op"
P = "no_op"
R = "no_op"
S = "no_op"
Y = "no_op"

A-c = "no_op"

"'" = "no_op"
"/" = "no_op"
"?" = "no_op"


[keys.normal.g]
a = "no_op"
b = "no_op"
c = "no_op"
d = "no_op"
e = "no_op"
f = "no_op"
g = "no_op"
h = "no_op"
i = "no_op"
j = "no_op"
k = "no_op"
l = "no_op"
m = "no_op"
n = "no_op"
p = "no_op"
r = "no_op"
s = "no_op"
t = "no_op"
w = "no_op"
y = "no_op"
D = "no_op"

"." = "no_op"
"|" = "no_op"


####################################################################################################

# diagnostics mini mode
[keys.normal."\\"]
up =  "goto_prev_diag"
down =  "goto_next_diag"
ret =  "workspace_diagnostics_picker"
"\\" =  "diagnostics_picker"

####################################################################################################

# language server protocol mini mode
[keys.normal.z]
z = "symbol_picker"
n = "rename_symbol"
r = "goto_reference"
d = "goto_definition"
i = "goto_implementation"
t = "goto_type_definition"
ret = "code_action"

b = "no_op"
c = "no_op"
j = "no_op"
k = "no_op"
m = "no_op"
# n = "no_op"
N = "no_op"
p = "no_op"
# t = "no_op"
# z = "no_op"
space = "no_op"

up = "no_op"
down = "no_op"
backspace = "no_op"
pageup = "no_op"
pagedown = "no_op"

C-b = "no_op"
C-d = "no_op"
C-f = "no_op"
C-u = "no_op"

"/" = "no_op"
"?" = "no_op"


[keys.normal.Z]
ret = "workspace_symbol_picker"
d = ["vsplit", "goto_definition"]
t = ["vsplit", "goto_type_definition"]

b = "no_op"
c = "no_op"
j = "no_op"
k = "no_op"
m = "no_op"
n = "no_op"
N = "no_op"
p = "no_op"
# t = "no_op"
z = "no_op"

space = "no_op"
up = "no_op"
down = "no_op"
backspace = "no_op"
pageup = "no_op"
pagedown = "no_op"

C-b = "no_op"
C-d = "no_op"
C-f = "no_op"
C-u = "no_op"

"/" = "no_op"
"?" = "no_op"

####################################################################################################
