####################################################################################################

[keys.insert.j]
j = "normal_mode"

[keys.normal."space"]
# TODO: possible to overwrite mini-modes now
f = "no_op"
r = ":config-reload"
q = "switch_case"
left = "goto_previous_buffer"
right = "goto_next_buffer"
space = "goto_last_accessed_file"

# TODO: config diagnostics & lsp
# TODO: from saiyajin => go to change due to micro config
# # create a new minor mode bound to `+`
# [keys.normal.","]
# "-" = "swap_view_left"
# "=" = "swap_view_right"
# ";" = "goto_file"
# "'" = "wclose"
# "\\" = "wonly"
# "/" = "rotate_view"

# [keys.normal."/"]
# "[" = "rsearch"
# "]" = "search"
# ";" = "search_prev"
# "'" = "search_next"
# "\\" = "search_selection"
# "|" = "search_selection_detect_word_boundaries"

# [keys.normal."\\"]
# "[" = "shell_pipe"
# "]" = "shell_pipe_to"
# ";" = "shell_insert_output"
# "'" = "shell_append_output"
# "\\" = "shell_keep_pipe"

# [keys.normal."+"]
# m = ":run-shell-command make"
# c = ":run-shell-command cargo build"
# t = ":run-shell-command cargo test"

####################################################################################################
