####################################################################################################

# normal mode
[keys.normal]

# escape selections
esc = ["collapse_selection", "keep_primary_selection"]

# hover
C-space = ["hover"]

# return
ret = ["insert_mode"]

####################################################################################################
