####################################################################################################

# normal mode
[keys.normal]

# escape selections
esc = ["collapse_selection", "keep_primary_selection"]

# return
ret = ["insert_mode"]

####################################################################################################
