####################################################################################################

# select mode
[keys.select]

# escape selections
esc = ["normal_mode"]

# return
ret = ["insert_mode"]

# hover
A-ret = ["hover"]                                          # cmd-enter         # hover


####################################################################################################

# alt-shift
A-S-up = ["select_mode", "goto_prev_paragraph", "select_mode"]  # alt-shift-up      # select prev block
A-S-down = ["select_mode", "goto_next_paragraph", "select_mode"]# alt-shift-down    # select next block

####################################################################################################
