####################################################################################################

# select mode
[keys.select]

# escape selections
esc = ["normal_mode"]

# return
ret = ["insert_mode"]

####################################################################################################
