####################################################################################################
# theme
####################################################################################################

# theme = "adwaita-dark"
theme = "base16_custom"
# theme = "base16_transparent"
# theme = "dark_plus"
# theme = "fleet_dark"
# theme = "github_dark"
# theme = "molokai"
# theme = "osaka"
# theme = "solarized-osaka"
# theme = "snazzy"

####################################################################################################
