####################################################################################################

[default]

####################################################################################################

[scripts.forge]
command = 'source ${PIER}/forge.sh'
description = 'observe & build alacritty, helix & karabiner'
tags = ['build']

####################################################################################################

[scripts.dir-count]
command = 'fd . --type=d --max-depth=1 | /usr/bin/wc -l'
description = 'count directories in present address'
tags = ['shell']

[scripts.file-count]
command = 'fd . --type=f --max-depth=1 | /usr/bin/wc -l'
description = 'count files in present address'
tags = ['shell']

####################################################################################################

[scripts.finder-hidden-off]
command = 'defaults write com.apple.Finder AppleShowAllFiles false && killall Finder'
description = 'turn finder hidden files on'
tags = ['osx']

[scripts.finder-hidden-on]
command = 'defaults write com.apple.Finder AppleShowAllFiles true && killall Finder'
description = 'turn finder hidden files off'
tags = ['osx']

####################################################################################################

[scripts.fpath]
command = '''
# echo $FPATH | xsv flatten -d ":" -n
source "${IN_SILICO}/breakDL.sh"  $COLUMNS
echo $FPATH | xsv flatten -d ":" -n | awk '{print $2}'
source "${IN_SILICO}/breakDL.sh"  $COLUMNS
'''
description = 'display fpath'
tags = ['env']

[scripts.gopath]
command = '''
# echo $GOPATH | xsv flatten -d ":" -n | awk '{print $2}'
source "${IN_SILICO}/config.sh"
source "${IN_SILICO}/breakDL.sh" $COLUMNS
echo $GOPATH | xsv flatten -d ":" -n | awk '{print $2}'
source "${IN_SILICO}/breakDL.sh" $COLUMNS
'''
description = 'display GOPATH'
tags = ['env']

[scripts.path]
command = '''
# echo $PATH | xsv flatten -d ":" -n | awk '{print $2}'
source "${IN_SILICO}/config.sh"
source "${IN_SILICO}/breakDL.sh" $COLUMNS
echo $PATH | xsv flatten -d ":" -n | awk '{print $2}'
source "${IN_SILICO}/breakDL.sh" $COLUMNS
'''
description = 'display PATH'
tags = ['env']

####################################################################################################

[scripts.git]
command = '''
# git status & git stash & git log
source "${IN_SILICO}/config.sh"

source "${IN_SILICO}/breakCross.sh" $COLUMNS

git status --short
source "${IN_SILICO}/breakSL.sh" $COLUMNS

git stash list
source "${IN_SILICO}/breakSL.sh" $COLUMNS

git log --graph --topo-order --abbrev-commit --date=relative --decorate --all --boundary --pretty=format:'%Cgreen%ad %Cred%h%Creset -%C(yellow)%d%Creset %s %C(dim white)%cn%Creset' -10
source "${IN_SILICO}/breakCross.sh" $COLUMNS
'''
description = 'all-round git status'
tags = ['git']

####################################################################################################

[scripts.godoc]
command = 'godoc -http=localhost:6060; open http://localhost:6060 -a Opera'
description = 'open port for godoc'
tags = ['go']

####################################################################################################

[scripts.julia]
command = 'micro /Users/drivas/Factorem/Awesome-lists/awesome-julia/README.md'
description = 'edit julia awesome list'
tags = ['julia']

####################################################################################################

[scripts.update]
command = 'source ${PIER}/update.sh'
description = 'update homebrew, rustc compiler, & cargo & go binaries'
tags = ['update']

####################################################################################################
