####################################################################################################

# default flags
default_flags = ""


####################################################################################################

# # icons
# icon_theme = "vscode"


####################################################################################################

# config
[[verbs]]
invocation = "quit"
key = "shift-alt-q"
internal = "quit"
description = "quit broot"

[[verbs]]
invocation = "back"
key = "alt-q"
internal = "back"
description = "revert to the previous state"

[[verbs]]
invocation = "refresh"
key = "shift-alt-r"
internal = "refresh"
description = "refresh tree"

# file
[[verbs]]
invocation = "edit"
key = "alt-e"
shortcut = "e"
execution = "subl {file}"
leave_broot = false
description = "open file with `subl` editor"

[[verbs]]
invocation = "micro"
key = "alt-m"
shortcut = "m"
execution = "micro {file}"
leave_broot = false
description = "open file with `micro` editor"

[[verbs]]
invocation = "amp"
key = "alt-a"
shortcut = "a"
execution = "amp {file}"
leave_broot = false
description = "open file with `amp` editor"

[[verbs]]
invocation = "create {subpath}"
shortcut = "c"
execution = "touch {directory}/{subpath}"
leave_broot = false
description = "create file"

# search
[[verbs]]
invocation = "total_search"
key = "alt-r"
internal = "total_search"
description = "search again but on all children"

[[verbs]]
invocation = "next_match"
key = "alt-n"
internal = "next_match"
description = "go to next match"

[[verbs]]
invocation = "previous_match"
key = "shift-alt-n"
internal = "previous_match"
description = "go to previous match"

# view
[[verbs]]
invocation = "toggle_files"
key = "shift-alt-f"
internal = ":toggle_files"
description = "toggle files"

[[verbs]]
invocation = "toggle_hidden"
key = "shift-alt-d"
shortcut = "d"
internal = "toggle_hidden"
description = "toggle hidden"

# pager
[[verbs]]
invocation = "bat"
key = "shift-alt-b"
shortcut = "bat"
external = "bat --paging always {file}"
leave_broot = false
description = "open file with `bat`"

[[verbs]]
invocation = "mdcat"
key = "shift-alt-m"
shortcut = "mdcat"
external = "mdcat --paginate {file}"
leave_broot = false
description = "open file with `mdcat`"

[[verbs]]
invocation = "jless"
key = "shift-alt-j"
shortcut = "jless"
external = "jless {file}"
leave_broot = false
description = "open file with `jless`"

[[verbs]]
invocation = "print_to_copy"
key = "alt-c"
shortcut = "pc"
external = "bat --paging always --plain {file}"
leave_broot = false
description = "open file with `bat` to copy"

[[verbs]]
invocation = "hck"
key = "shift-alt-k"
shortcut = "hck"
external = "hck {file}"
leave_broot = true
description = "open file with `hck`"

[[verbs]]
invocation = "xsv"
key = "shift-alt-x"
shortcut = "xsv"
external = "xsv table {file}"
leave_broot = true
description = "open file with `xsv`"

# print
[[verbs]]
invocation = "print_tree"
key = "shift-alt-v"
shortcut = "pt"
internal = "print_tree"
description = "print tree and leaves broot"

# git
[[verbs]]
invocation = "toggle_git_ignore"
shortcut = "gi"
internal = "toggle_git_ignore"
description = "toggle git ignore"

# stage
[[verbs]]
invocation = "toggle_stage"
key = "alt-s"
shortcut = "ts"
internal = "toggle_stage"
description = "toggle stage"

[[verbs]]
invocation = "toggle_staging_area"
key = "shift-alt-s"
shortcut = "tsa"
internal = "toggle_staging_area"
description = "toggle staging area"

[[verbs]]
invocation = "clear_stage"
key = "shift-alt-l"
shortcut = "cls"
internal = "clear_stage"
description = "clear stage area"

# move
[[verbs]]
invocation = "select_first"
key = "alt-g"
internal = "select_first"
description = "go to top of the list"

[[verbs]]
invocation = "select_last"
key = "shift-alt-g"
internal = "select_last"
description = "go to bottom of the list"

[[verbs]]
invocation = "page_up"
key = "alt-Up"
internal = "page_up"
description = "go to page up"

[[verbs]]
invocation = "page_down"
key = "alt-Down"
internal = "page_down"
description = "go to page down"

# panel
[[verbs]]
invocation = "toggle_preview"
key = "tab"
internal = "toggle_preview"
description = "open / close preview panel"

[[verbs]]
invocation = "open_preview"
key = "right"
apply_to = "file"
internal = "open_preview {file}"
leave_broot = false
description = "display file on panel"

[[verbs]]
invocation = "close_preview"
key = "left"
apply_to = "file"
internal = "close_preview {file}"
leave_broot = false
description = "close display"

[[verbs]]
invocation = "panel_left"
key = "alt-b"
internal = "panel_left"
description = "select left panel"

[[verbs]]
invocation = "panel_right"
key = "alt-f"
internal = "panel_right"
description = "select right panel"


####################################################################################################

# theme
[skin]
# default = "rgb(131, 148, 150) rgb(0, 43, 54) / rgb(131, 148, 150) rgb(7, 54, 66)"     # base0 base03 / base01 base02
default = "gray(23) none / gray(20) none"                                               # transparent background
tree = "rgb(88, 110, 117) none"                                                         # base01 default
file = "none none"                                                                      # default default
directory = "rgb(38, 139, 210) none bold"                                               # blue default bold
exe = "rgb(211, 1, 2) none"                                                             # red default
link = "rgb(211, 54, 130) none"                                                         # magenta default
pruning = "rgb(88, 110, 117) none italic"                                               # base01 default italic
perm__ = "rgb(88, 110, 117) none"                                                       # base01 default
perm_r = "none none"                                                                    # default default
perm_w = "none none"                                                                    # default default
perm_x = "none none"                                                                    # default default
owner = "rgb(88, 110, 117) none"                                                        # base01 default
group = "rgb(88, 110, 117) none"                                                        # base01 default
sparse = "none none"                                                                    # default default
git_branch = "rgb(147, 161, 161) none"                                                  # base1 default
git_insertions = "rgb(133, 153, 0) none"                                                # green default
git_deletions = "rgb(211, 1, 2) none"                                                   # red default
git_status_current = "none none"                                                        # default default
git_status_modified = "rgb(181, 137, 0) none"                                           # yellow default
git_status_new = "rgb(133, 153, 0) none"                                                # green default
git_status_ignored = "rgb(88, 110, 117) none"                                           # base01 default
git_status_conflicted = "rgb(211, 1, 2) none"                                           # red default
git_status_other = "rgb(211, 1, 2) none"                                                # red default
selected_line = "none rgb(7, 54, 66)"                                                   # default base02
char_match = "rgb(133, 153, 0) none underlined"                                         # green default underlined
file_error = "rgb(203, 75, 22) none italic"                                             # orange default italic
flag_label = "none none"                                                                # default default
flag_value = "rgb(181, 137, 0) none bold"                                               # yellow default bold
input = "none none"                                                                     # default default
status_error = "rgb(203, 75, 22) rgb(7, 54, 66)"                                        # orange base02
status_job = "rgb(108, 113, 196) rgb(7, 54, 66) bold"                                   # violet base02 bold
status_normal = "none rgb(7, 54, 66)"                                                   # default base02
status_italic = "rgb(181, 137, 0) rgb(7, 54, 66)"                                       # yellow base02
status_bold = "rgb(147, 161, 161) rgb(7, 54, 66) bold"                                  # base1 base02 bold
status_code = "rgb(108, 113, 196) rgb(7, 54, 66)"                                       # violet base02
status_ellipsis = "none rgb(7, 54, 66)"                                                 # default base02
scrollbar_track = "rgb(7, 54, 66) none"                                                 # base02 default
scrollbar_thumb = "none none"                                                           # default default
help_paragraph = "none none"                                                            # default default
help_bold = "rgb(147, 161, 161) none bold"                                              # base1 default bold
help_italic = "rgb(147, 161, 161) none italic"                                          # base1 default italic
help_code = "rgb(147, 161, 161) rgb(7, 54, 66)"                                         # base1 base02
help_headers = "rgb(181, 137, 0) none"                                                  # yellow default
help_table_border = "none none"                                                         # default default
preview_title = "gray(20) rgb(0, 43, 54)"
staging_area_title = "gray(22) rgb(0, 43, 54)"

####################################################################################################
