####################################################################################################

# default flags
default_flags = ""


####################################################################################################

# config
[[verbs]]
invocation = "open_leave"
key = "ctrl-s"                          # mapped -> `alt-enter`
cmd = ":cd"
description = "go into directory -> `alt-enter`"

[[verbs]]
invocation = "root_up"
key = "ctrl-r"                          # mapped -> `ctrl-enter`
internal = "root_up"
description = "move tree root up -> `ctrl-enter`"

[[verbs]]
key = "ctrl-t"                          # mapped -> `cmd-enter`
external = "command open {file}"
leave_broot = false
description = "open according to OS -> `cmd-enter`"

[[verbs]]
invocation = "quit"
key = "alt-q"
internal = "quit"
description = "quit broot"

[[verbs]]
invocation = "refresh"
key = "alt-r"
internal = "refresh"
description = "refresh tree"

# file
[[verbs]]
invocation = "micro"
key = "shift-f9"                        # mapped -> `alt-ctrl-enter`
execution = "micro {file}"
leave_broot = false
description = "open file with `micro` editor -> `ctrl-cmd-left`"

[[verbs]]
invocation = "helix"
key = "shift-f10"                       # mapped -> `alt-cmd-enter`
execution = "hx {file}"
leave_broot = false
description = "open file with `helix` editor -> `ctrl-cmd-right`"

# search
[[verbs]]
invocation = "total_search"
key = "alt-down"                        # mapped -> `alt-f`
internal = "total_search"
description = "search again but on all children -> `alt-f`"

[[verbs]]
invocation = "next_match"
key = "alt-l"
internal = "next_match"
description = "go to next match"

[[verbs]]
invocation = "previous_match"
key = "alt-h"
internal = "previous_match"
description = "go to previous match"

# view
[[verbs]]
invocation = "toggle_files"
key = "alt-shift-f"
internal = ":toggle_files"
description = "toggle files"

[[verbs]]
invocation = "toggle_hidden"
key = "alt-shift-d"
internal = "toggle_hidden"
description = "toggle hidden"

# pager
[[verbs]]
invocation = "bat"
key = "alt-up"                          # mapped -> `alt-b`
external = "bat --paging always {file}"
leave_broot = true
description = "open file with `bat` -> `alt-b`"

[[verbs]]
invocation = "mdcat"
key = "alt-m"
external = "mdcat --paginate {file}"
leave_broot = true
description = "open file with `mdcat`"

[[verbs]]
invocation = "jless"
key = "alt-j"
external = "jless {file}"
leave_broot = true
description = "open file with `jless`"

[[verbs]]
invocation = "hck"
key = "alt-k"
external = "hck {file}"
leave_broot = true
description = "open file with `hck`"

[[verbs]]
invocation = "xsv"
key = "alt-x"
external = "xsv table {file}"
leave_broot = true
description = "open file with `xsv`"

[[verbs]]
invocation = "print_to_copy"
key = "alt-c"
external = "bat --paging always --plain {file}"
leave_broot = true
description = "open file with `bat` to copy"

# git
[[verbs]]
invocation = "toggle_git_ignore"
key = "alt-shift-g"
internal = "toggle_git_ignore"
description = "toggle git ignore"

# sort
[[verbs]]
invocation = "sort_by_type"
key = "shift-alt-t"
internal = "sort_by_type"
description = "sort by type"

[[verbs]]
invocation = "sort_by_size"
key = "shift-alt-z"
internal = "sort_by_size"
description = "sort by size"

[[verbs]]
invocation = "sort_by_date"
key = "shift-alt-y"
internal = "sort_by_date"
description = "sort by date"

[[verbs]]
invocation = "sort_by_count"
key = "shift-alt-c"
internal = "sort_by_count"
description = "sort by count"

# stage
[[verbs]]
invocation = "toggle_stage"
key = "alt-s"
internal = "toggle_stage"
description = "toggle stage"

[[verbs]]
invocation = "toggle_staging_area"
key = "ctrl-space"
internal = "toggle_staging_area"
description = "toggle staging area"

[[verbs]]
invocation = "clear_stage"
key = "alt-z"
internal = "clear_stage"
description = "clear stage area"

[[verbs]]
invocation = "stage_all_files"
key = "alt-a"
internal = "stage_all_files"
description = "stage all matching files"

# move
[[verbs]]
invocation = "select_first"
key = "ctrl-o"                          # mapped -> `cmd-up`
internal = "select_first"
description = "go to top of the list -> `cmd-up`"

[[verbs]]
invocation = "select_last"
key = "ctrl-p"                          # mapped -> `cmd-down`
internal = "select_last"
description = "go to bottom of the list -> `cmd-down`"

[[verbs]]
invocation = "page_up"
key = "ctrl-b"                          # mapped -> `alt-up`
internal = "page_up"
description = "go to page up -> `alt-up`"

[[verbs]]
invocation = "page_down"
key = "ctrl-f"                          # mapped -> `alt-down`
internal = "page_down"
description = "go to page down -> `alt-down`"

# panel
[[verbs]]
invocation = "toggle_preview"
key = "ctrl-g"                          # mapped -> `shift-enter`
internal = "toggle_preview"
description = "open / close preview panel -> `shift-enter`"

[[verbs]]
invocation = "close_preview"
key = "alt-b"                           # mapped -> `alt-left`
apply_to = "file"
internal = "close_preview {file}"
leave_broot = false
description = "close display -> `alt-left`"

[[verbs]]
invocation = "open_preview"
key = "alt-f"                           # mapped -> `alt-right`
apply_to = "file"
internal = "open_preview {file}"
leave_broot = false
description = "display file on panel -> `alt-right`"

[[verbs]]
invocation = "panel_left"
key = "ctrl-left"
internal = "panel_left"
description = "select left panel"

[[verbs]]
invocation = "panel_right"
key = "ctrl-right"
internal = "panel_right"
description = "select right panel"

# create
[[verbs]]
invocation = "create {subpath}"
shortcut = "c"
execution = "touch {directory}/{subpath}"
leave_broot = false
description = "create file"


####################################################################################################

# theme
[skin]
# default = "rgb(131, 148, 150) rgb(0, 43, 54) / rgb(131, 148, 150) rgb(7, 54, 66)"        # base0 base03 / base01 base02
default = "gray(23) none / gray(20) none"              # transparent background
tree = "rgb(88, 110, 117) none"                        # base01 default
file = "none none"                                     # default default
directory = "rgb(38, 139, 210) none bold"              # blue default bold
exe = "rgb(211, 1, 2) none"                            # red default
link = "rgb(211, 54, 130) none"                        # magenta default
pruning = "rgb(88, 110, 117) none italic"              # base01 default italic
perm__ = "rgb(88, 110, 117) none"                      # base01 default
perm_r = "none none"                                   # default default
perm_w = "none none"                                   # default default
perm_x = "none none"                                   # default default
owner = "rgb(88, 110, 117) none"                       # base01 default
group = "rgb(88, 110, 117) none"                       # base01 default
sparse = "none none"                                   # default default
git_branch = "rgb(147, 161, 161) none"                 # base1 default
git_insertions = "rgb(133, 153, 0) none"               # green default
git_deletions = "rgb(211, 1, 2) none"                  # red default
git_status_current = "none none"                       # default default
git_status_modified = "rgb(181, 137, 0) none"          # yellow default
git_status_new = "rgb(133, 153, 0) none"               # green default
git_status_ignored = "rgb(88, 110, 117) none"          # base01 default
git_status_conflicted = "rgb(211, 1, 2) none"          # red default
git_status_other = "rgb(211, 1, 2) none"               # red default
selected_line = "none rgb(7, 54, 66)"                  # default base02
char_match = "rgb(133, 153, 0) none underlined"        # green default underlined
file_error = "rgb(203, 75, 22) none italic"            # orange default italic
flag_label = "none none"                               # default default
flag_value = "rgb(181, 137, 0) none bold"              # yellow default bold
input = "none none"                                    # default default
status_error = "rgb(203, 75, 22) rgb(7, 54, 66)"       # orange base02
status_job = "rgb(108, 113, 196) rgb(7, 54, 66) bold"  # violet base02 bold
status_normal = "none rgb(7, 54, 66)"                  # default base02
status_italic = "rgb(181, 137, 0) rgb(7, 54, 66)"      # yellow base02
status_bold = "rgb(147, 161, 161) rgb(7, 54, 66) bold" # base1 base02 bold
status_code = "rgb(108, 113, 196) rgb(7, 54, 66)"      # violet base02
status_ellipsis = "none rgb(7, 54, 66)"                # default base02
scrollbar_track = "rgb(7, 54, 66) none"                # base02 default
scrollbar_thumb = "none none"                          # default default
help_paragraph = "none none"                           # default default
help_bold = "rgb(147, 161, 161) none bold"             # base1 default bold
help_italic = "rgb(147, 161, 161) none italic"         # base1 default italic
help_code = "rgb(147, 161, 161) rgb(7, 54, 66)"        # base1 base02
help_headers = "rgb(181, 137, 0) none"                 # yellow default
help_table_border = "none none"                        # default default
preview_title = "gray(20) rgb(0, 43, 54)"
staging_area_title = "gray(22) rgb(0, 43, 54)"


####################################################################################################
