####################################################################################################

# default flags
default_flags = ""

####################################################################################################
# config
####################################################################################################

# move
[[verbs]]
invocation = "select_first"
key = "ctrl-o"
internal = "select_first"
description = "`cmd-up` -> go to top of the list"

[[verbs]]
invocation = "select_last"
key = "ctrl-p"
internal = "select_last"
description = "`cmd-down` -> go to bottom of the list"

[[verbs]]
invocation = "page_up"
key = "shift-f1"
internal = "page_up"
description = "`alt-up` -> go to page up"

[[verbs]]
invocation = "page_down"
key = "shift-f2"
internal = "page_down"
description = "`alt-down` -> go to page down"

# open
[[verbs]]
internal = "close_panel_ok"
key = "ctrl-a"
description = "`cmd-left` -> close direcotry"

[[verbs]]
internal = "open_stay!"
key = "ctrl-e"
description = "`cmd-right` -> open directory"

[[verbs]]
invocation = "root_up"
key = "ctrl-v"
internal = "root_up"
description = "`ctrl-cmd-up` -> move tree root up"

[[verbs]]
invocation = "open_leave"
key = "ctrl-x"
cmd = ":cd"
description = "`ctrl-cmd-down` -> go into directory"

[[verbs]]
key = "alt-ctrl-f6"
external = "command open {file}"
leave_broot = false
description = "`cmd-enter` -> open according to OS"

# panel
[[verbs]]
invocation = "toggle_preview"
key = "alt-ctrl-f7"
internal = "toggle_preview"
description = "`ctrl-cmd-space` -> open / close preview panel"

[[verbs]]
invocation = "close_preview"
key = "alt-ctrl-f8"
apply_to = "file"
internal = "close_preview {file}"
leave_broot = false
description = "`ctrl-cmd-left` -> close display"

[[verbs]]
invocation = "open_preview"
key = "alt-ctrl-f9"
apply_to = "file"
internal = "open_preview {file}"
leave_broot = false
description = "`ctrl-cmd-right` -> display file on panel"

[[verbs]]
invocation = "panel_left"
key = "ctrl-left"
internal = "panel_left"
description = "select left panel"

[[verbs]]
invocation = "panel_right"
key = "ctrl-right"
internal = "panel_right"
description = "select right panel"

# directory
[[verbs]]
invocation = "mk {subpath}"
key = "alt-ctrl-f10"
execution = "mkdir {directory}/{subpath}"
leave_broot = false
auto_exec = false
description = "`ctrl-cmd-shift` -> create directory"

# move
[[verbs]]
external = "mv {file} {other-panel-directory}"
invocation = "move_to_pane"
key = "alt-ctrl-f11"
leave_broot = false
auto_exec = false
description = "`ctrl-cmd-alt` -> move file to pane"

# copy
[[verbs]]
external = "cp -r {file} {other-panel-directory}"
invocation = "copy_to_pane"
key = "alt-ctrl-f12"
leave_broot = false
auto_exec = false
description = "`ctrl-cmd-cmd` -> copy file to pane"

# rename
[[verbs]]
external = "mv {file} {parent}/{new_filename}"
invocation = "rename {new_filename:file-name}"
shortcut = "rn"
key = "ctrl-l"
leave_broot = false
auto_exec = false
description = "`shift-alt` -> rename file"

# create
[[verbs]]
invocation = "create {subpath}"
shortcut = "c"
key = "shift-f6"
execution = "touch {directory}/{subpath}"
leave_broot = false
auto_exec = false
description = "`ctrl-cmd-enter` -> create file"

# remove
[[verbs]]
external = "rm -rf {file}"
invocation = "rm"
key = "shift-f7"
leave_broot = false
auto_exec = false
description = "`ctrl-cmd-delete` -> delete file"

# stage
[[verbs]]
invocation = "toggle_staging_area"
key = "shift-f10"
internal = "toggle_staging_area"
description = "`alt` -> toggle staging area"

[[verbs]]
invocation = "stage_all_files"
key = "alt-f1"
internal = "stage_all_files"
description = "`alt-a` -> stage all matching files"

[[verbs]]
invocation = "toggle_stage"
key = "ctrl-f9"
internal = "toggle_stage"
description = "`alt-s` -> toggle stage"

[[verbs]]
invocation = "clear_stage"
key = "alt-ctrl-f5"
internal = "clear_stage"
description = "`alt-z` -> clear stage area"

# quit
[[verbs]]
invocation = "quit"
key = "ctrl-f7"
internal = "quit"
description = "`alt-q` -> quit broot"

# refresh
[[verbs]]
invocation = "refresh"
key = "ctrl-f8"
internal = "refresh"
description = "`alt-r` -> refresh tree"

# editor
[[verbs]]
invocation = "micro"
key = "ctrl-j"
execution = "micro {file}"
leave_broot = false
description = "`delete-cmd` -> open file with `micro` editor"

[[verbs]]
invocation = "helix"
key = "ctrl-n"
execution = "hx {file}"
leave_broot = false
description = "`delete-alt` -> open file with `helix` editor"

# search
[[verbs]]
invocation = "total_search"
key = "alt-f7"
internal = "total_search"
description = "`alt-f` -> search again but on all children"

[[verbs]]
invocation = "next_match"
key = "ctrl-f1"
internal = "next_match"
description = "`alt-l` -> go to next match"

[[verbs]]
invocation = "previous_match"
key = "alt-f9"
internal = "previous_match"
description = "`alt-h` -> go to previous match"

# view
[[verbs]]
invocation = "toggle_hidden"
key = "shift-alt-f5"
internal = "toggle_hidden"
description = "`alt-shift-d` -> toggle hidden"

[[verbs]]
invocation = "toggle_files"
key = "shift-alt-f7"
internal = ":toggle_files"
description = "`alt-shift-f` -> toggle files"

# pager
[[verbs]]
invocation = "bat"
key = "alt-f2"
external = "bat --paging always {file}"
leave_broot = true
description = "`alt-b` -> open file with `bat`"

[[verbs]]
invocation = "mdcat"
key = "ctrl-f2"
external = "mdcat --paginate {file}"
leave_broot = true
description = "`alt-m` -> open file with `mdcat`"

[[verbs]]
invocation = "jless"
key = "alt-f11"
external = "jless {file}"
leave_broot = true
description = "`alt-j` -> open file with `jless`"

[[verbs]]
invocation = "hck"
key = "alt-f12"
external = "hck {file}"
leave_broot = true
description = "`alt-k` -> open file with `hck`"

[[verbs]]
invocation = "xsv"
key = "alt-ctrl-f4"
external = "xsv table {file}"
leave_broot = true
description = "`alt-x` -> open file with `xsv`"

# copy
[[verbs]]
invocation = "print_to_copy"
key = "alt-f4"
external = [
  "sh",
  "-e",
  "/Users/drivas/.archive/cerberus/broot/copy.sh",
  "{file}",
]
leave_broot = false
description = "`alt-c` -> open file with `bat` to copy"

# git
[[verbs]]
invocation = "toggle_git_ignore"
key = "alt-shift-f8"
internal = "toggle_git_ignore"
description = "`alt-shift-g` -> toggle git ignore"

# sort
[[verbs]]
invocation = "sort_by_type"
key = "ctrl-shift-f10"
internal = "sort_by_type"
description = "`alt-shift-t` -> sort by type"

[[verbs]]
invocation = "sort_by_size"
key = "alt-ctrl-shift-f5"
internal = "sort_by_size"
description = "`alt-shift-z` -> sort by size"

[[verbs]]
invocation = "sort_by_date"
key = "alt-ctrl-shift-f4"
internal = "sort_by_date"
description = "`alt-shift-y` -> sort by date"

[[verbs]]
invocation = "sort_by_count"
key = "alt-shift-f4"
internal = "sort_by_count"
description = "`alt-shift-c` -> sort by count"


####################################################################################################

# command line move & delete
[[verbs]]
key = "alt-b"
internal = ":input_go_word_left"

[[verbs]]
key = "alt-f"
internal = ":input_go_word_right"

[[verbs]]
key = "ctrl-w"
internal = ":input_del_word_left"

[[verbs]]
key = "alt-d"
internal = ":input_del_word_right"


####################################################################################################

# theme
[skin]
# default = "rgb(131, 148, 150) rgb(0, 43, 54) / rgb(131, 148, 150) rgb(7, 54, 66)"        # base0 base03 / base01 base02
default = "gray(23) none / gray(20) none"              # transparent background
tree = "rgb(88, 110, 117) none"                        # base01 default
file = "none none"                                     # default default
directory = "rgb(38, 139, 210) none bold"              # blue default bold
exe = "rgb(211, 1, 2) none"                            # red default
link = "rgb(211, 54, 130) none"                        # magenta default
pruning = "rgb(88, 110, 117) none italic"              # base01 default italic
perm__ = "rgb(88, 110, 117) none"                      # base01 default
perm_r = "none none"                                   # default default
perm_w = "none none"                                   # default default
perm_x = "none none"                                   # default default
owner = "rgb(88, 110, 117) none"                       # base01 default
group = "rgb(88, 110, 117) none"                       # base01 default
sparse = "none none"                                   # default default
git_branch = "rgb(147, 161, 161) none"                 # base1 default
git_insertions = "rgb(133, 153, 0) none"               # green default
git_deletions = "rgb(211, 1, 2) none"                  # red default
git_status_current = "none none"                       # default default
git_status_modified = "rgb(181, 137, 0) none"          # yellow default
git_status_new = "rgb(133, 153, 0) none"               # green default
git_status_ignored = "rgb(88, 110, 117) none"          # base01 default
git_status_conflicted = "rgb(211, 1, 2) none"          # red default
git_status_other = "rgb(211, 1, 2) none"               # red default
selected_line = "none rgb(7, 54, 66)"                  # default base02
char_match = "rgb(133, 153, 0) none underlined"        # green default underlined
file_error = "rgb(203, 75, 22) none italic"            # orange default italic
flag_label = "none none"                               # default default
flag_value = "rgb(181, 137, 0) none bold"              # yellow default bold
input = "none none"                                    # default default
status_error = "rgb(203, 75, 22) rgb(7, 54, 66)"       # orange base02
status_job = "rgb(108, 113, 196) rgb(7, 54, 66) bold"  # violet base02 bold
status_normal = "none rgb(7, 54, 66)"                  # default base02
status_italic = "rgb(181, 137, 0) rgb(7, 54, 66)"      # yellow base02
status_bold = "rgb(147, 161, 161) rgb(7, 54, 66) bold" # base1 base02 bold
status_code = "rgb(108, 113, 196) rgb(7, 54, 66)"      # violet base02
status_ellipsis = "none rgb(7, 54, 66)"                # default base02
scrollbar_track = "rgb(7, 54, 66) none"                # base02 default
scrollbar_thumb = "none none"                          # default default
help_paragraph = "none none"                           # default default
help_bold = "rgb(147, 161, 161) none bold"             # base1 default bold
help_italic = "rgb(147, 161, 161) none italic"         # base1 default italic
help_code = "rgb(147, 161, 161) rgb(7, 54, 66)"        # base1 base02
help_headers = "rgb(181, 137, 0) none"                 # yellow default
help_table_border = "none none"                        # default default
preview_title = "gray(20) rgb(0, 43, 54)"
staging_area_title = "gray(22) rgb(0, 43, 54)"


####################################################################################################
